allennlp/common/checks.py
allennlp/layers/embeddings.py
tests/data/embeddings_test.py

Sorry, I made the previous PR before the repo went public, so that fork was deleted.

Pytorch embedding v2

---

.pylintrc
allennlp/__init__.py
allennlp/nlp_api.py
tests/nlp_api_test.py

There is very little actual implementation code here as of now - this is mostly just a means of abstracting some decisions away by redirection.  There will be a bit more implementation code in here once `from_params` is implemented, because that will be at least a little complicated, but that needs to wait until we have more experiment configuration code in place.

Added NlpApi class

---

allennlp/service/README.md
allennlp/service/index.html
allennlp/service/server.py
requirements.txt
tests/service/server_test.py

most of this will change once we know what the models we want to support look like, but this should give us a skeleton to build on. 
(this is a first step toward https://app.asana.com/0/358382652518673/358435950435832)

prototype flask app for serving models + bare-bones webapp

---

allennlp/commands/train.py
allennlp/data/iterators/adaptive_iterator.py
allennlp/data/iterators/data_iterator.py
allennlp/models/bidaf.py
allennlp/models/decomposable_attention.py
allennlp/models/semantic_role_labeler.py
allennlp/models/simple_tagger.py
allennlp/nn/util.py
allennlp/run
allennlp/training/trainer.py
experiment_config/bidaf.json
experiment_config/semantic_role_labeler.json
tests/commands/train_test.py

There are a bunch of unrelated things in here.  I tried to split them out into their own commits, so you can look at the commit log and click on individual commits if you want a better picture of what's in here and why.

Minor training improvements

---

allennlp/training/trainer.py
experiment_config/bidaf.json

This solves the exploding gradient problem.

Add gradient clipping in the backward pass with a hook

---

allennlp/models/semantic_role_labeler.py
scripts/srl-eval.pl
tests/models/semantic_role_labeler_test.py

This is half of the work for the SRL metrics - this will allow us to evaluate trained models offline against the official eval script, which i've also included verbatim, seems a reasonable thing to have in `scripts`. The test that the perl script runs on the output of the functions I wrote is a little fast and loose, but I couldn't think of a better way to do it.

Srl metrics

---

allennlp/commands/train.py
allennlp/service/servable/models/bidaf.py
allennlp/service/servable/models/decomposable_attention.py
allennlp/service/servable/models/semantic_role_labeler.py
allennlp/service/servable/servable.py
allennlp/training/trainer.py
experiment_config/bidaf.json
experiment_config/decomposable_attention.json
experiment_config/semantic_role_labeler.json
tests/commands/train_test.py
tests/service/servables/bidaf_test.py
tests/service/servables/decomposable_attention_test.py
tests/service/servables/srl_test.py

This PR:
1. Makes tqdm more compatible with docker / kubernetes log capturing.
2. Moves trainer parameters in experiment configs into their own section.
3. Fixes a bug where validation metrics were overwriting training metrics.

Small collection of misc fixes

---

allennlp/data/dataset_readers/snli.py
allennlp/models/decomposable_attention.py
allennlp/service/servable/servable.py
experiment_config/decomposable_attention.json
tests/service/servables/decomposable_attention_test.py

Mostly this is just an updated configuration file; very little actual code change here.

Training for decomposable attention

---

allennlp/service/static/index.html

I was having a problem where the forms would not accept submissions when the application was first started.  I believe this is because the page was refreshed on the submit despite the `e.preventDefaults`.  This did not happen once tabs had been switched.
I was unable to find the problem, so I removed the forms and instead handle the event in the button's `onClick`.  This is not ideal because it will not trigger form submission on enter, but it's better than the previous case.

Forms work on start

---

kubernetes-webdemo.yaml
tests/notebooks_test.py

I also increased the memory the kubernetes-webdemo requests.

Fix docker build by disabling notebook tests.

---

tests/service/predictors/srl_test.py

hopefully this solves Pradeep's last failing test issue

use pytest.approx when comparing unarchived models

---

allennlp/training/trainer.py

Fix calculation of patience and best epoch

---

allennlp/commands/train.py
allennlp/data/dataset_readers/squad.py
allennlp/data/instance.py
allennlp/data/vocabulary.py
allennlp/models/bidaf.py
experiment_config/bidaf.json
requirements.txt
scripts/evaluate_squad_model.py
scripts/squad_eval.py

And other miscellaneous fixes to make this actually work

Adding an evaluation script for SQuAD

---

allennlp/common/file_utils.py
tests/common/file_utils_test.py

S3 (where we're mostly planning to host files, I believe) returns a hash of the file as the `ETag` header. This PR uses this to determine if a cached version is stale. Basically:
* `url_to_filename` now takes an extra `etag` parameter and incorporates it into the filename
* given a URL, we make a `HEAD` request and get the `ETag` header
* we now check our cache for the filename based on the correct URL and the new ETag
If the file is on a server that doesn't return the `ETag` header, then it will behave just as it did before (which is bad, I guess)
Pro: eliminates bad case where you have a stale version cached and don't download the newest
Con: requires the HTTP `HEAD` request every time, even if the file is already in the cache
this seems like a good tradeoff to me.

make HEAD requests, use ETag to decide whether to download

---

allennlp/data/dataset_readers/snli.py
allennlp/models/decomposable_attention.py
allennlp/modules/feedforward.py
experiment_config/bidaf.json
experiment_config/decomposable_attention.json
tests/data/dataset_readers/snli_reader_test.py

This adds an "append_null" option to the SNLI reader, adds dropout to the feed forward nets, and changes the default parameter file a bit.

Updated decomposable attention code to match paper

---

allennlp/commands/train.py
allennlp/models/model.py
allennlp/training/trainer.py
experiment_config/bidaf.json
experiment_config/decomposable_attention.json
experiment_config/semantic_role_labeler.json
scripts/train_fixtures.py
tests/commands/train_test.py
tests/fixtures/bidaf/experiment.json
tests/fixtures/decomposable_attention/experiment.json
tests/fixtures/srl/experiment.json
tests/models/archival_test.py
tests/models/bidaf_test.py
tests/models/decomposable_attention_test.py
tests/models/semantic_role_labeler_test.py
tutorials/getting_started/getting_started.md
tutorials/getting_started/simple_tagger.json

it was actually a pretty simple change.
this reminds me that I need to give more thought to positional vs named arguments to our command line tools, but I'll leave that out of this PR.

move serialization_dir from config file to command line arg to train

---

allennlp/common/file_utils.py

this should solve the issue where the cache gets corrupt entries if a download gets interrupted

download urls to tempfile then copy to cache

---

allennlp/data/vocabulary.py

Thanks @joelgrus and @OyvindTafjord for help finding this.

Don't write newlines to vocab file

---

allennlp/commands/serve.py
allennlp/service/predictors/bidaf.py
tests/commands/predict_test.py

This also updates our MC model to our best result.

Add best_span_string back into the MC prediction API

---

kubernetes-webdemo.yaml

* 4 replicas.
* Explicit image version.

Update kubernetes-webdemo configuration.

---

allennlp/service/server_sanic.py
tests/service/server_sanic_test.py

I'm not thrilled with this code, but it would take a lot more work to make it really good.
it can be disabled with an environment variable, in case things go awry.

add cache to web server

---

allennlp/service/static/css/main.css
allennlp/service/static/index.html

Per @schmmd's request, this PR:
- Styles SRL table output (reduces padding, uses subtler colors)
- Fixes excessive content scroll bug
- Styles passage context output (increases readability, adds blue highlight)
- Unminifies CSS
- Removes unused `<style>` from HTML.

Demo CSS Tweaks

---

allennlp/service/static/index.html

This PR:
- Disables the Run buttons when global `outputState` is set to `working`
- Removes an unused const (junk DNA from when i was building the UI)

Demo UI - Reintroducing working state to submit button

---

allennlp/commands/train.py
allennlp/data/vocabulary.py
tests/data/vocabulary_test.py

unify how Vocabs are created

---

allennlp/commands/serve.py
allennlp/service/static/index.html

- Adds some SRL examples which showcase difficult/rarer tags
- Update some non-trival TE examples
- Update SRL model

better examples, update SRL model

---

allennlp/data/dataset_readers/language_modeling.py
allennlp/data/dataset_readers/semantic_role_labeling.py
allennlp/data/dataset_readers/sequence_tagging.py
allennlp/data/dataset_readers/snli.py
allennlp/data/dataset_readers/squad.py
allennlp/data/token_indexers/token_indexer.py

Fixes #181.  I'm not thrilled with the method name I used here, but that's easy to change.

Centralize creation of TokenIndexer dictionary

---

README.md
setup.py

I already pushed the tag to pypi, these are just a few minor tweaks to the readme and `setup.py` reflecting python3.6 and the fact you can now install via pip.

minor changes to setup and readme for pip package

---

allennlp/service/server_sanic.py

now logs everything as a single JSON object, also adds some brief output for textual-entailment and machine-comprehension

better prediction logging

---

kubernetes-webdemo.yaml

bump webdemo

---

allennlp/commands/evaluate.py
allennlp/commands/train.py
allennlp/common/util.py

I confirmed the problem and confirmed that this fixes it.

Fixes #304 by setting random seeds

---

allennlp/training/trainer.py
tests/training/trainer_test.py

fix epoch bug

---

allennlp/data/token_indexers/__init__.py
allennlp/data/token_indexers/dep_label_indexer.py
allennlp/data/token_indexers/pos_tag_indexer.py
allennlp/data/token_indexers/single_id_token_indexer.py
allennlp/data/tokenizers/word_splitter.py
allennlp/service/predictors/semantic_role_labeler.py
tests/data/token_indexers/dep_label_indexer_test.py
tests/data/token_indexers/pos_tag_indexer_test.py
tests/data/token_indexers/single_id_token_indexer_test.py

Add TokenIndexers for POS tags and dependency labels

---

allennlp/modules/seq2seq_encoders/__init__.py
allennlp/modules/seq2seq_encoders/intra_sentence_attention.py
allennlp/modules/similarity_functions/multiheaded.py
allennlp/modules/similarity_functions/similarity_function.py
tests/modules/seq2seq_encoders/intra_sentence_attention_test.py

Adding an intra-sentence attention encoder (with optional multi-head attention).

---

allennlp/training/trainer.py

* broke `Trainer.train()` up into a lot of different functions
* got rid of all the `None` checks by writing wrapper functions that no-op in those cases
* created `TensorboardWriter` abstraction for the same reason
let me know if you don't like any of the design choices here
Fixes #204

big refactoring of Trainer

---

allennlp/models/semantic_role_labeler.py
tests/service/predictors/bidaf_test.py
tests/service/predictors/decomposable_attention_test.py
tests/service/predictors/srl_test.py

I think this is actually the right fix + I added a bunch of tests that would have caught this.

fix broken predictor + add comprehensive predictor tests

---

allennlp/training/trainer.py

fixes #345 (I checked by continuing to train a model trained on the GPU on the CPU).

use device mapping for optimiser state

---

allennlp/commands/train.py
tests/commands/train_test.py

`Dataset.index_instances()` doesn't return a value. so currently we're assigning `None` to test_data.
added a test for this.

don't assign from index_instances

---

allennlp/common/testing/test_case.py

use /tmp to hold temp test directories

---

allennlp/nn/util.py
tests/nn/util_test.py

I want to use `logsumexp` in some other stuff I'm doing, so I'm just pulling this in from the coref branch.  I added a test for it and did some minor cleanup while I was at it.

Adding logsumexp to nn.util

---

allennlp/common/file_utils.py

Fixes https://github.com/allenai/allennlp/issues/425

Close TQDM progress

---

allennlp/data/token_indexers/__init__.py
allennlp/data/token_indexers/ner_tag_indexer.py
allennlp/data/tokenizers/token.py
tests/data/token_indexers/ner_tag_indexer_test.py
tests/fixtures/encoder_decoder/simple_seq2seq/experiment.json

I also changed one of the test configuration fixtures to actually use this, so we have an example to point to when people ask.

Add NER tag token indexer

---

allennlp/modules/seq2seq_encoders/__init__.py

Sorry it took me so long to get to this @OyvindTafjord!

add debug logging statement for pip-install issue with custom extension

---

Dockerfile
README.md
allennlp/commands/__init__.py
allennlp/commands/train.py
allennlp/common/checks.py
build_tools/travis/test_script.sh
tests/common/pythonhashseed_test.py

Remove PYTHONHASHSEED.

---

allennlp/models/simple_tagger.py
tests/models/simple_tagger_test.py

fix simple tagger

---

demo/src/App.js
demo/src/components/Header.js

Use longer names for models.

---

allennlp/models/encoder_decoders/simple_seq2seq.py

Just deleting a print statement we missed earlier.

Deleted an unnecessary print statement

---

scripts/ai2-internal/deploy-staging-demo.sh

This will be used by TeamCity for staging deploys.

Add a script that deploys the demo to staging.

---

scripts/ai2-internal/deploy-production-demo.sh
scripts/ai2-internal/deploy-staging-demo.sh

Also:
* Increase memory to 3 GB.
* Decrease production replicas to 4.

Fix bug in production deployment script

---

tutorials/Makefile

you learn new stuff about make and bash and docker every day

fix Makefile to work in docker

---

demo/public/css/main.css

Some quick / small CSS tweaks courtesy of @aaronsarnat and I's jam session.
* Comments.
* Make the max-width of nodes variable based on viewport width.
* Fix a wrapping issue in the passage.

Polish for the new Hierplane based SRL Demo.

---

allennlp/service/db.py
allennlp/service/server_sanic.py

* Disable database if there's an initial connection error.
* Don't display a permalink if there's a connection error.
* Set a 5 second database timeout.

Add a port option for database.

---

allennlp/service/db.py

autocommit

---

STYLE.md

These are the rules we've generally been following, I'm just putting them into a document that we can reference when questions come up.  Does this seem reasonable?  Anything to change or add?

Adding a proposed style guide

---

tutorials/getting_started/another_model_example.md
tutorials/getting_started/using_in_your_repo.md

I re-read Joel's tutorial before starting this one, and realized that there's more overlap than I thought.  I wasn't sure how to position this one - I didn't want to just duplicate what Joel already had, but I thought another example would be helpful.  It ended up considerably longer than I thought it might (about 4 times longer than the one that's there) - maybe this should be in the "deep dive" section?  I'm not sure the tone or the aim of this tutorial really fits in a "deep dive", though.

Added another model tutorial

---

tutorials/getting_started/using_in_your_repo.md

I originally wrote the tutorial as stepping through commits in an external repo, but that doesn't allow updating the repo at all, which is problematic.  I also said that users should download and make their own dataset, which isn't very nice.  This removes references to specific commits, and changes paths to point to some data that I uploaded to S3, so the tutorial is more self-contained.

Remove references to individual commits in tutorial, add data

---

demo/public/css/main.css

Fixes https://github.com/allenai/allennlp/issues/532

Allow the header to resize on small resolutions.

---

allennlp/common/checks.py
allennlp/models/crf_tagger.py
allennlp/models/decomposable_attention.py
allennlp/models/reading_comprehension/bidaf.py
allennlp/models/semantic_role_labeler.py
allennlp/models/simple_tagger.py

Add a check_dimensions_match function

---

allennlp/data/fields/__init__.py
allennlp/data/fields/field.py
allennlp/data/fields/label_field.py
allennlp/data/fields/list_field.py
allennlp/data/fields/text_field.py
allennlp/nn/util.py

This doesn't result in any changes for our current `Fields`, but it is necessary for the `ListField[ProductionRuleField]` that we use in the semantic parser.

Make ListField batching robust

---

tutorials/notebooks/data_pipeline.ipynb
tutorials/notebooks/embedding_tokens.ipynb

fixes #608 and fixes #610, although not the deployment issue that we still have - i'm not sure if @joelgrus fixed that in more of a permanent way? LMK if you want me to take more of a look at that part.

fix tutorials, make namespace vs keys unambiguous

---

allennlp/service/server_flask.py
allennlp/service/server_simple.py
requirements.txt

maybe this will make production deployments more stable?
http://flask.pocoo.org/docs/0.12/deploying/
http://flask.pocoo.org/docs/0.12/deploying/wsgi-standalone/#gevent

run flask with gevent

---

allennlp/training/metrics/span_based_f1_measure.py
tests/training/metrics/span_based_f1_measure_test.py

Fixes part of #667 - I need to actually run a full model really to see if the results are identical. It's very possible there are other quirks which are less obvious. I'm also not 100% sure i'm handling this correctly - I only went from the comment in the perl script not the actual code, because, well, perl.

handle continued spans correctly in SpanBasedF1Measure

---

Dockerfile

See: https://github.com/NVIDIA/nvidia-docker/issues/410 for why this is necessary....
Fixes #697

add driver label to Dockerfile

---

scripts/ai2-internal/run_with_beaker.sh

* `latest` is no longer supported for datasets.
* adds `--file-friendly-logging`.

Fix Beaker scripts.

---

allennlp/data/iterators/adaptive_iterator.py
allennlp/data/iterators/basic_iterator.py
allennlp/data/iterators/bucket_iterator.py
tests/data/iterators/adaptive_iterator_test.py
tests/data/iterators/bucket_iterator_test.py
tests/fixtures/encoder_decoder/simple_seq2seq/experiment.json
tests/fixtures/encoder_decoder/simple_seq2seq/experiment_with_attention.json

ok, this should address the remaining points that I merged too fast for

require sorting_keys for bucket_iterator

---

allennlp/models/encoder_decoders/wikitables_semantic_parser.py

This change made performance go from ~12% to ~22%.  That's still a lower bound on performance, though; next up is to get actual performance numbers, instead of a bound.

Normalize question/table similarity scores

---

scripts/verify.py

My original design was overly complicated and a bit obnoxious to use.  I'm pretty sure I'm the only one using this script presently.

Remove the --all flag and make --checks optional.

---

allennlp/commands/elmo.py
tests/commands/elmo_test.py

Partially addresses https://github.com/allenai/allennlp/issues/785.

Add options --all, --top, and --average to elmo command

---

allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py
allennlp/data/dataset_readers/wikitables/wikitables_preprocessed_dataset_reader.py
allennlp/data/fields/knowledge_graph_field.py

Doing this, and setting min count for vocab to be 3, as in the paper, reduces the vocab size from ~87k to ~8k.  Currently running an experiment to see the performance difference: http://beaker.allenai.org/tk/tk_4dwh71plvixl.
I haven't checked to see if this breaks tests...  It probably does.

Allow not using table entities for vocab creation

---

allennlp/common/util.py
allennlp/training/trainer.py

I tested this on my p2.xlarge, it seems to work, not sure how else to test it

log GPU memory

---

allennlp/training/trainer.py
tests/training/trainer_test.py

Add best validation metric and epoch to output metrics

---

allennlp/commands/elmo.py
tests/commands/elmo_test.py

Fixes https://github.com/allenai/allennlp/issues/837
This also fixes some type annotations.

Handle batches with only a single empty sentence

---

allennlp/common/params.py
tests/common/params_test.py

Fixes https://github.com/allenai/allennlp/issues/838

Convert URLs to cached files in add_file_to_archive

---

allennlp/commands/serve.py
scripts/wikitables_eval.py
training_config/wikitables_parser.json

This model gets ~26% parse accuracy during training on the dev set, ~23% accuracy using the eval script on the same dev set.  Still ~20% below the original parser's performance...

Updated the parser model in the demo, improved the wikitables eval script

---

allennlp/commands/evaluate.py
allennlp/commands/train.py

Fixes #792, not sure whether it's useful to also have a `test_dataset_reader`, thoughts?

add ability to have seperate dataset readers for train and val

---

allennlp/service/server_simple.py
tutorials/getting_started/making_predictions_and_creating_a_demo.md
tutorials/how_to/visualizing_model_internals.md

I _think_ I modified everything I needed to for updating the demo tutorials.  I might have missed something, though - this was a little rushed.

Update visualization howto

---

allennlp/commands/serve.py
tutorials/getting_started/creating_a_model.md
tutorials/getting_started/crf_tagger.json

update NER model in demo to latest + add some words about it to the tutorial

---

allennlp/commands/serve.py
tests/models/sniff_test.py

switch demo model to use elmo

---

allennlp/data/dataset_readers/nlvr.py
allennlp/data/semparse/__init__.py
allennlp/data/semparse/action_space_walker.py
allennlp/data/semparse/type_declarations/grammar_state.py
allennlp/data/semparse/type_declarations/type_declaration.py
allennlp/data/semparse/worlds/nlvr_world.py
doc/api/allennlp.data.semparse.rst
scripts/get_nlvr_logical_forms.py
tests/data/dataset_readers/nlvr_test.py
tests/data/semparse/action_space_walker_test.py
tests/data/semparse/worlds/nlvr_world_test.py

I added a class `ActionSpaceWalker` for enumerating logical forms given a grammar, and a script to preprocess a NLVR dataset to get logical forms given agenda.

Get logical forms from grammar (and an agenda)

---

README.md
allennlp/version.py
tutorials/README.md

You can test the pip package with `pip install -i https://testpypi.python.org/pypi --extra-index-url https://pypi.org/simple allennlp`.

Release v0.4.0

---

allennlp/models/constituency_parser.py
tests/models/constituency_parser_test.py

- Only considers unmasked spans (this probably didn't matter but it's nice to be sure) for decoding.
- Fix up some docs

Fix span masking

---

allennlp/commands/train.py

Beaker creates the output directory before we start training, so the stuff we added to check that the directory doesn't exist makes everything crash on beaker.  This fixes that.  The recovery logic was also split between a couple of different places, and this PR moves it all into one place.

Combine recovery logic, make it not crash on beaker

---

allennlp/__init__.py

add try except block with helpful message

---

allennlp/data/dataset_readers/penn_tree_bank.py
allennlp/service/predictors/constituency_parser.py
tests/fixtures/constituency_parser/constituency_parser.json
tests/fixtures/constituency_parser/experiment_no_evalb.json

I need the PTB style POS tags, not the more general ones from Universal Dependencies

pos -> tag

---

allennlp/service/predictors/wikitables_parser.py

Fixes a bug in #831 by changing file suffix from csv to tsv.

Bug fix in execute logical form

---

allennlp/modules/seq2seq_encoders/__init__.py

add ImportError to lstm import

---

tutorials/README.md

Add the link to the "how-to" tutorials README

Add a link to the span representations tutorial

---

allennlp/data/iterators/__init__.py
allennlp/data/iterators/epoch_tracking_bucket_iterator.py
allennlp/models/encoder_decoders/nlvr_semantic_parser.py
doc/api/allennlp.data.iterators.rst
tests/data/iterators/epoch_tracking_bucket_iterator_test.py
tests/fixtures/encoder_decoder/nlvr_semantic_parser/experiment.json
tests/models/encoder_decoders/nlvr_semantic_parser_test.py

This depends on #971. I'll rebase this branch after that PR gets merged.

Dynamically decrease checklist cost weight between epochs

---

allennlp/commands/fine_tune.py
allennlp/commands/train.py
allennlp/common/util.py
allennlp/training/trainer.py

- Adds a catch for Keyboard interrupts during training, which then tries to make a model archive using the serialisation directory before raising
- Pulls some tensorboard logging out into methods
- Adds a `prepare_global_logging` function to configure Tqdm, `logging` and stdout/stderr streams

Keyboard interrupt + training admin

---

MANIFEST.in
README.md
allennlp/commands/elmo.py
allennlp/commands/evaluate.py
allennlp/commands/fine_tune.py
allennlp/commands/make_vocab.py
allennlp/commands/predict.py
allennlp/commands/serve.py
allennlp/commands/subcommand.py
allennlp/commands/train.py
bin/allennlp
setup.py
tests/commands/main_test.py
tutorials/getting_started/creating_a_model.md
tutorials/getting_started/installation.md
tutorials/getting_started/making_predictions_and_creating_a_demo.md
tutorials/getting_started/training_and_evaluating.md
tutorials/getting_started/using_in_your_repo.md
tutorials/how_to/elmo.md

This was waaaay easier than I thought 👍 
Fixes #946

add allennlp command

---

allennlp/commands/predict.py

fix predictor issue for constituency parser

---

README.md

Match the main README to the installation one
https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/installation.md

Add docker port to README

---

allennlp/service/predictors/semantic_role_labeler.py
tests/models/sniff_test.py
tests/service/predictors/srl_test.py

make srl predictor more robust

---

allennlp/training/learning_rate_schedulers.py
allennlp/training/optimizers.py

Just updating our available optimisers, etc.

add some new optimisers and a cosine LR schedule

---

allennlp/data/dataset_readers/seq2seq.py

This minor pr:
- Adds caching for seq2seq data
- Fixes the kwarg format issue @matt-gardner mentioned in #1030

Minor enhancements to seq2seq data reader

---

allennlp/models/semantic_role_labeler.py

- Adds label smoothing
- Don't log a billion metrics during training, or ever, I have never used them

srl model tweaks

---

allennlp/common/file_utils.py

Update file_utiles.py such that it could accept customized ALLENNLP_CACHE_ROOT.

Customizing CACHE_ROOT in file_utiles.py

---

allennlp/models/encoder_decoders/wikitables/wikitables_decoder_step.py
allennlp/models/encoder_decoders/wikitables/wikitables_semantic_parser.py
training_config/wikitables_parser.json

Sadly, this didn't seem like it made a difference.  But it was used in the original model.

Add dropout

---

demo/public/css/main.css
demo/src/App.js
demo/src/components/Menu.js

I fixed the original issue in https://github.com/allenai/allennlp/pull/1074 (see https://github.com/allenai/allennlp/pull/1081) by moving the CSS into `main.css`.

Move the top nav bar to the left pane.

---

.pylintrc
allennlp/common/testing/model_test_case.py
allennlp/common/util.py
allennlp/modules/__init__.py
allennlp/nn/util.py
tests/nn/util_test.py

This is another one that's just moving over small modifications from the `wikitables` branch (that have already been reviewed).  I'll once again just merge this, unless I hear some objections.

Moving over modifications to common / util modules

---

allennlp/data/fields/__init__.py
allennlp/data/fields/knowledge_graph_field.py
allennlp/data/fields/production_rule_field.py
doc/api/allennlp.data.fields.rst
tests/data/fields/knowledge_graph_field_test.py
tests/data/fields/production_rule_field_test.py

This is the last big piece from the `wikitables` branch besides the models and dataset readers themselves.  This one has also already been reviewed, so don't feel like you have to go over this really carefully if you don't want to.

Adding KnowledgeGraphField and ProductionRuleField

---

allennlp/training/trainer.py

Helpful when the loss is already small

increase metrics logging precision

---

Dockerfile
scripts/EVALB/Makefile

clean EVALB via make, add to Dockerfile

---

allennlp/data/iterators/basic_iterator.py

my lone office hours customer yesterday was confused by this comment

fix comment

---

tutorials/getting_started/using_as_a_library_pt1.md
tutorials/getting_started/using_as_a_library_pt2.md

After this is merged, I'll rename the tutorials on the website in https://github.com/allenai/allennlp-website/pull/43.

Rename tutorials so they're clearly connected.

---

allennlp/models/semantic_parsing/nlvr/nlvr_coverage_semantic_parser.py
allennlp/models/semantic_parsing/wikitables/wikitables_erm_semantic_parser.py
allennlp/nn/decoding/decoder_trainers/expected_risk_minimization.py
tests/fixtures/semantic_parsing/nlvr_coverage_semantic_parser/experiment.json
tests/fixtures/semantic_parsing/wikitables/experiment-erm.json

Prune finished states in ERM

---

README.md
allennlp/version.py
tutorials/README.md
tutorials/getting_started/using_as_a_library_pt1.md
tutorials/getting_started/using_as_a_library_pt2.md

This PR is for our [draft release of v0.4.3](https://github.com/allenai/allennlp/releases/edit/untagged-ba9f701e6e0b405a604d)
I pushed a pip packages to testpypi, created a fresh environment, and ran tests.  The only tests that failed had to do with the fact that I didn't copy the `scripts` or `tutorials` folders into my fresh environment.
Fixes https://github.com/allenai/allennlp/issues/1217.

Release v0.4.3

---

allennlp/version.py

Forgot to do this during the release...

Uptick version to unreleased.

---

setup.py

Set long_description_content_type to markdown in setup.py.

---

MANIFEST.in

This is another thing that ought to be distributed with the pypi tarball...last thing, i promise 🙂

Add LICENSE to source distribution

---

allennlp/tests/training/trainer_test.py
allennlp/training/trainer.py

Check that a model is actually an improvement on the current best and not just equal to it.
fixes : #1237

A new model is only considered the best if it is better than others and not simply better or equal

---

allennlp/common/util.py
allennlp/tests/common/test_util.py

allow sanitize to work on custom classes

---

allennlp/service/server_simple.py

Fixes https://github.com/allenai/allennlp/issues/1316

Remove default arguments from the simple server.

---

allennlp/commands/__init__.py

Add version to AllenNLP command.

---

allennlp/tests/training/trainer_test.py

Make test_trainer_respects_keep_serialized_model_every_num_seconds more patient

---

README.md
allennlp/version.py
tutorials/README.md
tutorials/getting_started/using_as_a_library_pt1.md
tutorials/getting_started/using_as_a_library_pt2.md

Revert "Release v0.5.1"

---

allennlp/common/file_utils.py

In get_from_cache(), allow redirections in HEAD requests

---

allennlp/training/trainer.py

Quick refactor to expose the functionality to find the latest checkpoint in the serialization directory in `Trainer`.

Split off function to find latest checkpoint in Trainer

---

allennlp/commands/evaluate.py

Continuation of #1425 , missed one

Make evaluation tqdm description ignore metrics starting with _ 

---

allennlp/models/crf_tagger.py

Fix call to vocab.token_from_index -> self.label_namespace

---

allennlp/data/dataset_readers/__init__.py
allennlp/data/dataset_readers/ontonotes_ner.py
allennlp/tests/data/dataset_readers/ontonotes_ner_test.py
doc/api/allennlp.data.dataset_readers.ontonotes_ner.rst
doc/api/allennlp.data.dataset_readers.rst

Dataset reader for fine grained NER on the Ontonotes 5.0 corpus. I kind of CBA to write a converter between BIO and BIOUL but if you think the distinction is important I can add it

fine grained ner reader

---

allennlp/data/dataset_readers/conll2003.py
allennlp/data/dataset_readers/dataset_utils/__init__.py
allennlp/data/dataset_readers/dataset_utils/span_utils.py
allennlp/data/dataset_readers/ontonotes_ner.py
allennlp/tests/data/dataset_readers/dataset_utils/span_utils_test.py

Make `iob1_to_bioul` handle BIO encodings and add BIOUL encoding as an option to the fine grained NER reader.

Bio to bioul

---

tutorials/getting_started/using_as_a_library_pt1.md

Fixes https://github.com/allenai/allennlp/issues/1507

Fix broken link in using_as_a_library_pt1.md

---

allennlp/commands/train.py

Fixes #1447
I knew I saw this somewhere...

Remove extra .params

---

allennlp/tests/training/trainer_test.py
allennlp/training/trainer.py

Before, we were only saving the best validation metric for the metric we were tracking, when in reality, it's very likely that you have a lot more metrics which you care about the values of at that epoch.

Preserve best metrics

---

allennlp/commands/elmo.py

Original comment here about tensor size was a bit confusing.

Minor change of a comment

---

tutorials/getting_started/using_as_a_library_pt1.md

Fix broken link in tutorial

---

tutorials/getting_started/using_as_a_library_pt2.md
tutorials/getting_started/using_pretrained_models.md

Fixes the unreachable links reported by `check-links` (#1522). Please consider merging this after `check-links` has been added to CI so as to make sure CI fails without it.

Fix the reported broken links.

---

allennlp/training/trainer.py

Not really sure how to test this, any suggestions?

Expose iterator shuffling through Trainer config

---

allennlp/common/util.py
allennlp/tests/common/test_util.py

fix for the first bug in  #1584

make --include-package include all submodules

---

allennlp/training/optimizers.py

Logs the number of parameters used when building optimizers `from_params`

Log number of parameters in optimizers

---

allennlp/data/dataset_readers/universal_dependencies.py
requirements.txt
setup.py

Changing conllu broke something I don't understand, so i'm pinning it for now + the release.

revert conllu changes

---

training_config/bimpm.json

@matt-gardner, sorry that I missed the changes to the json config file of bimpm model when I change num_perspective to num_perspectives. This is the pack to fix it.

Fix bimpm config file.

---

allennlp/commands/train.py

Add missing --recover flag to train docs

---

allennlp/data/dataset_readers/ccgbank.py
allennlp/data/dataset_readers/conll2003.py
allennlp/tests/data/dataset_readers/ccgbank_test.py

The goal of this PR is to enable a single sequence labeling model to work with all sequence labeling dataset readers.
Changes:
@matt-peters these CCGBank changes might affect you? What do you think about them?

Standardize tagging datasets

---

allennlp/tests/training/learning_rate_schedulers_test.py
allennlp/training/learning_rate_schedulers.py

After taking a closer look at [TensorFlow's API for cosine annealing](https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/python/training/learning_rate_decay.py#L514), I realized it would make sense to name a few things differently. I also added another parameter, `eta_mul`, which determines the initial learning rate at the beginning of the i-th cycle. The default behavior is still the same.

Improve API for cosine annealing scheduler

---

tutorials/getting_started/using_as_a_library_pt1.md

This should help this tutorial stay in sync with allennlp-as-a-library-example.

Removing contents of requirements.txt file

---

allennlp/data/iterators/bucket_iterator.py

From discussion here: #1578. Let me know if I should remove the code instead of commenting it.

Remove bucket iterator shuffle warning.

---

allennlp/nn/util.py
allennlp/tests/nn/util_test.py

Fixed bug in _get_combination_and_multiply for batch size equal to 1

---

tutorials/how_to/elmo.md

In response to https://github.com/allenai/allennlp/issues/1735.

Add an example of how to read ELMo embeddings with h5py

---

allennlp/common/testing/model_test_case.py
allennlp/models/encoder_decoders/simple_seq2seq.py
allennlp/tests/models/encoder_decoders/simple_seq2seq_test.py

- Addresses:
- https://github.com/allenai/allennlp/issues/1713, "possible masking bug in simple_seq2seq"
- https://github.com/allenai/allennlp/issues/1134, "Simple Seq2Seq Computes Incorrect Dev Log Loss"

Fixes for seq2seq model

---

tutorials/how_to/elmo.md

In response to https://github.com/allenai/allennlp/issues/1735

Add an example of using ELMo interactively

---

allennlp/semparse/worlds/atis_world.py

Fixes #1843, so that import from allennlp does not require a network connection

Fix allennlp import requiring network connection

---

allennlp/common/checks.py
allennlp/predictors/wikitables_parser.py
allennlp/semparse/executors/wikitables_sempre_executor.py
scripts/verify.py

Raise RuntimeError if java is not available

---

MODELS.md
README.md

Partially addresses: https://github.com/allenai/allennlp/pull/1802

Create a markdown file that enumerates available models

---

allennlp/data/vocabulary.py
allennlp/models/model.py

This is the bug-fix to [[Bug] @classmethod in Vocabulary is not a real method of class, and it fails to custom our own Vocabulary subclasses.](https://github.com/allenai/allennlp/issues/1867).
But may we consider more test cases?

WrRan patch: to custom vocabulary

---

allennlp/semparse/contexts/text2sql_table_context.py
allennlp/semparse/worlds/text2sql_world.py
allennlp/tests/data/dataset_readers/semantic_parsing/grammar_based_text2sql_test.py
allennlp/tests/semparse/worlds/text2sql_world_test.py

- Modifies the grammar to remove some stuff which is not needed if we don't have table aliases.
- Wires it into the World

Var free grammar

---

doc/api/allennlp.models.semantic_parsing.quarel.rst

Fix QuaRel reference

---

allennlp/common/from_params.py
allennlp/tests/common/from_params_test.py

Fixes #1862
A couple of limitations I see/comments:
1. What should happen if the length of the tuple specified by the typing is different than the length of the tuple passed in the params?
2. The code is not recursive, so `List[List[...]]` will not work
3. The code does not handle primitive types, so `Tuple[A, int]` will not work
4. I can't think of a good use case for a set, but I implemented it anyway
Happy to hear comments

Adding support for list, tuple, and set in from_params

---

MODELS.md

The BiMPM download url in MODEL.md was wrong.

fix BiMPM url in MODEL.md

---

allennlp/commands/train.py
allennlp/tests/commands/train_test.py

Fixes https://github.com/allenai/allennlp/issues/1575

Add a --force command to train

---

.pylintrc

This disables the report, which I've never used and is quite annoying to scroll back over.  That said, others may use this and there's no sense merging it if anyone has an objection.  Sample output:
```
Verifying with ['pylint']
Linter (pylint):
Using config file /Users/michael/hack/allenai/allennlp/.pylintrc
************* Module allennlp.tests.commands.train_test
C: 21, 0: Exactly one space required after comma
params = lambda: Params({"model": {"type": "simple_tagger","text_field_embedder": {"tokens": {
^ (bad-whitespace)
C: 22, 0: Wrong hanging indentation (remove 24 spaces).
"type": "embedding",
|                       ^ (bad-continuation)
C: 23, 0: Wrong hanging indentation (remove 24 spaces).
"embedding_dim": 5
|                       ^ (bad-continuation)
C: 24, 0: Wrong hanging …
```

Remove the report from pylint.

---

allennlp/modules/token_embedders/elmo_token_embedder.py

Sorry, continuation of #1955 . Was able to run a model with this setting, so pretty sure I got it right this time around...

Add scalar_mix_parameters to ElmoTokenEmbedder.from_params

---

allennlp/semparse/worlds/wikitables_variable_free_world.py

@matt-gardner I could have made this fix in the new repo, but that would mean copying a lot of code (including the models) to the new repo. Moreover, this is a bug fix, and a minor one.

Minor bug fix in get_agenda

---

allennlp/modules/token_embedders/elmo_token_embedder.py
allennlp/nn/util.py
allennlp/tests/nn/util_test.py

combine_tensors_and_multiply_with_batch_size_one_and_seq_len_one

---

allennlp/data/vocabulary.py

Fixes https://github.com/allenai/allennlp/issues/1826

Ignore hidden vocabulary files

---

allennlp/common/checks.py
allennlp/training/trainer.py

Catch nan loss in training loop

---

allennlp/common/file_utils.py
allennlp/data/tokenizers/word_filter.py
allennlp/tests/data/tokenizers/word_filter_test.py
allennlp/tests/data/tokenizers/word_tokenizer_test.py

This pull request adds support for: 
- Adding stopwords from a file.
- Using a regex-based word filter.

Dynamic stopwords

---

allennlp/data/tokenizers/__init__.py
allennlp/data/tokenizers/sentence_splitter.py
allennlp/tests/data/tokenizers/sentence_splitter_test.py
doc/api/allennlp.data.tokenizers.rst

This pull request adds sentence segmentation to AllenNLP. It's just a wrapper on Spacy's rule-based and statistical sentence boundary detection.

Sentence splitter

---

allennlp/training/metrics/evalb_bracketing_scorer.py

Fixes https://github.com/allenai/allennlp/issues/2017

Specify path at which to compile evalb.

---

allennlp/data/iterators/data_iterator.py
allennlp/tests/data/iterators/basic_iterator_test.py

fix epoch tracking

---

allennlp/data/token_indexers/wordpiece_indexer.py
allennlp/tests/data/token_indexers/bert_indexer_test.py
allennlp/tests/fixtures/bert/config.json
allennlp/tests/fixtures/bert/vocab.txt
allennlp/tests/modules/token_embedders/bert_embedder_test.py

fixes #2141 
as mentioned in the issue, this change gets an extra point of dev F1 on the NER model I trained with BERT embeddings + character embeddings

add [CLS] and [SEP] tags to bert indexer

---

README.md
allennlp/commands/elmo.py
doc/api/allennlp.commands.rst

Fixes https://github.com/allenai/allennlp/issues/2137

Update the elmo command help text.

---

tutorials/how_to/visualizing_model_internals.md

Fixes the broken links and closes #2088

Fixes broken link and rephrasing visualizing_model_internals.md

---

allennlp/commands/evaluate.py
allennlp/data/dataset_readers/simple_language_modeling.py
allennlp/tests/commands/evaluate_test.py

- Display loss when running evaluate.
- Fixes https://github.com/allenai/allennlp/issues/1241
- Log when sentences are dropped due to exceeding the maximum length.

Minor fixes to help evaluate ELMo port.

---

allennlp/data/tokenizers/word_splitter.py
allennlp/predictors/biaffine_dependency_parser.py
allennlp/predictors/constituency_parser.py
allennlp/predictors/coref.py
allennlp/predictors/dialog_qa.py
allennlp/predictors/sentence_tagger.py

add default argument for SpacyWordSplitter

---

allennlp/training/trainer.py

Fix loaded model not taken to cuda device

---

allennlp/nn/util.py

Fixes https://github.com/allenai/allennlp/issues/1689

Remove last_dim_softmax as it's deprecated and scheduled for removal.

---

allennlp/data/token_indexers/wordpiece_indexer.py
allennlp/tests/data/token_indexers/bert_indexer_test.py

fix lowercase-ization in bert indexer

---

allennlp/tests/training/metrics/boolean_accuracy_test.py
allennlp/training/metrics/boolean_accuracy.py

fix completely masked case in BooleanAccuracy

---

allennlp/commands/train.py
allennlp/tests/commands/train_test.py

This PR addresses #2240. Suggestions welcome.

Check for existing vocabulary before creating a new one (#2240)

---

allennlp/data/token_indexers/openai_transformer_byte_pair_indexer.py

Here's Huggingface's original code: https://github.com/huggingface/pytorch-openai-transformer-lm/blob/master/text_utils.py#L30

Add raw prefix to avoid warnings from regex

---

tutorials/README.md

Added links for Tutorials  for the following:
Creating a Configuration File.
Using a Debugger.
Training and Using a Transformer ELMo.
Fixes #2284

Added links for some tutorials and organized the How-to alphabetically.

---

allennlp/semparse/contexts/text2sql_table_context.py

I had trouble reproducing the same pytest output as @WrRan has on his PR locally, but here are a few more escape character fixes.

Fix backslash exceptions.

---

allennlp/semparse/domain_languages/nlvr_language.py

Sorry, didn't catch this the first time reviewing.

Fix f-string in NLVR Language

---

allennlp/tests/training/trainer_test.py
allennlp/training/trainer.py

I tested the one-gpu test. I don't have a multi-gpu machine.

move model to cuda in tests, add comment

---

allennlp/commands/evaluate.py
allennlp/commands/fine_tune.py
allennlp/models/model.py
allennlp/tests/commands/train_test.py
allennlp/tests/models/model_test.py
allennlp/training/trainer.py

@matt-gardner, this is follow-up on discussion in #2501.

Remove extended_vocab argument from extend_embedder_vocab API.

---

requirements.txt
setup.py

includes OpenAI GPT-2. don't have an immediate use case for it, but I suspect if it's in the library people will figure out a way to use it.

upgrade huggingface pretrained bert

---

DEPRECATION.md

- Examples of when backward compatibility is likely to be an issue.
- Suggestions for ensuring compatibility.
- Mechanics for deprecating.

Propose a deprecation policy.

---

.pylintrc
allennlp/tests/tools/drop_eval_test.py
allennlp/tools/drop_eval.py
doc/api/allennlp.tools.rst
doc/api/allennlp.tools.squad_eval.rst
doc/api/allennlp.tools.wikitables_evaluator.rst

This is me taking and cleaning up the evaluation script that @dDua wrote, from the private DROP repo, along with tests.  It has already had two pairs of eyes on it.

Add official DROP evaluation script

---

allennlp/models/encoder_decoders/copynet_seq2seq.py

This just adds an `InitializerApplicator` parameter to the CopyNet model.

Add initializer to copynet

---

allennlp/modules/augmented_lstm.py

fix the bug of tensor.data in argumented_lstm.py
Fixes #2530

fix a bug in augmented_lstm.py

---

allennlp/tests/tools/drop_eval_test.py
allennlp/tools/drop_eval.py

Fixed bugs:
-- when predictions are none
-- removed unnecessary dictionary usage in "answer"
Added test cases for end to end F1 and EM measure with json loading

bug fixes in drop evaluation and more test cases

---

allennlp/commands/test_install.py

Adds possiblity to limit pytest tests in test-install command.

add option "-k" to limit tests in test-install command

---

allennlp/tests/common/params_test.py
training_config/dependency_parser.json

add dependency parser config

---

allennlp/semparse/contexts/quarel_utils.py
allennlp/tests/semparse/contexts/quarel_utils_test.py

This was due to some refactoring that I did a while ago, and it is the cause of the broken QuaRel demo.  I didn't see an easy way to test for this kind of breakage in the demo repository, unfortunately, but I added a test for the breakage here.
I'm not going to say that this fixes the issue in the demo repo (https://github.com/allenai/allennlp-demo/issues/182), because the demo repo needs to be updated to use this commit after this gets merged, and then it will be fixed.

Fix quarel explanations

---

allennlp/data/dataset_readers/text_classification_json.py
allennlp/tests/data/dataset_readers/text_classification_json_test.py
allennlp/tests/fixtures/data/text_classification_json/integer_labels.jsonl

TextCat Reader skip_label_indexing Fix

---

tutorials/tagger/config_allennlp.py

We really should have some CI check on these tutorials, I think.  But that's for another day.

Add missing paren

---

allennlp/modules/seq2seq_encoders/__init__.py
allennlp/modules/seq2seq_encoders/bidirectional_language_model_transformer.py

- Fixes https://github.com/allenai/allennlp/issues/2462.

Move register to typical location.

---

allennlp/commands/find_learning_rate.py
allennlp/commands/fine_tune.py
allennlp/common/file_utils.py
allennlp/common/params.py
allennlp/data/dataset_readers/coreference_resolution/winobias.py
allennlp/data/dataset_readers/penn_tree_bank.py
allennlp/data/dataset_readers/reading_comprehension/util.py
allennlp/data/dataset_readers/stanford_sentiment_tree_bank.py
allennlp/data/dataset_readers/text_classification_json.py
allennlp/data/dataset_readers/universal_dependencies.py
allennlp/data/token_indexers/wordpiece_indexer.py
allennlp/models/biaffine_dependency_parser.py
allennlp/models/constituency_parser.py
allennlp/models/coreference_resolution/coref.py
allennlp/models/graph_parser.py
allennlp/models/language_model.py
allennlp/models/reading_comprehension/bidaf_ensemble.py
allennlp/models/semantic_parsing/quarel/quarel_semantic_parser.py
allennlp/models/semantic_parsing/text2sql_parser.py
allennlp/models/semantic_parsing/wikitables/wikitables_erm_semantic_parser.py
allennlp/modules/openai_transformer.py
allennlp/modules/seq2seq_encoders/bidirectional_language_model_transformer.py
allennlp/nn/util.py
allennlp/tests/data/vocabulary_test.py

This PR starts to tackle #1410
Tasks:
There are some docs changes which I'm not 100% sure about it, so pay special attention when reviewing them. Also, I've made two `metadata` arguments required cause I saw they were in fact.

Fix docstrings after inspection

---

allennlp/modules/token_embedders/embedding.py

After https://github.com/allenai/allennlp/issues/2694#issuecomment-480471577.

Add missing docstring for Embedding.pretrained_file

---

allennlp/modules/seq2seq_encoders/qanet_encoder.py
allennlp/tests/models/reading_comprehension/qanet_test.py

Fixes #2605, allows `QaNetEncoder` for multiple GPUs.

QaNetEncoder Multi-GPU

---

allennlp/predictors/predictor.py
allennlp/pretrained.py

Added NAQANet to pretrained.py and DEFAULT_PREDICTORS

---

allennlp/data/vocabulary.py

Fixes #2453, sorry it took me so long to get to this!

Document interaction between UNK token and max_vocab_size

---

allennlp/training/metrics/evalb_bracketing_scorer.py

Following up on https://github.com/allenai/allennlp/pull/2743#discussion_r278370732 , applying the same fix to the EVALB metric.

Directly capture output in EVALB metric

---

training_config/bidaf.jsonnet

Remove misleading dropout from bidaf.jsonnet

---

tutorials/how_to/training_transformer_elmo.md

- Fixes https://github.com/allenai/allennlp/issues/2812

Link pretrained model in tutorial.

---

allennlp/commands/train.py

Following https://github.com/allenai/allennlp/pull/2830#issuecomment-491868200
@joelgrus this patch will make test evaluation work until #2817 is merged.

Fix test evaluation after training in the general case

---

allennlp/tests/tools/drop_eval_test.py
allennlp/tools/drop_eval.py

Fixes https://github.com/allenai/allennlp/issues/2852

Use optimal matching for the drop eval and add appropriate tests.

---

allennlp/pretrained.py

Updated the model with the new one : fine-grained-ner-model-elmo-2018.08.31.tar.gz ->  fine-grained-ner-model-elmo-2018.12.21.tar.gz

updated fine-grained-ner-model-elmo URL

---

MODELS.md

Updated new and updated links for NER models

Updated links for pretrained NER models

---

allennlp/data/token_indexers/wordpiece_indexer.py
allennlp/tests/data/token_indexers/bert_indexer_test.py

fixes bad mistake in yesterday's PR

truncate type ids

---

scripts/ai2-internal/run_with_beaker.py

Fix bug introduced in #2903, where docker image was not defined.

Fix bug in run_with_beaker.py script

---

training_config/atis_train.jsonnet
training_config/wikitables_parser.jsonnet

Fixes https://github.com/allenai/allennlp/issues/2845

Link to Wikitables and ATIS data.

---

allennlp/data/vocabulary.py
allennlp/tests/data/vocabulary_test.py

Main motivation here is to simplify tutorial code, but could also be useful more generally.

Allowing for bulk adding of tokens to vocab

---

allennlp/predictors/predictor.py

- Fixes https://github.com/allenai/allennlp/issues/1573

Add cuda_device to Predictor.from_path

---

allennlp/models/encoder_decoders/simple_seq2seq.py

Should be "tokens" rather than "target tokens"

correct the wrong parameter note(target_namespace)

---

allennlp/training/learning_rate_schedulers/cosine.py

- Fixes https://github.com/allenai/allennlp/issues/2388

Clarify docs for CosineWithRestarts

---

allennlp/data/dataset_readers/copynet_seq2seq.py

Removed target_token_indexers documentation

---

allennlp/commands/train.py

do not evaluate after training if non-default trainer

---

allennlp/training/callbacks/log_to_tensorboard.py

- Fixes https://github.com/allenai/allennlp/issues/2998

Make per-batch logging quieter.

---

allennlp/data/tokenizers/sentence_splitter.py

Update some legacy documents that look like copied from `WordSplitter`.

Update documents to sentence_splitter.py

---

scripts/wikitables/generate_data_from_erm_model.py

Minor changes to the script that decodes logical forms from a trained ERM model to make it work with the latest code.

Fixes to ERM decoding script

---

allennlp/data/token_indexers/wordpiece_indexer.py

warn about truncation only once

---

README.md

allenNLP broken link

---

allennlp/tests/training/callback_trainer_test.py
allennlp/training/callbacks/update_moving_average.py

fix UpdateMovingAverage.from_params

---

allennlp/tests/data/dataset_readers/text_classification_json_test.py
requirements.txt
setup.py

pin pytorch away from 1.2 until we fix the tests

---

allennlp/commands/find_learning_rate.py

Move matplotlib import into function

---

allennlp/training/tensorboard_writer.py

Fixing NaN warning with single element tensors

---

allennlp/data/fields/span_field.py
allennlp/interpret/attackers/attacker.py
allennlp/interpret/attackers/hotflip.py
allennlp/interpret/attackers/input_reduction.py
allennlp/interpret/attackers/utils.py
allennlp/interpret/saliency_interpreters/integrated_gradient.py
allennlp/interpret/saliency_interpreters/simple_gradient.py
allennlp/interpret/saliency_interpreters/smooth_gradient.py
allennlp/tests/data/fields/span_field_test.py
allennlp/tests/interpret/hotflip_test.py
allennlp/tests/interpret/simple_gradient_test.py

Depends on #3202 and #3201.  Implements targeted hotflip attacks, beam search for input reduction, and other minor cleanup.

Targeted hotflip attacks and beam search for input reduction

---

Dockerfile
Dockerfile.pip

Reverts allenai/allennlp#3177
I need to change `python` to `python3` in the quoref test and also change the Dockerfile used for CI.

Revert "Use an NVIDIA base image."

---

allennlp/common/params.py
allennlp/modules/attention/__init__.py
allennlp/modules/attention/additive_attention.py
allennlp/tests/modules/attention/additive_attention_test.py
doc/api/allennlp.modules.attention.rst

Added Additive Attention module (Also known as Concat attention) from  https://arxiv.org/pdf/1409.0473.pdf

Add additive attention & unittest

---

scripts/ai2-internal/run_with_beaker.py

- Compile Jsonnet config locally so that `import` works.
- Add `--include-package` option so we can use the script with other repos.
- Add `--overrides`.

Assorted fixes for run_with_beaker.py

---

.github/ISSUE_TEMPLATE/question.md

Very open to suggestions on the wording ;-)

Advertise Discourse on the issue template

---

allennlp/data/token_indexers/wordpiece_indexer.py
allennlp/tests/data/token_indexers/bert_indexer_test.py

wordpiece indexer should not crash on empty sequences

---

allennlp/interpret/attackers/input_reduction.py

This apparently doesn't work; should have tested it more thoroughly before merging...

Revert batching for input reduction

---

allennlp/common/registrable.py

Re-fix regression previously fixed in #2004 but re-introduced in #3190

Change log level to clean up allennlp command

---

allennlp/data/dataset_readers/stanford_sentiment_tree_bank.py
allennlp/interpret/saliency_interpreters/simple_gradient.py
allennlp/models/model.py
allennlp/predictors/predictor.py

This reverts commit 135db83a151179715e32e9093cde0ac9bd17ec20.

Reverting an unintentional commit that broke our build

---

allennlp/data/token_indexers/pretrained_transformer_indexer.py

Hi! I may be wrong but I think this was a typo.

Fix typo in docstring

---

allennlp/models/encoder_decoders/copynet_seq2seq.py
requirements.txt
setup.py

Fix bugs due to breaking change in pytorch.
Fixes https://github.com/allenai/allennlp/issues/3343

Upgrade to pytorch 1.3

---

allennlp/commands/train.py
allennlp/tests/commands/train_test.py

Fix random seeds not getting copied to the config created in serialization folder.
Fixes https://github.com/allenai/allennlp/issues/3211

Random seeds do not get copied to the model archive 

---

scripts/ai2_internal/resume_daemon.py
scripts/ai2_internal/run_with_beaker.py

- Simply pass, e.g., `--max-resumes=10`.
- Modifies `resume_daemon.py` to automatically install itself.

Make run_with_beaker.py automatically resume

---

requirements.txt
setup.py

- For https://github.com/allenai/allennlp/issues/3367
- I've verified that this fixes the aforementioned bug using a fresh conda environment in Mac OS 10.13.6.

Pin away from torch 1.3.0.

---

setup.py

ugh missed this in #3402 , sorry for being sloppy about it.

Pin overrides to 2.0 in setup.py

---

pyproject.toml

Hello, first time contributor here!
This is my suggestion to fix the infinite loop you're having and reported @ [poetry](https://github.com/sdispater/poetry/issues/771). I just had the same issue and that was the problem.
Hope it works for you as well!

Add a package name in Pyproject

---

allennlp/data/token_indexers/pretrained_transformer_indexer.py
allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
allennlp/modules/language_model_heads/bert.py
allennlp/modules/language_model_heads/gpt2.py
allennlp/modules/token_embedders/pretrained_transformer_embedder.py
allennlp/nn/util.py
allennlp/tests/data/token_indexers/pretrained_transformer_indexer_test.py
allennlp/tests/modules/token_embedders/pretrained_transformer_embedder_test.py
requirements.txt
setup.py

Fixes https://github.com/allenai/allennlp/issues/3448.
Breaking changes that were introduced in the new "transofrmers" release should not affect existing allennlp codebase.

pytorch_transformers -> transformers

---

allennlp/common/params.py

A user was confused by this message (see https://discourse.allennlp.org/t/jsonnet-configuration-file-cannot-be-interpreted/127/2) so I'm improving the wording.

Clarify wording on the Jsonnet loading error.

---

allennlp/tests/data/tokenizers/sentence_splitter_test.py
allennlp/tests/models/sniff_test.py
allennlp/tests/predictors/biaffine_dependency_parser_test.py

#3432 broke our build somehow, even though it passed CI 🤔 . I fixed the spacy tests by deleting the test that failed, because we shouldn't have tests for statistical models which we don't directly control.

Fix and simplify spacy tests

---

allennlp/training/checkpointer.py

Fix OOM while loading best model state

---

allennlp/commands/train.py
allennlp/tests/commands/train_test.py

Create model archive for multi-GPU training

---

allennlp/commands/train.py

Allow multi-node distributed training with one GPU per node

---

allennlp/training/trainer.py

Set `find_unused_parameters` to True for torch's `DistributedDataParallel`

---

allennlp/data/dataset_readers/ccgbank.py
allennlp/data/dataset_readers/semantic_dependency_parsing.py
allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
allennlp/models/coreference_resolution/coref.py
allennlp/modules/bimpm_matching.py
allennlp/modules/encoder_base.py
allennlp/modules/sampled_softmax_loss.py
allennlp/tests/common/test_util.py
allennlp/tests/training/callback_trainer_test.py
allennlp/tests/training/trainer_test.py
dev-requirements.txt
scripts/examine_sql_coverage.py

These tools shouldn't change their behavior as they have rather strict definitions.  Ideally we would be able to use the latest bugfixes.

Unpin black and flake8 for development

---

allennlp/common/registrable.py

I missed this in https://github.com/allenai/allennlp/pull/3588.

Fix bug in a docstring.

---

tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt2.md

[#2213](https://github.com/allenai/allennlp/pull/2213) changed tutorial predictor code but only partially changed the accompanying description. This PR fixes this issue by updating the description.

Fix tutorial code/description inconsistency.

---

allennlp/common/util.py
allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
allennlp/tools/EVALB/evalb.dSYM/Contents/Info.plist

I thought I needed more changes, but right now this is all.

Factor out a single function I need in allennlp_reading_comprehension

---

allennlp/tests/training/metrics/auc_test.py

Fixes #3608. Fixing the test by handling the special case, where there is no positive gold label.

Bug fix for flaky test in AucTest, resolving issue #3608

---

allennlp/modules/span_extractors/endpoint_span_extractor.py

Fixes #3416. Check for dimensions in EndpointSpanExtractor when use_exclusive_start_indices = False.

fixed the fix-endpoint_span_extractor issue

---

allennlp/commands/find_learning_rate.py
dev-requirements.txt
setup.py

make matplotlib optional

---

allennlp/modules/span_extractors/self_attentive_span_extractor.py
allennlp/nn/util.py
allennlp/tests/nn/util_test.py

I want to re-use this logic in a different place.

Factor out batched_span_select code

---

allennlp/training/trainer.py

Fixes #3663 
@scarecrow1123 would love to get your point of view on this, I think this is correct? We want the metrics returned at the end of each epoch to only be computed once we are sure that all the workers have finished their epoch.

change where we block in the distributed case

---

scripts/build_docs.py

recursively sort docs

---

allennlp/data/fields/multilabel_field.py
allennlp/tests/data/fields/multilabel_field_test.py

Fix the bug as in [https://github.com/allenai/allennlp/issues/3721](https://github.com/allenai/allennlp/issues/3721)

fix MultiLabelField

---

allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
allennlp/tests/data/tokenizers/pretrained_transformer_tokenizer_test.py

`intra_word_tokenize` and `_determine_num_special_tokens_added`

Support sequence pair for some functions in PretrainedTransformerTokenizer

---

allennlp/nn/util.py
allennlp/tests/nn/util_test.py

Helps with fine-tuning on larger output spaces. Addresses #3761

Add util to extend layer sizes

---

allennlp/predictors/coref.py

Fixes contiguous whitespaces causing coref model to produce bad results

---

allennlp/modules/seq2vec_encoders/__init__.py
training_config/stanford_sentiment_treebank_roberta.jsonnet

https://storage.cloud.google.com/allennlp-public-models/sst-roberta-large-2020.02.17.tar.gz

Add RoBERTa SST model, 95.64 dev 95.11 test

---

setup.py

Pin transformers < 2.5.0

---

allennlp/models/basic_classifier.py
allennlp/models/biaffine_dependency_parser.py
allennlp/models/biattentive_classification_network.py
allennlp/models/bimpm.py
allennlp/models/constituency_parser.py
allennlp/models/coreference_resolution/coref.py
allennlp/models/crf_tagger.py
allennlp/models/encoder_decoders/composed_seq2seq.py
allennlp/models/encoder_decoders/copynet_seq2seq.py
allennlp/models/encoder_decoders/simple_seq2seq.py
allennlp/models/graph_parser.py
allennlp/models/masked_language_model.py
allennlp/models/model.py
allennlp/models/next_token_lm.py
allennlp/models/semantic_role_labeler.py
allennlp/models/simple_tagger.py
allennlp/models/srl_bert.py
allennlp/predictors/predictor.py
allennlp/tests/models/basic_classifier_test.py
allennlp/tests/models/bert_srl_test.py
allennlp/tests/models/biaffine_dependency_parser_test.py
allennlp/tests/models/bimpm_test.py
allennlp/tests/models/constituency_parser_test.py
allennlp/tests/models/coreference_resolution/coref_test.py
allennlp/tests/models/crf_tagger_test.py
allennlp/tests/models/encoder_decoders/composed_seq2seq_test.py
allennlp/tests/models/encoder_decoders/simple_seq2seq_test.py
allennlp/tests/models/graph_parser_test.py
allennlp/tests/models/semantic_role_labeler_test.py
allennlp/tests/models/simple_tagger_test.py

Renaming Model.decode to Model.make_output_human_readable

---

allennlp/common/params.py
allennlp/common/util.py
allennlp/data/dataset_readers/conll2000.py
allennlp/data/dataset_readers/conll2003.py
allennlp/data/dataset_readers/coreference_resolution/util.py
allennlp/data/dataset_readers/coreference_resolution/winobias.py
allennlp/data/dataset_readers/dataset_utils/ontonotes.py
allennlp/data/dataset_readers/quora_paraphrase.py
allennlp/data/dataset_readers/semantic_dependency_parsing.py
allennlp/data/dataset_readers/sequence_tagging.py
allennlp/data/fields/field.py
allennlp/predictors/coref.py
allennlp/predictors/open_information_extraction.py
allennlp/predictors/semantic_role_labeler.py

I browsed through the docs to find glaring issues and attempted to address them.

Various documentation fixes

---

allennlp/commands/train.py
allennlp/training/util.py

Fix for --recover with distributed training.

---

allennlp/tests/modules/attention/legacy_attention_test.py
allennlp/tests/modules/conditional_random_field_test.py
allennlp/tests/modules/encoder_base_test.py
allennlp/tests/modules/seq2seq_encoders/compose_encoder_test.py
allennlp/tests/modules/seq2seq_encoders/feedforward_encoder_test.py
allennlp/tests/modules/seq2seq_encoders/pass_through_encoder_test.py
allennlp/tests/modules/span_extractors/bidirectional_endpoint_span_extractor_test.py
allennlp/tests/modules/span_extractors/endpoint_span_extractor_test.py
allennlp/tests/modules/span_extractors/self_attentive_span_extractor_test.py
allennlp/tests/nn/util_test.py
allennlp/tests/training/metrics/auc_test.py
allennlp/tests/training/metrics/categorical_accuracy_test.py
allennlp/tests/training/metrics/entropy_test.py
allennlp/tests/training/metrics/f1_measure_test.py
allennlp/tests/training/metrics/fbeta_measure_test.py

The former is incompatible with CUDA as pointed out by @bryant1410 in #3890 .

Change torch.BoolTensor(...) to torch.tensor(...)

---

.github/workflows/nightly.yml

fix install order, only run publish on allenai/allennlp

---

training_config/basic_stanford_sentiment_treebank.jsonnet

Remove non-existent `batch_first` usage

---

allennlp/commands/find_learning_rate.py
allennlp/tests/models/simple_tagger_test.py
allennlp/tests/training/trainer_test.py
allennlp/training/__init__.py
allennlp/training/trainer.py

Fixes #3913 and fixes #3218.  This is NOT a fix for #3785, which I thought might be covered in the work for #3913, but it turns out was unrelated.

Add batch and epoch callbacks to the trainer

---

allennlp/data/__init__.py

I don't know how this happened, but not having `Batch` exported anymore broke the models repo.

Export Batch at the appropriate level

---

allennlp/data/token_indexers/pretrained_transformer_indexer.py

Albert uses a different way of storing the vocab, so we need a different way of getting it out and filling our own `Vocab` object.

Find the vocab even in Albert

---

allennlp/data/token_indexers/pretrained_transformer_indexer.py

Should fix https://github.com/allenai/allennlp/issues/3456

Fetch transformers vocabs automatically

---

setup.py

such as`chmod 600 ./pypirc` -> `~/.pypirc`

Fix some typos in setup.py

---

allennlp/tests/commands/train_test.py
allennlp/training/trainer.py

It's a one-line-change, but the tests are huge ...

Correctly computes the number of training steps

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
Makefile

We were missing the flag `--upgrade-strategy eager` in the `pip install` command.

Ensure all deps are up-to-date in CI

---

.github/workflows/master.yml

This is what I originally intended

Fix cron schedule

---

.github/workflows/master.yml
RELEASE_PROCESS.md
allennlp/version.py
scripts/get_version.py

hard-code version

---

allennlp/tests/version_test.py

This will ensure that we are consistent with how we version future releases.

add test for version convention

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
Dockerfile.test
Makefile
allennlp/tests/commands/find_learning_rate_test.py
allennlp/tests/commands/train_test.py
allennlp/tests/modules/encoder_base_test.py
allennlp/tests/training/trainer_test.py
dev-requirements.txt
pytest.ini

Add self-hosted runner for GPU checks

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
Dockerfile
Dockerfile.test
Makefile

Does the following:
- ensures Docker images built and run on the self-hosted runner are given unique labels per job so those built by other jobs running in parellel won't collide
- upgrades Docker Hub images to Python 3.7 base

Improve Docker-based workflows

---

allennlp/data/vocabulary.py
allennlp/tests/data/vocabulary_test.py

improve error message for Vocab.get_token_index

---

allennlp/commands/evaluate.py

Fixes https://github.com/allenai/allennlp/issues/4198

Fix Bug in evaluate script

---

CHANGELOG.md
allennlp/commands/train.py

wait for non-master workers to finish reading vocab before master worker saves it

---

allennlp/training/trainer.py
tests/training/trainer_test.py

This is a follow-up from our discussion at https://github.com/allenai/allennlp/pull/4241.

Makes the EpochCallback work the same way as the BatchCallback

---

CHANGELOG.md
allennlp/common/util.py
allennlp/training/tensorboard_writer.py
allennlp/training/trainer.py
tests/training/trainer_test.py

report CPU memory usage for each worker

---

allennlp/training/tensorboard_writer.py

log metrics in alphabetical order

---

CHANGELOG.md
allennlp/modules/token_embedders/pretrained_transformer_embedder.py
allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
tests/modules/token_embedders/pretrained_transformer_embedder_test.py
tests/modules/token_embedders/pretrained_transformer_mismatched_embedder_test.py

Having this would have made resolving #4273 much easier.
Fixes #4147.

Allow using pretrained transformers without fine-tuning them

---

CHANGELOG.md
allennlp/common/plugins.py

add 'allennlp_server' to default plugins

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
Makefile
allennlp/training/util.py

I overlooked this in https://github.com/allenai/allennlp/pull/4350

ensure 'from_files' vocab doesn't load instances

---

README.md
mkdocs-skeleton.yml

Some things didn't render well in our API docs.

fix some formatting issues in README

---

README.md

We may need to rework this when we have many.

Add a section for external tutorials

---

CHANGELOG.md
allennlp/training/trainer.py
tests/commands/train_test.py

~~With this PR, when you set `cuda_device: -2` in the config, it automatically uses one GPU if there is one.~~
When you don't set `cuda_device` at all, it automatically chooses one GPU of there is one.

Adds the ability to automatically detect whether we have a GPU

---

allennlp/data/tokenizers/pretrained_transformer_tokenizer.py

Removes unnecessary imports and deep copies.

small fix to pretrained transformer tokenizer

---

README.md
dev-requirements.txt

fix README, pin mkdocs, update mkdocs-material

---

allennlp/data/fields/text_field.py

Fix type hint in text_field.py

---

CHANGELOG.md
setup.py

fix boto3 dependency for package manager

---

CHANGELOG.md
allennlp/modules/token_embedders/pretrained_transformer_embedder.py
allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
tests/modules/token_embedders/pretrained_transformer_embedder_test.py

add option to use scalar mix of all transformer layers

---

CHANGELOG.md
allennlp/training/metrics/fbeta_measure.py
tests/training/metrics/fbeta_measure_test.py

fixed bug that erronously increased last label's false positive count

---

allennlp/commands/train.py
allennlp/common/file_utils.py
allennlp/common/logging.py
allennlp/common/params.py
allennlp/common/testing/model_test_case.py
allennlp/models/archival.py
allennlp/models/model.py
allennlp/training/util.py

I don't know why, but on Matt's NLVR branch mypy suddenly decided that it cares about all these annotations, so I fixed them everywhere it complained.

Type annotations for paths

---

CHANGELOG.md
allennlp/common/testing/model_test_case.py
allennlp/data/token_indexers/pretrained_transformer_indexer.py

This is mainly about being able to test models that don't return a loss in eval mode.

More BART changes

---

allennlp/data/dataloader.py

small doc fix

---

CHANGELOG.md
allennlp/commands/evaluate.py
allennlp/commands/find_learning_rate.py
allennlp/commands/predict.py
allennlp/commands/train.py
allennlp/common/logging.py
allennlp/common/tqdm.py

Bring back file-friendly-logging flag

---

allennlp/data/dataset_readers/nlvr2_reader.py
allennlp/models/vilbert.py
test_fixtures/vilbert/experiment.json
test_fixtures/vilbert/experiment_from_huggingface.jsonnet
test_fixtures/vilbert/experiment_from_huggingface_model_name.json
tests/models/vilbert_test.py

Still a bunch of work left to do here:

Initializing a VilBERT model from a pre-trained transformer

---

CHANGELOG.md
allennlp/training/__init__.py
allennlp/training/trainer.py
tests/training/trainer_test.py

Added an EpochCallback in `trainer.py` to track the epoch as a member of the model class.

EpochCallBack for tracking epoch

---

CHANGELOG.md
allennlp/common/tqdm.py
allennlp/data/tokenizers/token.py
allennlp/predictors/text_classifier.py

The second half of this is https://github.com/allenai/allennlp-models/pull/110.
Apparently we broke the SST models recently, and this brings them back. The errors added up in such a way that everything worked, only the results were garbage, which is why the tests didn't find anything. Thanks to @alexisjihyeross for finding it!

Fix RoBERTa SST

---

CHANGELOG.md
allennlp/common/checks.py
allennlp/common/params.py
allennlp/training/util.py

Small type annotation fixes. 
PS: I had `isort` runnning automatically which reordered some imports in the files I modified, hope that's ok(didn't see anything in CONTRIBUTING.md about import order).
Closes #4535 .

Static type checking fixes

---

allennlp/training/metrics/boolean_accuracy.py
allennlp/training/metrics/categorical_accuracy.py

Fixes https://github.com/allenai/allennlp/issues/4564 for `BooleanAccuracy ` and `CategoricalAccuracy`.
@AkshitaB

Fix boolean & categorical accuracy in distributed mode

---

CHANGELOG.md
allennlp/commands/evaluate.py
allennlp/commands/find_learning_rate.py
allennlp/commands/predict.py
allennlp/commands/train.py

Give better usage info for overrides parameter

---

.github/workflows/master.yml
.github/workflows/pull_request.yml

There's been some improvements:
https://github.com/actions/cache#whats-new

upgrade actions to cache@v2

---

CHANGELOG.md
allennlp/common/from_params.py
tests/common/from_params_test.py

Improve handling of **kwargs in FromParams

---

CHANGELOG.md
allennlp/commands/evaluate.py
allennlp/training/util.py
tests/commands/evaluate_test.py

add flag for saving predictions to 'evaluate' command

---

CHANGELOG.md
scripts/py2md.py
scripts/tests/py2md/basic_example.py
scripts/tests/py2md/basic_example_expected_output.md

Just a small fix to our doc building script 🛠

fix multi-line links in docs

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
CHANGELOG.md
CONTRIBUTING.md
Dockerfile
Dockerfile.test
README.md
setup.py
tests/common/registrable_test.py

https://github.com/allenai/allennlp-models/pull/135 needs to merge before all tests will pass

official support for Python 3.8 🐍

---

CHANGELOG.md
allennlp/commands/train.py
allennlp/common/params.py
allennlp/models/archival.py
allennlp/predictors/predictor.py
tests/common/params_test.py

Allow overrides to be JSON string or dict

---

CHANGELOG.md
allennlp/commands/find_learning_rate.py
allennlp/common/testing/model_test_case.py
allennlp/predictors/predictor.py
allennlp/training/trainer.py

See https://youtu.be/9mS1fIYj1So?t=540
This is from the tweet you sent me @dirkgr

Small optimization when zero-ing gradients

---

CHANGELOG.md
allennlp/commands/__init__.py
allennlp/commands/cached_path.py
allennlp/commands/print_results.py
allennlp/commands/subcommand.py

Subcommands that don't require plugins will no longer cause plugins to be loaded or have an `--include-package` flag.

CLI improvements

---

.github/workflows/master.yml
.github/workflows/pull_request.yml

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

new way of setting env variables in GH Actions

---

allennlp/training/checkpointer.py

I don't know how mypy missed this one 🙄

fix typehint on checkpointer method

---

CHANGELOG.md
allennlp/modules/seq2vec_encoders/pytorch_seq2vec_wrapper.py

fix docstring for PyTorchSeq2VecWrapper

---

CHANGELOG.md
allennlp/training/trainer.py

Fixes #4653.
Replaces #4674 and #4676.

Be sure to close the TensorBoard writer

---

CHANGELOG.md
allennlp/commands/train.py
tests/commands/train_test.py

warn about batches_per_epoch with validation loader

---

CHANGELOG.md
allennlp/commands/train.py
allennlp/common/testing/model_test_case.py
allennlp/modules/token_embedders/token_embedder.py
allennlp/nn/util.py
allennlp/predictors/sentence_tagger.py

Fixes the remaining broken links.

a few small doc fixes

---

CHANGELOG.md
allennlp/modules/text_field_embedders/basic_text_field_embedder.py

allow TextFieldEmbedder to have EmptyEmbedder that may not be in input

---

CHANGELOG.md
allennlp/interpret/saliency_interpreters/integrated_gradient.py
allennlp/interpret/saliency_interpreters/simple_gradient.py
allennlp/interpret/saliency_interpreters/smooth_gradient.py

This will partially address https://github.com/allenai/allennlp-demo/issues/601.

clean up forward hooks from saliency interpreters on exceptions

---

dev-requirements.txt

Needed until https://github.com/getsentry/responses/issues/354 is resolved.

pin urllib3 in dev reqs for responses

---

CHANGELOG.md
allennlp/common/util.py
allennlp/data/data_loaders/multi_process_data_loader.py
allennlp/data/data_loaders/multitask_data_loader.py
allennlp/data/data_loaders/multitask_epoch_sampler.py
allennlp/data/data_loaders/multitask_scheduler.py
allennlp/data/dataset_readers/__init__.py
allennlp/data/dataset_readers/multitask.py
setup.py
tests/common/util_test.py
tests/data/data_loaders/multitask_data_loader_test.py
tests/data/data_loaders/multitask_scheduler_test.py

This is still very much in progress, and the way that I want to finish this implementation is very much dependent on some other major changes to the data pipeline.  I'm making a draft PR now, so that we have a place that's easy to see and talk about  a use case for those major data changes, to help with design choices when making those changes.

Multitask data loading and scheduling

---

CHANGELOG.md
allennlp/common/cached_transformers.py
allennlp/common/util.py
setup.py

Makes the transformer cache work with custom kwargs

---

CHANGELOG.md
allennlp/nn/beam_search.py
tests/nn/beam_search_test.py

ensure GumbelSampler sorts beams by true log prob

---

CHANGELOG.md
README.md
allennlp/common/plugins.py

Adds a table which lists both AI2 and third-party plugins 👇
---
@himkt let me know if you're okay with having your name in the README, or if you'd like me to use a different link. I'm just linking to your personal website right now.

improve plugin section in README

---

tests/training/metrics/auc_test.py

Pulling this out from https://github.com/allenai/allennlp/pull/4793.

fix AUC test

---

.github/workflows/ci.yml
CHANGELOG.md
docs/css/extra.css
scripts/py2md.py
scripts/tests/py2md/basic_example_expected_output.md

Added this link "[SOURCE]" that will take you to the module on GitHub.

add link to source code in docs

---

Makefile

Same fix as https://github.com/allenai/allennlp-demo/pull/659

Fix cache volume

---

CHANGELOG.md
allennlp/common/model_card.py
allennlp/common/task_card.py
tests/common/model_card_test.py
tests/common/task_card_test.py

Moving modelcard and taskcard abstractions to main repo

---

CHANGELOG.md
allennlp/commands/train.py
allennlp/common/testing/distributed_test.py
allennlp/data/token_indexers/elmo_indexer.py
allennlp/nn/util.py
allennlp/predictors/sentence_tagger.py
allennlp/training/trainer.py
tests/commands/train_test.py
tests/training/trainer_test.py

Rename 'master' to 'primary' in context of distributed training

---

allennlp/data/data_loaders/multiprocess_data_loader.py
allennlp/data/dataset_readers/__init__.py
allennlp/data/dataset_readers/babi.py
allennlp/data/dataset_readers/conll2003.py
allennlp/data/dataset_readers/dataset_reader.py
allennlp/data/dataset_readers/interleaving_dataset_reader.py
allennlp/data/dataset_readers/sharded_dataset_reader.py
tests/data/dataset_readers/interleaving_dataset_reader_test.py

Based on discussion @dirkgr and I had.

resolve _read type

---

CHANGELOG.md
allennlp/nn/util.py
allennlp/training/metrics/average.py

From discussion here: https://github.com/allenai/allennlp-models/pull/193#discussion_r559732791.
- Adds a helper function for doing distributed reductions across workers.
- I used the function in the `Average` metric to demonstrate how it can simplify things.

A helper for distributed reductions

---

README.md

Also removes the link to discourse

Add link to upgrade guide to README

---

CHANGELOG.md
allennlp/training/trainer.py

Background: https://github.com/allenai/allennlp/issues/4939
This PR makes `GradientDescentTrainer` create `serialization_dir` itself.
@epwalsh Please take a look.

Update `GradientDescentTrainer` to automatically create directory for `serialization_dir`

---

CHANGELOG.md
allennlp/commands/predict.py
allennlp/predictors/predictor.py
allennlp/version.py
tests/commands/predict_test.py

This request came in via email and seems quite reasonable.

Allows specifying extra arguments for predictors

---

CHANGELOG.md
allennlp/common/model_card.py
tests/common/model_card_test.py

- Added `ModelUsage` to `ModelCard` class.

Adding ModelUsage, rearranging fields

---

CHANGELOG.md
allennlp/training/metrics/fbeta_multi_label_measure.py

As pointed out in https://stackoverflow.com/questions/65984950/allennlp-2-0-cant-get-fbetamultilabelmeasure-to-run/66165479#66165479.

Inputs to the FBetaMultiLabel metric were copied and pasted wrong

---

.github/workflows/ci.yml
CHANGELOG.md
allennlp/data/tokenizers/sentence_splitter.py
allennlp/data/tokenizers/spacy_tokenizer.py
setup.py
tests/data/dataset_readers/text_classification_json_test.py

Fixes #4950 .
- Update to spaCy 3.0

Update spaCy to 3.0

---

CHANGELOG.md
allennlp/training/metrics/rouge.py

ensure ROUGE metric can be pickled

---

CHANGELOG.md
allennlp/common/model_card.py

This fixes a `ValueError` raised when trying to print out a ModelCard

fix __str__ method of ModelCardInfo

---

README.md

I might have gone a little too crazy with the emojis.

Add link to gallery and demo in README

---

CHANGELOG.md
allennlp/training/callbacks/wandb.py

Adds additional parameters to the W&B callback. See the `wandb.init` docs for reference: https://docs.wandb.ai/ref/python/init

additional W&B params

---

CHANGELOG.md
allennlp/commands/predict.py
allennlp/data/data_loaders/multitask_data_loader.py
allennlp/data/dataset_readers/multitask.py
allennlp/predictors/multitask.py

Fixes https://github.com/allenai/allennlp/issues/5098.
The tests for this are in https://github.com/allenai/allennlp-models/pull/248.

Predicting with a dataset reader on a multitask model

---

CHANGELOG.md
allennlp/data/dataset_readers/interleaving_dataset_reader.py
tests/data/dataset_readers/interleaving_dataset_reader_test.py

Fixes https://github.com/allenai/allennlp/discussions/4933#discussioncomment-606859.

fix bug with interleaving dataset reader

---

allennlp/models/basic_classifier.py

Update docstring for basic_classifier

---

CHANGELOG.md
allennlp/data/dataset_readers/sharded_dataset_reader.py
tests/data/dataset_readers/sharded_dataset_reader_test.py

fix bug with sharded dataset reader

---

.github/pull_request_template.md
CONTRIBUTING.md
codecov.yml

- Adds a section describing our docstring syntax to the `CONTRIBUTING` guide.
- Adds a checklist to our pull request template.

improve contributing guide / PR template

---

CHANGELOG.md
allennlp/modules/transformer/t5.py
allennlp/modules/transformer/transformer_module.py
scripts/py2md.py
tests/modules/transformer/t5_test.py

See the CHANGELOG for a summary.

Improve weight tying logic in transformer module

---

CHANGELOG.md
allennlp/fairness/bias_direction.py
tests/fairness/bias_direction_test.py

Fixes #5395 
- Added flag `center=false` to `torch.pca_lowrank` in `PairedPCABiasDirection` to avoid centring the difference vectors.
- Adjusted bias_direction_test.py to facilitate new (correct) paired PCA bias direction.

Fix PairedPCABiasDirection

---

tests/common/push_to_hub_test.py

HF now raises ValueError

---

setup.py

Potentially fixes https://github.com/allenai/allennlp/issues/5466

Enforce reading in utf-8 encoding

---

CHANGELOG.md
allennlp/modules/transformer/t5.py
tests/modules/transformer/t5_test.py

Resize T5 Vocab

---

.github/workflows/ci.yml
CHANGELOG.md
allennlp/training/metrics/fbeta_multi_label_measure.py
tests/training/metrics/fbeta_multi_label_measure_test.py

Dimensions in `FBetaMultiLabelMeasure`

---

CHANGELOG.md
allennlp/nn/util.py

Clone warns

---

CHANGELOG.md
allennlp/data/vocabulary.py

Clarify Vocabulary documentation, add -1 option for `min_pretrained_embeddings`

---

CHANGELOG.md
requirements.txt

@h-vetinari found we re-introduced some dependencies that we don't need.

Dependencies

---

allennlp/nn/util.py
scripts/py2md.py

Missing `f` prefix on f-strings fix

---

.github/dependabot.yml
tests/training/learning_rate_schedulers/cosine_test.py

Taking over from https://github.com/allenai/allennlp/pull/5633, because I can't push changes there.

Dependabot GitHub Actions
