allenai/allennlp

- allennlp/data/vocabulary.py
I remembered why I had to make this a subclass of `defaultdict` in the first place - you can't do the simple lambda function in `__init__` that I wanted to do, because that function can't depend on the key.  So I just improved the docstring instead.
> Improved docstring for `_NamespaceDependentDefaultDict`

- Dockerfile
- build_tools/travis/install.sh
- scripts/install_requirements.sh
This eliminates `conda install` from the installation script by eliminating the automated pytorch installation. 
(the setup instructions tell you to install it separately anyway: https://github.com/allenai/allennlp#setting-up-a-development-environment ) 
Since the instructions say conda is "the easiest way" (rather than "the only way") to get things setup, I'm hesitant to have the installation scripts assume it. (Also, there are people who can't/don't use conda for various reasons, I think we should accommodate them if it's not costly to do so.)
I then added those steps back to the Dockerfile and travis setup. let me know if there's anywhere else where pytorch needs to be installed programatically.
(I assume at some point we'll probably just want a base docker image that already has …
> remove conda / pytorch from install_requirements.sh

- allennlp/data/fields/text_field.py
- allennlp/data/token_indexers/__init__.py
- allennlp/data/token_indexers/single_id_token_indexer.py
- allennlp/data/token_indexers/token_characters_indexer.py
- allennlp/data/token_indexers/token_indexer.py
this gets rid of most of the `cast`s in the code and feels like a better design. a few things to note:
(1) as mentioned on slack, this doesn't play well with `overrides`, so I had to comment those out from these files. I left a TODO to re-enable them when we can. I've already submitted a PR to that library, but the maintainer doesn't seem that active on GitHub, so we'll see what happens.
(2) after this change, pylint complains about `no-self-use` all over the place. I can't really see why it wasn't complaining about those already, but I added overrides.
(3) I had to add a `type: ignore` to `TokenIndexer.from_params`. it appears to have something to do with the intersection of Generics, type erasure, and classmethods. I don't think digging into it is the best use of my time right now.
(4) …
> make TokenIndexer generic over token type

- allennlp/data/vocabulary.py
`Sequence` encompasses both `List` and `Tuple`, and while lists are bad default arguments, tuples aren't. IMO this results in clearer default args for `Vocabulary`, since one could reasonably interpret 
```
non_padded_namespaces = None
```
to mean that there aren't any non-padded namespaces
> change None sentinel to Tuple sentinel

- allennlp/data/data_iterator.py
- allennlp/data/iterators/adaptive_iterator.py
- allennlp/data/iterators/basic_iterator.py
- allennlp/data/iterators/bucket_iterator.py
- tests/data/iterators/adaptive_iterator_test.py
- tests/data/iterators/basic_iterator_test.py
- tests/data/iterators/bucket_iterator_test.py
pretty straightforward. two things I don't like about this
(1) the documentation is copied twice
(2) the default values for the parameters are specified twice (in both `__init__` and `from_params`). 
I considered two approaches to the second issue.
(2a) pull those out into shared constants (but nowhere else in the code does that)
(2b) give `Params.as_dict` two extra named parameters `required_fields` and `optional_fields`. If you pass those in, then it must be the case that 
```
required_fields \subset params.keys() \subset required_fields.union(optional_fields)
```
and then every `from_params` method could just just call
```
cls(**params.to_dict(required_fields=[...], optional_fields=[...]))
```
of course there's also always
(2c) do nothing
thoughts?
> add from_params method for DataIterator subclasses

- allennlp/run
This obviates the need to `export PYTHONPATH=.`.
> Add the root of the project to PYTHONPATH in run.py.

- allennlp/common/util.py
- allennlp/models/bidaf.py
- allennlp/modules/seq2vec_encoders/pytorch_seq2vec_wrapper.py
- allennlp/nn/util.py
- tests/nn/util_test.py
There was a TODO in BiDAF to replace masked values before doing a max.  This fixes that issue.
> Fix masked max in BiDAF

- allennlp/service/servable/models/bidaf.py
- tests/service/servables/servable_test.py
- tests/service/server_flask_test.py
- tests/service/server_sanic_test.py
at some point the `best_span` from bidaf became a tuple of `np.int64`, which the json serializer chokes on. so now I convert it to python types.
I also added tests to catch this sort of error.
> fix int64 serialization + add tests

- tests/service/server_sanic_test.py
Hiding the app construction inside of `setUp` makes it so that I can still run `py.test -k SomeOtherThing` and have those tests run, even if the app construction fails for whatever reason (as it was, I would get errors on test _collection_, which would make it so the tests I wanted to focus on wouldn't even get run).  It also makes it so that log files are only created when `setUp` is run, and so `tearDown` will be able to clean them up, so we can remove the logging redirection that we had.
I saved the relevant variables to the class, so that, even though app initialization is only run in `setUp`, it doesn't get run more than once.
> Make service tests only construct the app when they are run

- .pylintrc
- allennlp/common/file_utils.py
- requirements.txt
- requirements_test.txt
- tests/common/file_utils_test.py
these fileutils will (once they're integrated elsewhere) allow us to specify URLs instead of files, resolving them to a local cache and downloading only if necessary.
this will allow us to point default configs to datasets / glove vectors on s3 instead of fixed paths.
we can also use this with `run evaluate` and so on
> add caching utils

- allennlp/modules/token_embedders/embedding.py
Pretty sure this was just introduced with the embedding fix PR that got merged late yesterday.
> Fix bug where embedding was always trainable

- requirements.txt
this fixes the issue that we see on Docker and in new installs.
I'm sending a PR to pyhocon to fix their bug as well.
> pin pyhocon to 0.3.35 (until they fix ConfigTree.pop())

- allennlp/modules/token_embedders/embedding.py
If we've just read a bunch of pre-trained vectors, we should initialize the embeddings for words that aren't in our pre-trained set to have the same mean and std as the pre-trained vectors.  This makes that happen
> Initialize non-pretrained words to be in the same space as pretrained words

- allennlp/commands/train.py
- allennlp/common/testing/test_case.py
- allennlp/models/archival.py
- allennlp/models/model.py
- allennlp/service/predictors/predictor.py
- allennlp/training/trainer.py
- experiment_config/bidaf.json
- experiment_config/decomposable_attention.json
- experiment_config/semantic_role_labeler.json
- scripts/regenerate_archived_models.py
- scripts/train_fixtures.py
- tests/commands/train_test.py
- tests/fixtures/bidaf/experiment.json
- tests/fixtures/decomposable_attention/experiment.json
- tests/fixtures/srl/experiment.json
- tests/models/archival_test.py
- tests/training/trainer_test.py
- tutorials/getting_started/getting_started.md
- tutorials/getting_started/simple_tagger.json
this was clunky and it turns out unnecessary.
we're already serializing it as `_model_params.json`, so we can just use that. also fixes a bug where we were popping off the trainer params before serializing.
(there is a stray change in here to add a default `Predictor` for the simple tagger, I need that for the Tutorial, and it was so minor that it didn't seem worth the work to split it out into its own PR)
> don't manually add the config file to the params for archiving

- doc/Makefile
- doc/conf.py
the important change is the one to `conf.py`, right now all of the "source" links in the docs point to `allennlp/deep_qa/whatever`
> deep_qa -> allennlp

- allennlp/modules/similarity_functions/bilinear.py
- allennlp/modules/similarity_functions/linear.py
- experiment_config/bidaf.json
And I fixed a small BiDAF parameter bug while I was at it.
> Add default initialization to linear and bilinear similarity functions

- allennlp/models/bidaf.py
- tests/commands/predict_test.py
- tests/models/bidaf_test.py
@schmmd, if you really want the tokenized question and/or passage for whatever reason, you could modify the BiDAF predictor to return the tokens in the resulting json: https://github.com/allenai/allennlp/blob/311db7f69ac809ceb4c1a47d1fe8da1203b4947b/allennlp/service/predictors/bidaf.py#L17
This PR should get you a decent pass at an answer string, though.
> Add best span string as output to `predict_span`

- Dockerfile.cpu
- README.md
This is needed in the short term for our continuous docker build by Docker Swarm.  I will figure out how to remove this before long, but I need it in the short term.
> Add back Dockerfile.cpu.

- allennlp/models/bidaf.py
- allennlp/models/decomposable_attention.py
- allennlp/models/semantic_role_labeler.py
- allennlp/models/simple_tagger.py
- allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py
- allennlp/modules/seq2vec_encoders/pytorch_seq2vec_wrapper.py
- tests/modules/seq2seq_encoders/pytorch_seq2seq_wrapper_test.py
- tests/modules/seq2vec_encoders/pytorch_seq2vec_wrapper_test.py
Thanks to @OyvindTafjord's exploration, I discovered I wasn't passing the mask into the modeling layer or the span end encoder in BiDAF.  I fixed that bug, and made the mask a required argument to the encoders, to head off any similar bugs later.
While I was at it, I also moved the conversion from binary mask to tensor of sequence lengths into the encoder wrappers themselves, so the model just has to worry about the mask.
> Require mask in encoders, update models, fix bug in BiDAF

- allennlp/data/fields/index_field.py
- allennlp/data/fields/label_field.py
- allennlp/data/fields/sequence_label_field.py
- allennlp/data/fields/text_field.py
- allennlp/service/predictors/semantic_role_labeler.py
- tests/data/dataset_test.py
- tests/data/fields/index_field_test.py
- tests/data/fields/label_field_test.py
- tests/data/fields/sequence_label_field_test.py
- tests/data/fields/text_field_test.py
- Adds type checks to all the fields.
- Change logic in `LabelField` to require labels to be strings if `skip_indexing=True`.
- Fixes a bug in the SRL predictor that meant we were trying to get the indexes of Spacy objects rather than strings, so they were returning OOV ids rather than the correct ids for the string.
> Predictor fix

- allennlp/data/dataset_readers/squad.py
- allennlp/data/token_indexers/single_id_token_indexer.py
- allennlp/data/token_indexers/token_characters_indexer.py
- allennlp/data/tokenizers/character_tokenizer.py
- allennlp/modules/token_embedders/embedding.py
- experiment_config/bidaf.json
- tests/fixtures/bidaf/experiment.json
Byte encoding converts tokens to ints directly, and using the vocabulary to then map those ints to other ints is both unnecessary and problematic (because how do you save the resultant int mapping, when the loading code expects that it's reading strings?).  This makes it so that `TokenIndexers` can bypass the vocabulary if what they're given is already an `int`.
I also fixed a small bug in the `SquadReader`, where we were removing newlines.  This was necessary for our old data code where we output one instance per line, but is no longer necessary.
> Fix byte encoding, bypassing the vocabulary

- build_tools/readthedocs/requirements.txt
- build_tools/travis/install.sh
This was breaking the ReadTheDocs build, and could break the Travis build.  I think the Travis build has only been working due to the cache.
> Use post3 url for PyTorch.

- tutorials/getting_started/configuration.md
I just looked over the tutorial - it looks great!  There was one minor tweak, though - I'd avoid using "namespace" in the way that you did, because those names are not actually related in any way to the vocabulary namespaces, and that could be confusing (and the vocab namespaces are an advanced topic, anyway, that most users shouldn't have to think about).
> Remove "namespace" from tutorial, play up a nice feature

- allennlp/data/dataset_readers/language_modeling.py
- allennlp/data/dataset_readers/snli.py
- allennlp/data/dataset_readers/squad.py
- allennlp/data/token_indexers/token_characters_indexer.py
- allennlp/data/tokenizers/character_tokenizer.py
- allennlp/data/tokenizers/word_tokenizer.py
- allennlp/models/bidaf.py
- allennlp/service/predictors/bidaf.py
- experiment_config/bidaf.json
- experiment_config/decomposable_attention.json
- tests/commands/evaluate_test.py
- tests/commands/predict_test.py
- tests/data/dataset_readers/language_modeling_dataset_test.py
- tests/data/dataset_readers/snli_reader_test.py
- tests/data/dataset_readers/squad_reader_test.py
- tests/data/tokenizers/character_tokenizer_test.py
- tests/data/tokenizers/word_tokenizer_test.py
- tests/fixtures/data/language_modeling.txt
- tests/fixtures/data/squad.json
- tests/models/bidaf_test.py
- tests/models/decomposable_attention_test.py
- tests/models/semantic_role_labeler_test.py
- tests/models/simple_tagger_test.py
Fixes #191.  This makes it a lot easier to add things like start and end characters, which otherwise would be very difficult to implement.  I also added the ability to change the padding index for characters when you're using byte encoding (MattP's code using 261 for the padding index, e.g., instead of 0, because 0 could be a byte in your byte stream*).
*Actually, I don't think that 0 is a valid byte in UTF-8, but we'll ignore that for now...
> Add start/end tokens to tokenizers, instead of in readers

- allennlp/models/archival.py
- tests/models/archival_test.py
this may be too aggressive (I can imagine wanting to use the evaluation_json_file in `run evaluate`, if that's the case I could check if it exists or pass through a flag not to delete it, but this was simplest)
(also, I know the config file in the test is sort of nonsensical)
> remove evalution_json_file key from config during load_archive

- allennlp/service/static/index.html
This removes the raw json response from the TE output.
I'm interested in having a raw json response on all the pages, but this output presently looks terrible.
> Remove debugging output from TE.

- allennlp/commands/serve.py
- allennlp/service/server_sanic.py
currently `allennlp/run serve` only works if you run it from the top level directory. with this change it should work no matter where you run it from.
also, this opens the door to specifying a different "static" dir at runtime, although I didn't implement that in `serve`
> stop using relative paths in service

- Dockerfile
- allennlp/common/registrable.py
- allennlp/data/dataset.py
- allennlp/data/dataset_readers/language_modeling.py
- allennlp/data/dataset_readers/semantic_role_labeling.py
- allennlp/data/dataset_readers/squad.py
- allennlp/data/fields/list_field.py
- allennlp/data/fields/sequence_label_field.py
- allennlp/data/fields/text_field.py
- allennlp/data/iterators/adaptive_iterator.py
- allennlp/data/tokenizers/word_splitter.py
- allennlp/data/vocabulary.py
- allennlp/modules/token_embedders/token_characters_encoder.py
- allennlp/service/predictors/semantic_role_labeler.py
- allennlp/training/metrics/span_based_f1_measure.py
- allennlp/training/optimizers.py
- allennlp/training/trainer.py
- build_tools/travis/install.sh
- tutorials/getting_started/getting_started.md
This lets us put type annotations on variables directly, instead of in comments, so we can get rid of all of the places we had to disable pylint's `unused-imports` check.
Fixes #254.
> Upgrade to python 3.6

- allennlp/modules/__init__.py
- allennlp/modules/attention.py
- allennlp/modules/augmented_lstm.py
- allennlp/modules/feedforward.py
- allennlp/modules/highway.py
- allennlp/modules/matrix_attention.py
- allennlp/modules/seq2seq_encoders/__init__.py
- allennlp/modules/seq2vec_encoders/__init__.py
- allennlp/modules/similarity_function.py
- allennlp/modules/similarity_functions/__init__.py
- allennlp/modules/stacked_alternating_lstm.py
- allennlp/modules/text_field_embedders/__init__.py
- allennlp/modules/time_distributed.py
- allennlp/modules/token_embedders/__init__.py
- doc/api/allennlp.models.model.rst
- doc/api/allennlp.modules.rst
- doc/api/allennlp.modules.similarity_functions.rst
- doc/api/allennlp.modules.text_field_embedders.rst
- doc/api/allennlp.modules.token_embedders.rst
there's a small amount of duplication, the docstring for the `text_field_embedders` module is basically a snippet from the docstring of `TextFieldEmbedder`, couldn't think of anything better to do. other than that should be pretty straightforward.
> api docs for the modules class

- allennlp/data/dataset_readers/dataset_reader.py
- allennlp/data/dataset_readers/language_modeling.py
- allennlp/data/dataset_readers/semantic_role_labeling.py
- allennlp/data/dataset_readers/sequence_tagging.py
- allennlp/data/dataset_readers/snli.py
- allennlp/data/dataset_readers/squad.py
- allennlp/models/bidaf.py
- allennlp/models/decomposable_attention.py
- allennlp/models/model.py
- allennlp/models/semantic_role_labeler.py
- allennlp/models/simple_tagger.py
- allennlp/nn/util.py
- allennlp/service/predictors/bidaf.py
- allennlp/service/predictors/decomposable_attention.py
- allennlp/service/predictors/predictor.py
- allennlp/service/predictors/semantic_role_labeler.py
- allennlp/service/predictors/simple_tagger.py
- tests/commands/predict_test.py
- tests/models/bidaf_test.py
- tests/models/decomposable_attention_test.py
- tests/models/semantic_role_labeler_test.py
- tests/models/simple_tagger_test.py
- tests/service/server_sanic_test.py
This is so that the `Predictors`, or anything else that wants to make
predictions given a trained model, has an easier time of processing the
data in the same way the trained model did - all you need is the
instantiated `DatasetReader`, and not any private members pulled out
from that class.
Changing this on the `DatasetReaders`, though, meant changing the
`Predictors` themselves.  And that meant unifying the API around making
model predictions from single instance inputs.  I was able to remove
all of the `tag` and `predict_` methods on individual models, replacing
them with a single `Model.forward_on_instance` method.  I _think_ the
result is a lot cleaner, but I could have missed something important
when making this change - it was a whole bunch of pulling things apart
and putting them …
> Adding a `text_to_instance` method on DatasetReader

- allennlp/modules/text_field_embedders/basic_text_field_embedder.py
This fixes the order of `tokens` vs `token_characters` when concatenated. This used to rely on dictionary ordering which changed from Python 3.5 to 3.6. This will fix it to the order we had in 3.5 (`token_characters` before `tokens`) and should have the earlier models behaving well again.
FYI @schmmd @matt-gardner
> Fix ordering of text field embedders

- setup.py
This fixes #285, I hadn't realised that if you specify 3.6 it isn't generic across sub-versions and actually means 3.6.0.
Also I don't know exactly how we want to manage releasing pip packages vs official releases. This seems important for people to be able to even install the package, so after this is approved i'll release a new minor version or something.
> fix python version compatibility

- allennlp/models/bidaf.py
- allennlp/training/metrics/__init__.py
- allennlp/training/metrics/squad_em_and_f1.py
So that SQuAD models other than BiDAF don't have to duplicate the metric code.
Fixes #245.
> Moving SQuAD metrics to a common place

- allennlp/data/tokenizers/word_splitter.py
- tests/data/tokenizers/word_splitter_test.py
A basic, unopinionated word splitter which keeps runs of (unicode) letters and runs of digits together, anything else is treated as single-character "words". Showed marginal improvement (compared to the default spacy English tokenizer) in BiDAF on SQuAD.
> Letters+digits word splitter

- Dockerfile
Without this PR, we inherit a MAINTAINER label from the base image, so it's listed as NVIDIA.
> Add MAINTAINER label to Dockerfile.

- allennlp/data/iterators/adaptive_iterator.py
- allennlp/data/iterators/bucket_iterator.py
Add a warning when passing `shuffle=False` to bucket and adaptive iterators.  Fixes #162.
> Iterators warning when shuffle is False

- allennlp/commands/__init__.py
- allennlp/commands/predict.py
- allennlp/commands/serve.py
- allennlp/service/predictors/__init__.py
- allennlp/service/predictors/predictor.py
- allennlp/service/server_sanic.py
- tests/commands/predict_test.py
- tests/commands/serve_test.py
- tests/service/predictors/bidaf_test.py
- tests/service/predictors/decomposable_attention_test.py
- tests/service/predictors/srl_test.py
- tests/service/server_sanic_test.py
this addresses https://github.com/allenai/allennlp/issues/323 and is a better design anyway
here `DEFAULT_MODELS` and `DEFAULT_PREDICTORS` are defined with `allennlp.commands.main()` which now takes optional dicts of overrides.
after this change, if someone implements their own predictors, they can just specify them when they call `main()`
still needs tests
> make default models and default predictors configurable

- allennlp/modules/similarity_functions/dot_product.py
- allennlp/modules/similarity_functions/linear.py
- allennlp/nn/util.py
So that I can use them in other places (particularly in a multi-headed attention encoder).
I also added an option for scaling the dot product similarity.
> Move combine_tensor methods into a common location

- allennlp/data/tokenizers/word_splitter.py
- allennlp/data/vocabulary.py
- tests/data/tokenizers/word_splitter_test.py
- tests/data/vocabulary_test.py
As discussed in https://github.com/allenai/allennlp/issues/338, simple fix for bug in reading newline-like tokens.
> Fix misreading of newline-like vocab tokens

- allennlp/training/trainer.py
based on a suggestion I added intermittent "log metrics to tensorflow" in the middle of an epoch. but that method had log statements in it, which means that you get metrics logged to the console in the middle of an epoch, which looks bad and mucks with tqdm and everything.
anyway, I split out the log statements into a separate `_metrics_to_console` function, and I only call it at the end of an epoch. (the metrics still are part of the tqdm description)
> don't log metrics to console in the middle of an epoch

- tests/nn/util_test.py
I noticed that the constraints part of the vitterbi test had two equally likely sequences, so I fixed it to only have one.
> make viterbi test more specific

- allennlp/training/metrics/span_based_f1_measure.py
- tests/training/metrics/span_based_f1_measure_test.py
This adds an optional prediction_map to the SpanBasedF1Measure. If provided, this gives a mapping from the ''num_classes'' dimension of ''predictions'' to the indices of the label vocabulary. In other words, the label at each timestep is ``vocabulary.get_index_to_token_vocabulary(prediction_map[batch, argmax(predictions[batch, t]))``, rather than simply ``vocabulary.get_index_to_token_vocabulary(argmax(predictions[batch, t]))``.
This is useful when you have a task where each datapoint can select from a different subset of possible labels (for instance, FrameNet Frame Semantic Parsing, where each Frame has a different set of Roles associated with it).
> Add an optional prediction map to SpanBasedF1Measure

- Dockerfile
fixes #372 and shaves about 0.8GB off our image size 👍.
> don't pull cuda runtime twice

- allennlp/data/fields/label_field.py
- tests/data/fields/label_field_test.py
Fixes #382.
This fixes the empty_field method of LabelField, which currently fails because skip_indexing is not True.
> Fixes empty_field method of LabelField and adds a test

- allennlp/commands/train.py
It was annoying to add the test vocab to the vocabulary creation, so I made it possible to read the test data like we do for the other datasets. Given that we load it in, I figured it would make sense to call `evaluate` on it if a user passed it.
> add optional test data to train

- allennlp/commands/train.py
My previous version of this was mutating `train_data.instances`, meaning that it was including the validation and test data. 😞  This version doesn't modify the datasets and also avoids copying them.
> don't mutate training data with test data

- allennlp/commands/predict.py
- allennlp/models/model.py
- allennlp/service/predictors/predictor.py
- allennlp/service/predictors/semantic_role_labeler.py
- kubernetes-dev-environment.yaml
- tests/commands/predict_test.py
- tests/service/server_sanic_test.py
This removes some brittle code that only works on machines with 1 GPU and lets you make predictions with a GPU.
On a `p2.xlarge` with a GPU a BiDAF prediction takes 0.20 seconds.  Without a GPU on the same machine a prediction takes 0.44 seconds.  Not a huge difference, because the code is set up to make one prediction at a time.
Fixes #303.
> Add a `cuda_device` option to `predict`.

- Dockerfile
- requirements.txt
* Remove conda.
* Use Debian instead of Ubuntu.
This trims another 200 MB from our Docker file.
```
~/h/a/allennlp (python-docker $%) docker images                                                                                                                                                                                     (allennlp) 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
allennlp/allennlp   python-jesse        74f6e1cbc41e        36 minutes ago      2.45GB
allennlp/allennlp   latest              547826cf4c97        About an hour ago   2.64GB
python              3.6.3-jessie        be512ebcbac9        5 days ago          690MB
```
> Use a Python base image.

- allennlp/nn/util.py
- tests/nn/util_test.py
Following points made by @kentonl in #364.
I also tried to switch `masked_softmax` to just use `vector += mask.log(); return F.softmax(vector)`.  I ran into trouble there, because it doesn't handle cases where the mask is zero everywhere (or zero for all entries in a row in the matrix, e.g., because a whole row is padded), which is important for some of our uses.  There didn't seem to be an easy way to fix that without just doing what we're already doing.  Maybe I'll figure something out, but I'm not optimistic.
> Use bmm to do an efficient weighted sum in cases where it applies

- allennlp/nn/util.py
- tests/nn/util_test.py
Also due to things pointed out by @kentonl in #364 (as well as a reminder in the pytorch slack channel that there's an easy way to renormalize after-the-fact).  I was able to remove our manual softmax operation by being smarter about how to use the mask (the exact operation is different in the `masked_softmax` vs. the `masked_log_softmax` cases).
> Using F.softmax directly to do the softmax, with more efficient fixes

- allennlp/data/dataset_readers/coreference_resolution/conll.py
- allennlp/models/coreference_resolution/coref.py
- allennlp/nn/util.py
- tests/nn/util_test.py
Note this is a PR to the `coref-wip` branch.
This just adds some tests for the batch index select functions and removes the zeros function.
Ignore the test that is failing - it's unrelated and I haven't fixed it yet.
> Coref util tests

- allennlp/data/fields/index_field.py
- tests/data/fields/index_field_test.py
I am using the same logic as `LabelField` and the `coref-wip` branch to deal with padding. However the documentation of `IndexField` allows for the index to be `Optional`. Should I instead change the constructor to allow for `None` to be a valid index argument ?
> Make sure IndexField padding passes valid arguments

- allennlp/data/token_indexers/token_characters_indexer.py
This prevents a crash when you have an empty token list, as can happen, say, from padding `ListField`s.
> Allow empty token lists to be padded

- allennlp/training/trainer.py
- tests/training/trainer_test.py
This fixes early-stopping / patience in the trainer. Patience should be defined as "Stop if you haven't improved the metric in N epochs", but the previous definition was "Stop if the current score is worse than the worse in N epochs". This lead to cases where training would stop even if the metric had increased recently.
> Fix patience

- scripts/ai2-internal/run_with_beaker.sh
Beaker changed the way single-file datasets are handled, so we need to change our script accordingly.
> Minor fix to beaker script

- allennlp/models/encoder_decoders/simple_seq2seq.py
Fixes #431.
We had originally used `with torch.cuda.device_of(some_variable)` to create new variables, thinking that this would create them on the save device as `some_variable`.  Turns out this doesn't actually work.  This fixes the last place in the code where we still used this pattern (I think...).
> Remove `with torch.cuda.device_of`, which doesn't do what we thought

- allennlp/nn/util.py
- tests/nn/util_test.py
As discussed per email, a possible simple fix (or at least substantial improvement without much loss of efficiency) for an issue with large elements outside the mask messing up the softmax calculations:
```
>>> import torch
>>> from allennlp.nn import util
>>> x1 = torch.autograd.Variable(torch.Tensor([[1,1,2],[1,1,100]]))
>>> mask = torch.autograd.Variable(torch.Tensor([[1,1,0],[1,1,0]]))
>>> util.masked_softmax(x1, mask)
Variable containing:
0.5000  0.5000  0.0000
0.0000  0.0000  0.0000
[torch.FloatTensor of size 2x3]
```
> Fix masked softmax

- .travis.yml
- allennlp/common/file_utils.py
- allennlp/common/tee_logger.py
- allennlp/data/dataset_readers/conll2003.py
- allennlp/data/dataset_readers/reading_comprehension/util.py
- allennlp/data/dataset_readers/seq2seq.py
- allennlp/models/archival.py
- allennlp/models/crf_tagger.py
- build_tools/travis/test_script.sh
- doc/api/allennlp.common.file_utils.rst
- doc/api/allennlp.common.rst
- doc/api/allennlp.common.squad_eval.rst
- doc/api/allennlp.common.tee_logger.rst
- doc/api/allennlp.data.dataset_readers.conll2003.rst
- doc/api/allennlp.data.dataset_readers.reading_comprehension.rst
- doc/api/allennlp.data.dataset_readers.rst
- doc/api/allennlp.data.dataset_readers.seq2seq.rst
- doc/api/allennlp.data.fields.rst
- doc/api/allennlp.data.token_indexers.rst
- doc/api/allennlp.data.tokenizers.rst
- doc/api/allennlp.models.archival.rst
- doc/api/allennlp.models.crf_tagger.rst
- doc/api/allennlp.models.encoder_decoders.rst
- doc/api/allennlp.models.rst
- doc/api/allennlp.modules.seq2seq_encoders.rst
- doc/api/allennlp.modules.seq2vec_encoders.rst
- doc/api/allennlp.service.predictors.rst
- doc/api/allennlp.training.metrics.rst
- doc/conf.py
- scripts/check_docs.py
most of this is just sphinx junk. the interesting parts are
* in [doc/conf.py](https://github.com/allenai/allennlp/pull/440/files#diff-684a0ceb2878d48b19612ca360e277ef) I enabled the sphinx-coverage plugin, which allows you to run "sphinx coverage", which is useful only for telling you what functions you missed in the python modules that are covered. In particular, it's not helpful for telling you that you forgot to add your new module to the docs.
* [scripts/check_docs.py](https://github.com/allenai/allennlp/pull/440/files#diff-803091b6e53da6bf7a2e907676fbd417) is a somewhat hacky script to tell you if you have any modules in your code that are not mentioned in the docs and vice versa. This is not perfect, but it's a lot better than what we have now. I also added a Travis option to run …
> sphinx coverage

- allennlp/commands/predict.py
- allennlp/models/model.py
- allennlp/service/predictors/predictor.py
- allennlp/service/predictors/semantic_role_labeler.py
- tests/commands/predict_test.py
- tests/service/predictors/bidaf_test.py
- tests/service/predictors/decomposable_attention_test.py
- Adds batch prediction to the `Model` and `Predictor`. 
- I left adding batch prediction to the sanic server because that seems fairly separate, although easily possible.
Currently, `Model.forward_on_batch` returns a dict like {"key": [list of predictions for batch]}, but I could imagine it might be better to have [{"key": batch1prediction}, {"key": batch2prediction}] as then the output from a single element in the batch would match the output of `Model.forward_on_instance`. If people have strong opinions either way i'll change it.
@lucylw FYI - this is what you need to have the stream prediction from JSON you wanted.
> add batch prediction to model and predictor

- allennlp/common/util.py
- tests/common/test_util.py
I ran into a case where I needed to sanitize `Variable` and `LongTensor` (not caught by `Tensor`). I could get rid of the former in my output, but it shouldn't hurt to cover this case too?
> More sanitize cases

- allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py
- tests/modules/seq2seq_encoders/pytorch_seq2seq_wrapper_test.py
Pytorch doesn't like it if you pad to greater than the max sequence length for tensors, but @wilburOne needs this to be preserved.
> Seq length padding fix

- allennlp/data/fields/label_field.py
- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- allennlp/nn/decoding/beam_search.py
- allennlp/nn/decoding/maximum_marginal_likelihood.py
I did some profiling to see where the bottlenecks were, and I fixed some of them.  This got me a 2-2.5x speedup.  I don't think there's much more gain to be had apart from with batching.
I also went over the computation we're doing in detail with @DeNeutoy, because I was seeing some odd behavior trying to get this to learn.  We discovered that we weren't using the current input at timestep t as part of the attention over the question, and that we weren't doing the output projection as nicely as we could, either.  I fixed those issues here, and tried to have the model learn my simple word segmentation problem.  I made it even simpler, with just one corrupted example, but I think I'm asking the model to learn too much from too small a dataset.  It clearly is able to learn something, but …
> Bug fixes in loss computation, speed improvements from profiling

- demo/src/App.js
- demo/src/api-config.js
- demo/src/components/McComponent.js
- demo/src/components/SrlComponent.js
- demo/src/components/TeComponent.js
we want to hardcode the backend as localhost:8000 for development but not for production. this is a quick and dirty way to make that happen
> make API_ROOT depend on window.location.origin

- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- allennlp/nn/decoding/beam_search.py
- allennlp/nn/decoding/decoder_state.py
- allennlp/nn/decoding/decoder_step.py
- allennlp/nn/decoding/decoder_trainer.py
- allennlp/nn/decoding/maximum_marginal_likelihood.py
- tests/nn/decoding/maximum_marginal_likelihood_test.py
There are two kinds of batching going on here: we process several training instances at once, _and_ we process several states for each training instance at once.  Hopefully the docs I wrote make this clear enough.
I switched to a simpler copying task, where I'm training the model to copy the input given noisy supervision, and I'm still having trouble getting it to train correctly.  But at least this logic runs, and I _think_ I did everything correctly here.  It gives about an 8x speedup when using a batch size of 60 instead of a batch size of 1 (and that's on top of a minor speed up using a batch size of 1 that I got from batching together several states for each instance).  I haven't tried profiling this at all, and there might be more gains to be had somewhere in here with some careful …
> Implemented batched decoding

- allennlp/commands/__init__.py
- allennlp/commands/predict.py
- allennlp/commands/serve.py
- allennlp/service/predictors/__init__.py
- allennlp/service/predictors/predictor.py
- allennlp/service/server_sanic.py
- scripts/cache_models.py
- tests/commands/predict_test.py
- tests/commands/serve_test.py
- tests/models/sniff_test.py
change dict used by run/serve from 
{predictor_name -> archive_file} 
to 
{demo_model_name -> (predictor_name, archive_file)}
which is a better representation and (in particular) allows us to have different demo models that share the same `Predictor` wrapper
(this will allow us to have a single `sentence_tagger` predictor that can be used by the NER model and by (say) a future POS tagger)
> introduce `DemoModel` abstraction

- allennlp/training/metrics/span_based_f1_measure.py
- tests/training/metrics/span_based_f1_measure_test.py
@nikett This was the problem with calling the metric the way you were, as there could have been fully padded sequences because you were using a `ListField[TextField]`.
> make span f1 robust to zero length sequences

- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- allennlp/nn/util.py
- tests/nn/util_test.py
So far, this is just setting up a variable number of valid actions, and changing the model to do a dot product with a smaller set of action embeddings, instead of a softmax over all actions.  Next, I will use the grammar and action history to actually select a set of valid actions at each state.
> Add constrained decoding to the DecoderStep

- allennlp/data/dataset_readers/__init__.py
- allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py
- allennlp/data/fields/knowledge_graph_field.py
- allennlp/data/knowledge_graph.py
- allennlp/data/vocabulary.py
- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- tests/data/dataset_readers/wikitables/wikitables_dataset_reader_test.py
- tests/fixtures/encoder_decoder/wikitables_semantic_parser/experiment.json
- tests/models/encoder_decoders/wikitables_semantic_parser_test.py
This initial version just reads a set of allowed productions from the training data, meaning that it won't generalize to unseen tables at test time, but at least it works!  The next step is to make the valid actions at each step instance-specific, then make them state-specific also.
I don't have good tests for any of the stuff I did in here yet.  I'd like to make good tests for the valid action stuff, and separate out the code a bit, but that'll be easier in the next step.  I'll make something like a `GrammarState`, that contains the `non_terminal_stack` that I used here, and have that object be richer, and testable.
> Actually use type constrained decoding

- Dockerfile
- allennlp/commands/__init__.py
- allennlp/commands/evaluate.py
- allennlp/commands/predict.py
- allennlp/commands/serve.py
- allennlp/commands/train.py
- tests/commands/evaluate_test.py
- tests/commands/main_test.py
- tests/commands/predict_test.py
- tests/commands/train_test.py
- tutorials/getting_started/training_a_model.md
this addresses https://github.com/allenai/allennlp/issues/511
it does the following things (I will use cuda_device as an example, but it does something similar for every multi-word argument)
(1) creates a `cuda_device` "mutually exclusive group"
(2) changes the existing argument to `cuda-device` under that group
(3) also includes a `cuda_device` argument under that group with `help=argparse.SUPPRESS`
this means that if you run (say) `allennlp/run predict --help` it only shows the option
```
--cuda-device CUDA_DEVICE
id of GPU to use (if any)
```
however, if you pass in the argument as `--cuda_device` it will still work (in order not to break anyone's existing code). This all feels slightly clunky, but breaking existing workflows seems like a non starter.
IN ADDITION, there is a dict of { …
> update CLI casing

- scripts/ai2-internal/deploy-production-demo.sh
This change prevents new pods from being used before they are accepting HTTP requests.  There's a rather long period of time after the container starts where the application is downloading models and initializing AllenNLP but is not accepting requests.
> Add readiness probe for production deployments.

- allennlp/service/server_sanic.py
- demo/src/index.js
The bootstrapped ReactJS application enabled service workers, which is something we don't want.  From [the web](https://developers.google.com/web/fundamentals/primers/service-workers/): "A service worker is a script that your browser runs in the background, separate from a web page, opening the door to features that don't need a web page or user interaction. Today, they already include features like push notifications and background sync."
While I'm not sure it's strictly necessary I also set no cache headers for our API responses.
> Disable Service Workers

- allennlp/__init__.py
`allennlp/__init__.py` seems like the right place for it, so it will kick in even if people don't use our `run` script.
https://stackoverflow.com/a/1093331/1076346
> raise RuntimeError if python < 3.6

- allennlp/modules/__init__.py
- allennlp/modules/scalar_mix.py
- doc/api/allennlp.modules.rst
- doc/api/allennlp.modules.scalar_mix.rst
- tests/modules/scalar_mix_test.py
Add `ScalarMix` module that computes scalar weighted averages of tensors, with optional layer normalization
> Add `ScalarMix` module

- scripts/ai2-internal/deploy-production-demo.sh
- scripts/ai2-internal/deploy-staging-demo.sh
* Set up proxys for GCP databases (follows https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine).
* Add liveness probe to staging.
> Support databases on GCP.

- scripts/write_srl_predictions_to_conll_format.py
Fixes a bug in the script write_srl_predictions_to_conll_format.py which was swapping the gold and predicted labels.
> Fixes SRL prediction script swapping gold and pred

- allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py
- allennlp/data/semparse/type_declarations/nlvr_type_declaration.py
- allennlp/data/semparse/type_declarations/type_declaration.py
- allennlp/data/semparse/type_declarations/wikitables_type_declaration.py
- allennlp/data/semparse/worlds/__init__.py
- allennlp/data/semparse/worlds/nlvr_world.py
- allennlp/data/semparse/worlds/wikitables_world.py
- allennlp/data/semparse/worlds/world.py
- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- doc/api/allennlp.data.semparse.type_declarations.rst
- doc/api/allennlp.data.semparse.worlds.rst
- tests/data/dataset_readers/wikitables/wikitables_dataset_reader_test.py
- tests/data/semparse/type_declarations/type_declaration_test.py
- tests/data/semparse/type_declarations/wikitables_type_declaration_test.py
- tests/data/semparse/worlds/nlvr_world_test.py
- tests/data/semparse/worlds/wikitables_world_test.py
This PR mainly contains a type declaration for NLVR, and the functionality to turn NLVR logical forms into action sequences. In the process of doing that, I made several changes:
1) Defined new module `type_declaration` that contains general classes for creating type systems for new domains.
2) Defined a new class `World` that contains generic methods for logical form processing and for making action sequences.
3) Redefined action sequences to contain original names instead of translated names (given by the name mapping).
4) Made some tweaks to the NLVR language to make type checking work correctly. The only major change is that the language now has lambda forms in `filter_*` functions. Actually, we had lambda forms even earlier, because the second argument to the `filter_*` functions was …
> NLVR Type Declaration

- allennlp/common/testing/model_test_case.py
- tests/models/reading_comprehension/bidaf_test.py
They have been failing due to a mismatch of 0.141%.
Fixes #565
> Increase tolerance of BiDAF tests.

- allennlp/nn/util.py
- tests/nn/util_test.py
`get_text_field_mask` was returning the wrong mask for models with purely character input.  This PR fixes it.
> Add support for purely character input in `get_text_field_mask`

- allennlp/data/dataset_readers/dataset_utils/__init__.py
- allennlp/data/dataset_readers/dataset_utils/ontonotes.py
- doc/api/allennlp.data.dataset_readers.dataset_utils.ontonotes.rst
- doc/api/allennlp.data.dataset_readers.dataset_utils.rst
- doc/api/allennlp.data.dataset_readers.rst
- tests/data/dataset_readers/ontonotes_test.py
Adds a `Ontonotes` class which reads all Ontonotes 5.0 annotations into a generator of `OntonotesSentence`'s. This is eventually going to be used heavily in the SRL reader and will replace the `_DocumentState` class in the coref reader, but this is a natural breaking point to split it up. 
`nltk` does have an ontonotes reader, but it reads everything in separate passes over the dataset and also doesn't read coref annotations, for some reason. I decided it would just be easier to have our own, rather than subclassing theirs, as they do loads of weird hyper functional stuff with maps and curried lazy loading etc which is not very pythonic and very obtuse.
> Canonical ontonotes

- allennlp/models/encoder_decoders/simple_seq2seq.py
After applying the change, training code runs on GPU error-free.
(Fixes #585)
> Fixed casting to FloatTensor in simple_seq2seq.py (#583)

- allennlp/data/semparse/type_declarations/nlvr_type_declaration.py
- allennlp/data/semparse/type_declarations/type_declaration.py
- allennlp/data/semparse/type_declarations/wikitables_type_declaration.py
- allennlp/data/semparse/worlds/world.py
- tests/data/semparse/type_declarations/type_declaration_test.py
- tests/data/semparse/worlds/nlvr_world_test.py
I mainly added a method `type_declaration.get_valid_actions()` that takes a name mapping, type signatures and a set of basic types and produces a dict from all non-terminals to productions starting from them.
@matt-gardner I tested this on the NLVR type declaration, and it works, but with wikitables, it has some problems with placeholder types. I also need to test it with table specific mappings.  I'll fix those soon. But I'm making this PR now to show you the API, so that you can continue with the stuff you're doing.
> Grammar from type declaration

- demo/src/components/SrlComponent.js
* Fixes #562;
* Fixes #567;
@schmmd Please review.
> Filter out trees with no children, but retain those with a single child.

- allennlp/commands/evaluate.py
- allennlp/common/testing/model_test_case.py
- allennlp/models/crf_tagger.py
- allennlp/models/model.py
- allennlp/modules/elmo.py
- allennlp/modules/elmo_lstm.py
- allennlp/nn/util.py
- allennlp/training/trainer.py
- scripts/evaluate_squad_model.py
- scripts/write_srl_predictions_to_conll_format.py
- tests/models/crf_tagger_test.py
- tests/models/decomposable_attention_test.py
- tests/models/encoder_decoders/simple_seq2seq_test.py
- tests/models/reading_comprehension/bidaf_test.py
- tests/models/semantic_role_labeler_test.py
- tests/models/simple_tagger_test.py
- tests/modules/conditional_random_field_test.py
- tests/modules/seq2seq_encoders/pytorch_seq2seq_wrapper_test.py
- tests/modules/seq2vec_encoders/pytorch_seq2vec_wrapper_test.py
- tests/modules/token_embedders/elmo_token_embedder_test.py
- Checks that parameters are getting gradients which need them in the model test cases.
- Removes all `.forward` references as Pytorch 0.3 has our bug fixes for modules which return dictionaries
- Fixes a bug in the sentence boundary function for ELMo which was not correctly recording inplace operations in the `Variable`
Fixes #456 
Fixes #494
> Grad checks

- tutorials/getting_started/using_in_your_repo.md
Missing "http://" caused markup file to think it is a relative path.
> Fix a link to the open research corpus

- allennlp/data/dataset.py
- allennlp/data/fields/__init__.py
- allennlp/data/fields/field.py
- allennlp/data/fields/knowledge_graph_field.py
- allennlp/data/fields/list_field.py
- allennlp/data/fields/production_rule_field.py
- allennlp/data/fields/text_field.py
- doc/api/allennlp.data.fields.rst
- tests/data/fields/production_rule_field_test.py
- tests/models/encoder_decoders/wikitables_semantic_parser_test.py
@DeNeutoy, @pdasigi, this PR implements the `ProductionRuleField` we talked about.  Eventually, this will be doubly nested somehow (probably in a couple of modified `ListFields`), so we have lists of production rule sequences.
While I was at it, I made a change to how "metadata" is handled in our processing, because the way we represent these arrays is going to break that code, anyway (this PR doesn't have a test that takes a `ProductionRuleField` and passes its output through `arrays_to_variables`, but it wouldn't work, as the tests that are currently failing here demonstrate).  So, @DeNeutoy, any ideas on how to fix `arrays_to_variables`?  Maybe I'll ask you and @joelgrus after our meeting tomorrow, as this might be easier to talk about in person, and the only solutions I can think of …
> ProductionRuleField

- allennlp/data/tokenizers/token.py
Fixes #624 by adding `__str__` and `__repr__` magic methods to the `Token` class, enabling them to be printed / logged.
Does this need a test? If so, where do you think is a good place?
> Add __str__ and __repr__ to Token class

- tutorials/getting_started/installation.md
I was reading the installation tutorial to figure out how to build from source to contribute, and I noticed that there was no mention of actually running `python setup.py install` to install the cloned version of allennlp. This PR fixes that.
In addition, there are still some mentions of PyTorch 0.2 when it looks like you've moved on to 0.3 --- changed those as well.
> Update install tutorial for PyTorch 0.3, mention python setup.py install

- allennlp/data/dataset_readers/seq2seq.py
- tests/data/dataset_readers/seq2seq_test.py
End token is always added to the source while adding the start token is optional. 
Fixes #611.
> Add end and optional start tokens to source sentence in seq2seq DatasetReader (fixes #611)

- allennlp/common/checks.py
- allennlp/common/testing/model_test_case.py
- allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py
- allennlp/data/fields/knowledge_graph_field.py
- allennlp/data/fields/list_field.py
- allennlp/data/fields/text_field.py
- allennlp/data/semparse/knowledge_graphs/knowledge_graph.py
- allennlp/data/semparse/type_declarations/__init__.py
- allennlp/data/semparse/type_declarations/grammar_state.py
- allennlp/data/semparse/type_declarations/type_declaration.py
- allennlp/data/semparse/worlds/nlvr_world.py
- allennlp/data/semparse/worlds/wikitables_world.py
- allennlp/data/semparse/worlds/world.py
- allennlp/models/crf_tagger.py
- allennlp/models/decomposable_attention.py
- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- allennlp/models/reading_comprehension/bidaf.py
- allennlp/models/semantic_role_labeler.py
- allennlp/models/simple_tagger.py
- allennlp/nn/decoding/maximum_marginal_likelihood.py
- allennlp/nn/util.py
- doc/api/allennlp.data.semparse.type_declarations.rst
- tests/data/dataset_readers/wikitables/wikitables_dataset_reader_test.py
- tests/data/semparse/type_declarations/grammar_state_test.py
- tests/data/semparse/type_declarations/type_declaration_test.py
- tests/data/semparse/worlds/nlvr_world_test.py
- tests/data/semparse/worlds/wikitables_world_test.py
- tests/fixtures/encoder_decoder/wikitables_semantic_parser/experiment.json
- tests/models/encoder_decoders/wikitables_semantic_parser_test.py
- tests/nn/decoding/maximum_marginal_likelihood_test.py
This PR modifies the `WikiTablesDatasetReader` to use the new `ProductionRuleField`, and the `WikiTablesSemanticParser` to also take the new data format.  It's close, but not quite done.  I ran into a bit of a snag when trying to produce lambda expressions.
The gist of how this works is that we enumerate all possible actions up front, in the `DatasetReader`, so that we can get indexed representations of every possible action.  Then, in the model, we'll embed those representations before decoding, and just _reference_ the embedded vectors when we need them during decoding.  I had a few issues getting a representation for all of the possible actions, and I was able to resolve most of them, but the lambda expressions are giving me trouble.  I'll put a note in the code for the particular spot …
> Use production rule field

- allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py
- allennlp/data/fields/knowledge_graph_field.py
- allennlp/data/semparse/knowledge_graphs/knowledge_graph.py
- allennlp/data/semparse/knowledge_graphs/table_knowledge_graph.py
- allennlp/data/semparse/worlds/wikitables_world.py
- allennlp/data/tokenizers/token.py
- allennlp/data/tokenizers/word_stemmer.py
- allennlp/data/tokenizers/word_tokenizer.py
- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- tests/data/dataset_readers/wikitables/wikitables_dataset_reader_test.py
- tests/data/fields/knowledge_graph_field_test.py
- tests/data/semparse/knowledge_graphs/table_knowledge_graph_test.py
This builds on #639 (which in turn builds on #606).  I'll rebase this once that one is merged.  It's only the most recent two commits shown in the list.
This PR makes the `KnowledgeGraphField` actually work the way that the original parser did.  We have two separate representations for each KG entity: an embedded representation of the text in the corresponding cell, and a set of linking features for each token in the question.  I haven't updated the model code to _use_ this at all - that will come next.
I've implemented most of the entity linking features from the original parser, except for the span matching ones.  Shouldn't be _too_ hard to add those, but it will be a little annoying.
> Better KnowledgeGraphField

- allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py
- allennlp/data/fields/production_rule_field.py
- allennlp/data/semparse/worlds/wikitables_world.py
- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- tests/data/dataset_readers/wikitables/wikitables_dataset_reader_test.py
- tests/data/fields/production_rule_field_test.py
- tests/models/encoder_decoders/wikitables_semantic_parser_test.py
This implements action scores based on entity linking, for terminal entity productions.  We had previously assumed that every action had an embedding, and we used that for scoring actions. 
This ignores the linking scores between the table and the question, and the current question attention at the given timestep.  This now implements equations 5 and 6 in the paper correctly, though it uses fake linking scores, as @rajasagashe is still implementing that piece.  Once Rajas is done, the model should be finished, and we can try to reproduce the original numbers.
This PR depends on #663 (which depends on #639).  I'll rebase this once those two PRs are merged.
> Use linking for action scoring

- .travis.yml
This is configured in TeamCity now and we don't want it running in both places.
On Thursday I'll make a PR that removes Travis entirely from our repo.
> Disable running coverage in Travis.

- requirements_test.txt
I'll also open a P3 issue to investigate which version of mypy we should be using, and whether there's a bug we should report upstream in version 0.560.  See #680 for more context.
> Pin mypy to 0.521

- Dockerfile
The `LABEL` was one way of doing this supported by an older version of nvidia-docker - the env variables are the new way, so let's have both for super-duper compatibility.
> make driver config robust to nvidia-docker version

- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- tests/models/encoder_decoders/wikitables_semantic_parser_test.py
I also added a test that failed before I made the change.  Almost all of the changes here are in test code.  And I tried to add some better comments for what's going on in the tests, as this code is far too complex...
> Handle padding correctly in _compute_new_states

- allennlp/data/fields/__init__.py
- allennlp/data/fields/index_field.py
- allennlp/data/fields/span_field.py
- doc/api/allennlp.data.fields.rst
- tests/data/fields/index_field_test.py
- tests/data/fields/span_field_test.py
Whilst doing this I came across [this](https://github.com/allenai/allennlp/blob/master/allennlp/data/fields/index_field.py#L41), which I think is redundant. I can add a commit to remove it and it's associated test, but I wasn't sure if there was something non-obvious it was used for, as you're more familiar with the Bidaf code than I am.
> Span field

- allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py
- allennlp/data/fields/knowledge_graph_field.py
- allennlp/data/semparse/util.py
- allennlp/data/semparse/worlds/nlvr_world.py
- allennlp/data/semparse/worlds/world.py
- doc/api/allennlp.data.semparse.rst
- doc/api/allennlp.data.semparse.util.rst
- tests/data/dataset_readers/wikitables/wikitables_dataset_reader_test.py
- tests/data/semparse/knowledge_graphs/table_knowledge_graph_test.py
- tests/data/semparse/type_declarations/grammar_state_test.py
- tests/data/semparse/util_test.py
- tests/data/semparse/worlds/nlvr_world_test.py
- tests/data/semparse/worlds/wikitables_world_test.py
- tests/data/semparse/worlds/world_test.py
I did some profiling to figure out why our data loading code took so long, and fixed some of the worst problems.  These were (1) using a lisp parser to read the example file, which can just as easily be read with some simple string splits, and (2) running spacy's tagger to get lemmas, but not using spacy's batching.  I had to implement batched tokenization for this, and merging this should probably wait until #680 is merged into master.
> Speed up WikiTablesDatasetReader

- allennlp/commands/evaluate.py
- allennlp/commands/predict.py
- allennlp/commands/train.py
- allennlp/common/util.py
- allennlp/service/server_simple.py
- tests/commands/evaluate_test.py
- tests/commands/predict_test.py
- tests/commands/train_test.py
- tests/common/test_util.py
- tutorials/getting_started/creating_a_model.md
- tutorials/getting_started/using_in_your_repo.md
Reverts allenai/allennlp#695
although the tests all pass on teamcity, they now fail on my machine, in weird non-deterministic ways, and I'm having a really hard time debugging why, so I'm going to revert this for now so it doesn't bite anyone else
> Revert "programmatic imports of third-party models"

- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- scripts/ai2-internal/run_with_beaker.sh
This reduces the percent of computation done in `_get_linking_probabilities` to approximately zero, giving a roughly 30% reduction in training time.
@rajasagashe, github isn't letting me add you as a reviewer, or I would have done it.
> Speed up get_linking_probabilities

- allennlp/models/coreference_resolution/coref_v2.py
- allennlp/modules/span_extractors/endpoint_span_extractor.py
- tests/modules/span_extractors/endpoint_span_extractor_test.py
replaces the two relevant methods in the coref model with their corresponding `SpanExtractors`.
> integrate span_extractors into coref model

- allennlp/data/dataset_readers/nlvr.py
- allennlp/data/semparse/type_declarations/nlvr_type_declaration.py
- allennlp/data/semparse/worlds/world.py
- allennlp/models/encoder_decoders/nlvr_semantic_parser.py
- tests/data/dataset_readers/nlvr_test.py
- tests/data/semparse/worlds/world_test.py
- tests/fixtures/encoder_decoder/nlvr_semantic_parser/experiment.json
I've added more rules in the agenda mapping scheme.
From the training logs, it seemed like the parser was having difficulty reaching the terminal states because it does not have any signal indicating whether it is taking the right path. So I added an option to include the non-terminal productions from the paths to the agenda as well. However, I do not see noticeable differences in the parser's training yet.
This PR depends on #713 (which depends on #607)
> Agenda improvements

- allennlp/commands/evaluate.py
- allennlp/training/trainer.py
When training models there's significant output because `tqdm.set_description` updates the tqdm output immediately instead of waiting for `mininterval` to pass.  I didn't notice this when testing locally because training is slow without a GPU.
> Set refresh to False when training to prevent extra TQDM output.

- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
- tests/models/encoder_decoders/wikitables_semantic_parser_test.py
@DeNeutoy's #730 reminded me that I wanted to try using `split()` instead of slicing when we're regrouping all of the intermediate states in the decoder.  I looked at a profiler to see where we were spending the most time in slicing operations, and tried converting all of them to `split()`.  These are the ones that helped.  The comment should explain what's going on here.
> Use split() to get a minor speedup

- allennlp/commands/elmo.py
- tests/commands/elmo_test.py
I think this is an improvement:
* It removes an argument that's a bit confusing.
* We no longer use stringified numbers as keys.
* When you run elmo, you don't need a separate file for the source sentences.
It's reasonably clear that sentences are encoded in UTF when used as names for datasets (see http://docs.h5py.org/en/latest/high/group.html?highlight=utf).
If for some reason we don't want this, I plan to store the sentence text as an attribute on the dataset.
> Use the sentence as the key in elmo command.

- allennlp/commands/elmo.py
- tests/commands/elmo_test.py
Previously duplicate sentences would cause an error when running the ELMo command.  This change outputs a warning and continues instead.
> Warn on duplicate sentences

- scripts/wikitables_eval.py
This script takes a wikitables example file, predicts logical forms for all of the instances, then calls out to sempre to evaluate the logical forms for denotation accuracy.  We call to sempre using a jar built from [this repo](https://github.com/allenai/wikitables-executor).  I put the jar on s3, and download it in the script, so this script should be able to just run.
This script depends on the updates in #794 to run (because that PR adds logical form output to the parser), but other than that it's standalone and can be reviewed now.
> Wikitables evaluation script

- allennlp/data/fields/array_field.py
- tests/data/fields/array_field_test.py
`ListField[ArrayField]` pads the list with empty `ArrayField`s. But it uses the default padding value=0 and can lead to the model incorrectly assuming the padded arrays to be filled. This change modifies the `empty_field` to also pass the `padding_value` to the padded `ArrayField` object.
Thoughts ?
> Handle padding in ListField[ArrayField]

- scripts/ai2-internal/run_with_beaker.py
Adding each command is a bit of a pain, but it provides excellent usage strings for our users.  Unfortunately `run_with_beaker.py` needs to be modified when Beaker changes it's commands under `beaker experiment run`.
> Pass through Beaker commands in run_with_beaker.py.

- scripts/ai2-internal/run_with_beaker.py
@schmmd, these are some fixes from me actually using this script today.
I would prefer to have the environment variables in the script; did you ask @nikett, @tusharkhot, or anyone else whether they have a preference here?  Yes, it makes the "experiment" page really ugly, but that's not the page you look at for an allennlp experiment, and it seems fine on the "task" page.
The description should be optional, I think.
And the `--detach` flag doesn't really do anything in beaker at this point, and will probably be removed (per some discussion in the `beaker-users` slack channel).
> Some minor flag fixes for the beaker script

- allennlp/data/dataset_readers/nlvr.py
- allennlp/data/semparse/type_declarations/nlvr_type_declaration.py
- allennlp/data/semparse/worlds/nlvr_world.py
- allennlp/data/semparse/worlds/world.py
- allennlp/models/encoder_decoders/nlvr_semantic_parser.py
- tests/data/dataset_readers/nlvr_test.py
- tests/data/semparse/worlds/nlvr_world_test.py
- tests/data/semparse/worlds/world_test.py
This PR includes several changes to the NLVR language:
1) I removed lambda functions from the language. This made the box filters less expressive, but the output space is more restricted. The reduced expressivity is not really a problem though. I tried to annotate a random set of 25 sentences, of which I could not annotate only 2 due to the lack of lambdas.
2) I converted each function that had placeholder types into multiple functions where the types of the arguments are unique. This increased the number of terminals, but the grammar now disallows unintended argument types that placeholders earlier allowed.
3) Related to the above change, I removed the attribute functions: "count", "color" and "shape", and pulled them into the assertion and filtering functions. This again increased the …
> NLVR language fixes

- allennlp/common/__init__.py
- allennlp/data/dataset_readers/conll2003.py
- allennlp/data/dataset_readers/coreference_resolution/conll.py
- allennlp/data/dataset_readers/dataset_reader.py
- allennlp/data/dataset_readers/dataset_utils/ontonotes.py
- allennlp/data/dataset_readers/penn_tree_bank.py
- allennlp/data/dataset_readers/reading_comprehension/squad.py
- allennlp/data/dataset_readers/reading_comprehension/triviaqa.py
- allennlp/data/dataset_readers/seq2seq.py
- allennlp/data/dataset_readers/sequence_tagging.py
- allennlp/data/dataset_readers/snli.py
Fixes #814.
Having `tqdm` in the `DatasetReader` subclasses doesn't play nicely with `lazy=True`, because you get a `tqdm` line for the dataset reader in every batch during training.  The better place to have `tqdm` is in the base class, when converting the generator into a list.  This PR removes the `tqdm` calls from the subclasses and adds one to the base class.
> Fix tqdm behavior around lazy datasets

- allennlp/models/crf_tagger.py
- allennlp/modules/conditional_random_field.py
- tests/modules/conditional_random_field_test.py
not 100% sure this is the best way to implement it, lmk what you think.
```
echo '{"sentence": "Sailing around the New York Harbor can be as educating as it is soothing."}' > examples.jsonl && python -m allennlp.run predict     https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2017.11.15.tar.gz     examples.jsonl
```
results in 
```
"tags": ["O", "O", "O", "B-LOC", "I-MISC", "L-MISC", "O", "O", "O", "O", "O", "O", "O", "O", "O"]
```
but if you specify BIOUL constraints
```
echo '{"sentence": "Sailing around the New York Harbor can be as educating as it is soothing."}' > examples.jsonl && python -m allennlp.run predict     https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2017.11.15.tar.gz     examples.jsonl -o '{"model":{"constraint_type":"BIOUL"}}'
```
you get
``` …
```
> add constrained decoding for CRFs

- allennlp/modules/text_field_embedders/basic_text_field_embedder.py
- allennlp/modules/text_field_embedders/text_field_embedder.py
- tests/modules/text_field_embedders/basic_text_field_embedder_test.py
Fixes #820.
We already require a `num_wrapping_dims` argument to `get_text_field_mask`.  It turns out we need a similar argument to the `BasicTextFieldEmbedder` also, so that CNNs work correctly (an `Embedding` is fine on higher-order input, which is probably why we didn't see this earlier).  The test I added fails before the addition of the `num_wrapping_dims` argument.
> Make BasicTextFieldEmbedder handle higher-order inputs

- tests/data/dataset_readers/dataset_utils/ontonotes_test.py
`Ontonotes.dataset_path_iterator` uses `os.walk` to iterate over files. `os.walk` makes no guarantees w.r.t the order of returned files (officially, [they're returned in arbitrary order](https://docs.python.org/3/library/os.html#os.listdir)). 
The test was failing on one of the machines I ran it on, so I edited the it to compare lengths and set equality.
> Fix OntoNotes dataset path iterator test by using set equality

- allennlp/commands/__init__.py
- allennlp/commands/fine_tune.py
- allennlp/commands/train.py
- allennlp/common/__init__.py
- allennlp/common/tqdm.py
- allennlp/models/__init__.py
- doc/api/allennlp.commands.fine_tune.rst
- doc/api/allennlp.commands.rst
- doc/api/allennlp.commands.train.rst
- tests/commands/fine_tune_test.py
Fixes #879.
I'm sure that we'll want to add more to this eventually, but this _should_ be the minimum functionality needed for continuing training a model on a new dataset.
I based this off of the `train` command, and I cleaned up some of what was there as I went, so there are also some minor changes to existing files.
@danyaljj, FYI.
I'm "requesting a review" now.  I'm working on the weekend because my family is gone for a few hours this morning, and I wanted to get this done.  I sometimes time-shift my hours a bit so that I can help with family stuff during the week.  _Please_ don't anyone feel pressure to work on the weekends just because I am doing this now.
> Add a fine-tune command for continuing training on a new dataset

- allennlp/nn/util.py
- tests/nn/util_test.py
> Fix masked_log_softmax when the entire vector is masked

- allennlp/data/semparse/worlds/nlvr_world.py
- scripts/get_nlvr_logical_forms.py
- tests/data/semparse/worlds/nlvr_world_test.py
This PR fixes two things:
1) The value of the `y_pos` attribute in NLVR increases from top to bottom of each block in the figure. That means, for an object to be at the top, its `y_pos` needs to be closer to 0. The way I originally implemented vertical spatial relations (above, below, top, bottom etc.) got this backwards. I fixed it in this PR.
2) Object names (and their hashes) originally did not include the identities of the boxes they belonged to. This caused the executor to not distinguish between objects that are the same shape, color and size, at the same x and y coordinates in different boxes.  I added box ids to object names now.
> Fix bugs related to y-coordinates and object hashes

- demo/src/components/TeComponent.js
- tutorials/misc/migrating-to-0.4.0.md
my plan is to link to this from the release notes.
let me know if I missed anything or explained anything poorly.
> Migrating to 0.4.0

- allennlp/data/dataset_readers/penn_tree_bank.py
- allennlp/models/constituency_parser.py
- allennlp/service/predictors/constituency_parser.py
- allennlp/service/server_flask.py
- demo/src/App.js
- demo/src/components/ConstituencyParserComponent.js
- demo/src/components/Header.js
- tests/data/dataset_readers/penn_tree_bank_reader_test.py
- tests/models/constituency_parser_test.py
- tests/service/predictors/constituency_parser_test.py
- Adds a Hierplane demo for the constituency parser.
- Weaves a new bit of metadata through the model so that we don't get unknown words in the demo (and actually, simplified things quite a bit)
- I haven't added the model yet, because it's not good enough and I still need to figure out why. But merging this doesn't depend on that, so I figured it would be best to split it up here.
The demo looks like this:
(We've hit maximum text wrapping capacity on a mac on the demo - we're going to need a "Select a demo model" page pretty soon.... [it could look like this but for deep learning models](https://bl.ocks.org/))
> Constituency js

- allennlp/data/dataset_readers/penn_tree_bank.py
- allennlp/models/constituency_parser.py
- allennlp/training/metrics/categorical_accuracy.py
- allennlp/training/metrics/f1_measure.py
- tests/data/dataset_readers/penn_tree_bank_reader_test.py
So for the parser, I had approximately 100 F1 metrics, and changing this line in the metric (without actually removing the 100 metrics, which I subsequently did also in this PR because it was super small) pushed the speed from 7.4 iterations/sec to 12/sec. I think i'll switch to accuracy in the future, but this is a general optimisation and a reminder not to do topk unless you definitely need to!
> speed up metrics

- allennlp/models/encoder_decoders/wikitables_semantic_parser.py
Noticed this since the linking scores and similarity scores were the same. This should improve the baseline by around 3 percent since linking features will now be used.
> Fixed bug where linking scores weren't properly updated with features

- allennlp/training/metrics/evalb_bracketing_scorer.py
- tests/training/metrics/evalb_bracketing_scorer_test.py
I was just averaging the metrics across multiple calls to EVALB, which was wrong. The correct version is much simpler 👍
> fix online metric calculation for EVALB

- allennlp/commands/__init__.py
- allennlp/commands/evaluate.py
- allennlp/commands/fine_tune.py
- allennlp/commands/predict.py
- allennlp/commands/train.py
- tests/commands/evaluate_test.py
- tests/commands/main_test.py
- tests/commands/train_test.py
Fixes #961.  Now any command will be able to include submodules, and new commands will get this automatically.  The elmo command doesn't really need this, but all of the others do.
> Move --include-packages flag up to top level

- allennlp/data/vocabulary.py
- tests/data/vocabulary_test.py
There were 2 problems here:
1) `max_vocab_size = defaultdict(lambda: max_vocab_size)`
default value for the new dictionary becomes `defaultdict` itself, and not the int as supposed
2) `max_vocab = max_vocab_size.get(namespace)`
probably it supposed to be `max_vocab_size[namespace]` instead (since it also adds a new element to the `defaultdict`)
Fixes #964.
> Fix max_vocab_size bug (#964)

- allennlp/models/encoder_decoders/nlvr_semantic_parser.py
- allennlp/nn/decoding/expected_risk_minimization.py
- tests/fixtures/encoder_decoder/nlvr_semantic_parser/experiment.json
- tests/models/encoder_decoders/nlvr_semantic_parser_test.py
I see that penalizing non-agenda actions makes the model overfit less. The accuracy on a small validation set I've been experimenting with went down after we removed currying, but the coverage went up. After I made this change, we're back to having the same accuracy as we did with currying (63%.. not great) but with higher coverage, now close to 80%.
In addition to adding the option of penalizing non-agenda actions, I also moved the code for computing model scores and checklists into `take_step`, as recommended by @matt-gardner in the review of #926.
> Penalize non agenda actions

- allennlp/data/semparse/worlds/nlvr_world.py
- allennlp/models/encoder_decoders/nlvr_semantic_parser.py
- tests/fixtures/encoder_decoder/nlvr_semantic_parser/experiment.json
- tests/models/encoder_decoders/nlvr_semantic_parser_test.py
The model used to assign uniform probabilities to all allowed in-agenda actions. This PR makes this parameterized by changing the output projection layer to project the concatenation of the current hidden state, attended encoder outputs, and now also the checklist difference. Doing this eliminates the `checklist_selection_weight` hyperparameter, which was the mixing weight for in-agenda probabilities and model assigned probabilities. Also, this makes our plans for eventually using linking scores in the checklist easier.
> Parameterized selection of in-agenda actions

- allennlp/data/semparse/worlds/wikitables_world.py
- tests/data/semparse/worlds/wikitables_world_test.py
- training_config/wikitables_parser.json
This is actually a very small change, but it depends on #947.  @rajasagashe, this should fix the key errors we were seeing.  It also has an updated training config, with optimizer parameters that match those in the original paper.  I had more luck with using a learning rate of 0.01, though - the 0.1 run I did crashed with an error I'm still looking into.
> Fix key error, update training configuration

- allennlp/service/predictors/wikitables_parser.py
Another option would be to not pass the tokenized question, so that way the dataset reader will lowercase it here:
https://github.com/allenai/allennlp/blob/401e8ad0692cc941f534191490c8ec4f1916d1bf/allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py#L233
Then the tokenized question could be added into `table_info` here:
https://github.com/allenai/allennlp/blob/401e8ad0692cc941f534191490c8ec4f1916d1bf/allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py#L240
> Bug: Question should be lowercased in the demo.

- tutorials/getting_started/creating_a_model.md
> Fix simple tagger link in creating a model tutorial

- allennlp/common/testing/model_test_case.py
The assert gave a really rubbish error in the case that the gradient was `None`, so this will improve that.
> better error for gradient check

- allennlp/data/fields/array_field.py
- allennlp/data/fields/index_field.py
- allennlp/data/fields/label_field.py
- allennlp/data/fields/list_field.py
- allennlp/data/fields/metadata_field.py
- allennlp/data/fields/sequence_label_field.py
- allennlp/data/fields/span_field.py
- allennlp/data/fields/text_field.py
- allennlp/data/instance.py
- tests/data/fields/array_field_test.py
- tests/data/fields/index_field_test.py
- tests/data/fields/label_field_test.py
- tests/data/fields/list_field_test.py
- tests/data/fields/sequence_label_field_test.py
- tests/data/fields/span_field_test.py
- tests/data/fields/text_field_test.py
Here's an initial pass at making it easier to see what's happening inside the data pieces. I'm sure there's many things we can add/improve but already I can see that this would help me check things when building a model.
SNLI:
```
>>> print(instance)
Instance with fields:
premise: TextField of length 12 with text:
[A, person, on, a, horse, jumps, over, a, broken, down, airplane, .]
and TokenIndexers : {'tokens': 'SingleIdTokenIndexer'}
hypothesis: TextField of length 10 with text:
[A, person, is, training, his, horse, for, a, competition, .]
and TokenIndexers : {'tokens': 'SingleIdTokenIndexer'}
label: LabelField with label: neutral in namespace labels
```
Squad:
```
>>> print(instance)
Instance with fields:
passage: TextField with text:
[Architecturally, ,, the, school, has, a, Catholic, …
```
> add an initial string representation to fields and instances

- allennlp/data/dataset_readers/__init__.py
- allennlp/data/dataset_readers/stanford_sentiment_tree_bank.py
- doc/api/allennlp.data.dataset_readers.rst
- doc/api/allennlp.data.dataset_readers.stanford_sentiment_tree_bank.rst
- tests/data/dataset_readers/stanford_sentiment_tree_bank_test.py
- tests/fixtures/data/sst.txt
This PR adds a reader for the StanfordSentimentTreebank tokens and labels, for 5/3/2-class text classification. It also optionally lets you pick whether or not to make examples from labeled subtrees, or whether to just use the sentences.
> Add Stanford Sentiment Treebank dataset reader

- allennlp/data/fields/__init__.py
- allennlp/data/fields/multilabel_field.py
- doc/api/allennlp.data.fields.rst
- tests/data/fields/multilabel_field_test.py
Adding a multilabel field which is useful for multi-label multi-class classification. 
Notes:
- I don't like how I am reading the vocabulary size, but I didn't find a better way. I am open to better suggestions. 
- The `as_tensor` function returns a dense vector of zeros and ones. It would have been more efficient to work with a list of indices instead, but that's not supported by torch.nn.BCEWithLogitsLoss
> Add a multilabel field

- allennlp/modules/token_embedders/embedding.py
- tests/modules/token_embedders/embedding_test.py
Applying `strip()` on the line leads to incorrect reading of certain words in the `glove.840B.300d` file. More precisely, it deletes the word (interpreting it as whitespace), considers the first dimension of the embedding as the word, and consequently finds only 299 dimensions. Sample log message 
`2018-03-30 15:06:35,244 - WARNING - allennlp.modules.token_embedders.embedding - Found line with wrong number of dimensions (expected 300, was 299): b'\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0 0.59759 -0.64012 0.32797 -0.40237 -0.96606 0.059478 -0.21576 0.16216 -0.32797 -1.6323 0.68522 -0.073292 0.21555 1.3283 -0.031215 -0.53429 0.49431 -1.1694 0.24104 -0.33426 0.58275 0.38341 0.55435 0.48166 -0.52648 0.064375 -0.8332 0.36364 0.41019 -0.72814 0.37718 0.12334 0.65675 …
> Reading glove embeddings: strip() --> rstrip()

- allennlp/modules/__init__.py
- allennlp/modules/elmo.py
- allennlp/modules/token_embedders/elmo_token_embedder.py
- tests/modules/token_embedders/elmo_token_embedder_test.py
@matt-peters FYI. @rajasagashe's experiments with the WikiTables parser found that a projection of the ELMo representations was significantly better than just using dropout.  In order to handle the projection cleanly in AllenNLP, it has to be done inside the `ElmoTokenEmbedder`.  This PR adds that.
> Adding an optional projection layer to ElmoTokenEmbedder

- allennlp/common/testing/model_test_case.py
- allennlp/data/dataset_readers/wikitables/wikitables_dataset_reader.py
- allennlp/data/dataset_readers/wikitables/wikitables_preprocessed_dataset_reader.py
- allennlp/data/fields/knowledge_graph_field.py
- allennlp/models/encoder_decoders/wikitables/wikitables_semantic_parser.py
- tests/fixtures/encoder_decoder/wikitables_semantic_parser/experiment-elmo-no-features.json
- tests/fixtures/encoder_decoder/wikitables_semantic_parser/experiment-mixture.json
- tests/models/encoder_decoders/wikitables/wikitables_semantic_parser_test.py
The main changes are elmo projection, cosine similarity, and table truncation. I replaced dividing by embedding dim with cosine similarity since it performs around 2 percent better.
> Ability to Run Elmo on Wikitables

- allennlp/nn/decoding/__init__.py
- allennlp/nn/decoding/beam_search.py
- allennlp/nn/decoding/decoder_state.py
- allennlp/nn/decoding/decoder_step.py
- allennlp/nn/decoding/decoder_trainers/__init__.py
- allennlp/nn/decoding/decoder_trainers/decoder_trainer.py
- allennlp/nn/decoding/decoder_trainers/expected_risk_minimization.py
- allennlp/nn/decoding/decoder_trainers/maximum_marginal_likelihood.py
- allennlp/nn/decoding/grammar_state.py
- allennlp/nn/decoding/rnn_state.py
- doc/api/allennlp.nn.decoding.decoder_trainers.rst
- doc/api/allennlp.nn.decoding.rst
- doc/api/allennlp.nn.rst
- tests/nn/decoding/beam_search_test.py
- tests/nn/decoding/decoder_trainers/expected_risk_minimization_test.py
- tests/nn/decoding/decoder_trainers/maximum_marginal_likelihood_test.py
- tests/nn/decoding/grammar_state_test.py
- tests/nn/decoding/simple_transition_system.py
This PR adds the transition-based decoding framework from the `wikitables` branch.  All of the code here has already been reviewed, so this doesn't need a thorough look at the code (unless you _want_ to go over it in detail!).  What I'm looking for in a review at this point is to make sure that the high-level structure of this module makes sense, and that the documentation is sufficient to know what each piece does and when it should be used.
It might be easiest to browse the code in my fork of the repo, found here: https://github.com/matt-gardner/allennlp/tree/decoding/allennlp/nn/decoding.  Start by looking at the module docstring in `__init__.py`, then look over the class structure, and class docstrings.  If anything isn't clear or could use some more documentation, let me know!
> Adding the decoding framework from the wikitables branch

- allennlp/service/server_flask.py
Several times I've run into an issue where I get a really weird error message about some required JSON field being missing, where there was actually a `KeyError` deep in my model code that was being caught at this point and re-branded incorrectly, hiding the original stack trace.  I don't think trying to catch the `KeyError` here is actually useful.
> Remove the KeyError catch block in the server

- scripts/cache_models.py
Importing `allennlp` is, unfortunately, slow, and causes several seconds of pointless waiting when `CACHE_MODELS=false`.  This removes the unnecessary wait by moving the imports inside the condition where `CACHE_MODELS=true`.
> Move imports to inside of CACHE_MODELS=true condition

- allennlp/models/semantic_parsing/wikitables/wikitables_decoder_state.py
- allennlp/models/semantic_parsing/wikitables/wikitables_decoder_step.py
- tests/models/semantic_parsing/wikitables/wikitables_decoder_step_test.py
I also added a convenience method for printing out the score and action sequence in a WikiTablesDecoderState, which is helpful for examining what's going on during decoding / beam search.
> Fix state scores in WikiTablesDecoderStep

- Dockerfile
- scripts/build_demo.py
- scripts/check_docs.py
1. Minor tweaks to the order of copies in the dockerfile.
2. Redirecting stderr as well as stdout in the `EVALB` command.
3. Hiding building the demo behind an argument and a script, because it is slow.
It's possible that our tests rely on the demo; CI will tell us that for sure.  If so, I'll try to find a way to make the tests not rely on the demo...
@schmmd, this means that something has to change in the demo build, in the same place where `CACHE_MODELS=true` is specified, wherever that is.
> Streamlining the docker build a little bit

- allennlp/data/fields/knowledge_graph_field.py
- allennlp/models/semantic_parsing/wikitables/wikitables_semantic_parser.py
- tests/fixtures/semantic_parsing/wikitables/experiment-elmo-no-features.json
Previously, if you wanted to ablate the linking features, we would always try one of Rajas's experiments to replace the linking features.  This makes the replacement optional, so you can actually ablate the linking features.
> Allow ablation where linking features are removed

- allennlp/common/tqdm.py
This was causing serious grief in Beaker - if an exception was raised inside any code wrapped in a tqdm progress bar, it would hang after raising the exception. @schmmd we might need to release again after this, so that people can upgrade.
> hack to stop tqdm hanging

- allennlp/commands/elmo.py
just ran `allennlp elmo --help` and updated the output.
> Update ELMo command help docstring

- allennlp/custom_extensions/make.sh
Needed to do this to get the custom highway LSTM working on a Tesla V100, otherwise during backprop it would fail and emit the error `CUDA Error: no kernel image is available for execution on the device`.
> Add compute model number to Compile custom LSTM for Tesla V100

- allennlp/models/semantic_parsing/nlvr/nlvr_decoder_step.py
- allennlp/models/semantic_parsing/wikitables/wikitables_decoder_step.py
Summary of changes:
1) Made the output projection layer the same in both mml and erm parsers for both nlvr and wikitables parsers
2) The checklist balance in nlvr (and unlinked checklist balance in wikitables) is now used to select appropriate action embeddings, the sum of which is added to predicted action embedding.
3) There are now learned scalar parameters that regularize the addition to predicted embedding (in nlvr and wikitables) and action logits (in wikitables).
> Changed how checklist balance is used in action prediction

- setup.py
Fixes https://github.com/allenai/allennlp/commit/70862e09eb9546f849334e4df4893d7597c9f1aa#commitcomment-28975524
Surprised that pylint didn't pick this up, but `python setup.py install` and `python setup.py test` now work on this branch. Sorry for the carelessness!
cc: @jpowerwa
> Add missing import to setup.py

- allennlp/data/dataset_readers/snli.py
- allennlp/models/decomposable_attention.py
- allennlp/service/predictors/decomposable_attention.py
- demo/src/components/TeComponent.js
> Add the attention visualization to the textual entailment demo

- tests/commands/test_install_test.py
I realized that it's a pretty strong assumption for this function to look for `setup.py` and `license` --- all we're really looking for is the `tests` directory. I also added another assert that the test file exists, just as a sanity check that we've got the right tests directory.
> Tweak TestInstall._get_project_root()

- MANIFEST.in
The custom extensions were previously not being packaged, since they didn't end in `.py`. I just added all files in the `allennlp` module, removing `__pycache__`s.
> Add custom extensions to distribution and install

- allennlp/modules/highway.py
- tests/modules/highway_test.py
As per #1211, now the Highway implementation won't require the `TimeDistributed` wrapper to work with n-dimensional input.
I've glanced around the lib and saw that `FeedForward` also has the 2-d input assumption, as well as some other layers (at least in the docs). Since `nn.Linear` accepts n-d input, I believe this can be relaxed. I've used `FeedForward` on `BxTxD` data unknowingly, and everything worked fine.
Fixes #1211.
> Replace slicing with chunk along the last dim

- demo/src/components/ConstituencyParserComponent.js
Updates the constituency parser demo to reference *Extending a Parser to Distant Domains Using a Few Dozen Partially Annotated Examples* which is now on arXiv http://arxiv.org/abs/1805.06556
> Constituency Parser Demo Reference Update

- tutorials/how_to/elmo.md
first code block was missing a `}`, and i took the opportunity to make the spacing for all of them uniform.
> Add missing close brace, standardize indentation in ELMo howto

- allennlp/commands/train.py
- tests/commands/train_test.py
> make it OK if serialization_dir exists but is empty

- allennlp/service/server_flask.py
- allennlp/service/server_simple.py
Since gevent 1.0a1 was released in 2011, wsgi is just an alias for pywsgi.
In version 1.3 wsgi is completely removed, causing allennlp to break.
For more info check  http://www.gevent.org/api/gevent.wsgi.html
Test plan:
run scripts/verify.py on trunk, all test pass.
> Migrate gevent's wsgi to pywsgi

- allennlp/tests/training/trainer_test.py
- allennlp/training/trainer.py
Fixes https://github.com/allenai/allennlp/issues/1267
> In Trainer, require "patience" to be a positive integer or None (meaning "no early stopping"). Set patience=None by default.

- codecov.yml
Our coverage jumped up from 92% to 95% after the tests were moved under `allennlp`...
> Ignore tests in coverage metrics

- tutorials/README.md
The installation tutorial was removed in https://github.com/allenai/allennlp/pull/1261. This PR changes the link on the tutorials site to the `#installation` section of the project `README.md.
> Fix link to installation instructions

- tutorials/how_to/visualizing_model_internals.md
The `()` and `[]` were flipped so this link didn't work.
> Fix link to demo.allennlp.org page

- allennlp/common/testing/test_case.py
- pytest.ini
Fixes #1350.  Well, it kind of fixes it.  I'd prefer to have the logs just interleaved with stderr, like they used to be, because this way it makes it pretty hard to follow some things...  If anyone knows how to get back to that without just pinning to `pytest==3.2`, I'd be happy to hear it.  (I'm also maybe happy to pin to 3.2 instead of this...)
> Format pytest logging correctly

- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
- training_config/wikitables_parser.json
There are a few tokens that I needed to be added to the wikitables parser vocabulary, and I couldn't figure out a cleaner way to do it than to just add them directly to the vocab in the configuration.  Ideally I'd want the model code to specify this, not the configuration file, but I don't know how to do that in a nice way.
This seems like something people might want to do in other circumstances, too.
> Add ability to add tokens to vocabulary namespaces

- scripts/ai2-internal/run_with_beaker.py
Fixes https://github.com/allenai/allennlp/issues/1345.
I ran an experiment with the following command:
```
./scripts/ai2-internal/run_with_beaker.py training_config/bidaf.json --memory 16G --cpu 1.0 --gpu-count 1 --name beaker-test-1epoch
```
You can see it at: http://beaker.allenai.org/ex/ex_bksl8hrscclq
> Make optional args actually optional.

- allennlp/common/configuration.py
- allennlp/service/config_explorer.html
- allennlp/service/config_explorer.py
stupid bug, not sure how I didn't catch it before. also removed a log statement that should have been taken out
> fix bug where json_annotation returns a garbage annotation for Optional types

- allennlp/predictors/wikitables_parser.py
- allennlp/tests/predictors/wikitables_parser_test.py
`predict_json` was overridden in the predictor to add an `answer` field to the outputs. This was not done with `predict_batch_json` though, causing the answer to not be produced when the inputs are batched. This PR fixes it.
> Output answers in wikitables predictor when inputs are batched

- allennlp/commands/elmo.py
- allennlp/tests/commands/elmo_test.py
- tutorials/how_to/elmo.md
Fixes #1396 Fixes #1257 
- Replaces sentence indexes with integer line indices
- Doesn't ignore duplicate lines in the dataset
- raises an error if your input file contains blank lines, rather than silently creating a dataset which doesn't align with the input file
> fix elmo command to use line indices and disallow empty lines

- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
- Change expected key in docstring from 'vocabulary_directory' to 'directory_path' ([link](https://allenai.github.io/allennlp-docs/api/allennlp.data.vocabulary.html#allennlp.data.vocabulary.Vocabulary.from_params))
> Fix a minor typo in docstring causing wrong api docs of vocabulary config

- allennlp/models/model.py
- allennlp/training/trainer.py
tqdm currently doesn't handle long descriptions very gracefully (image below)
This PR makes the tqdm description ignore metrics with a name that begins with `_`.
> Make tqdm description ignore metrics starting with _

- allennlp/training/trainer.py
Explicitly detach scalars by calling `item` before logging to tensorboard.
> Call `item` before logging to tensorboard

- allennlp/commands/fine_tune.py
- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
Add full support for configurable vocabulary extension
1. Add general configurable support for vocabulary extension (essential for transfer learning scenarios, fine tuning).
2. Make fine-tune command extend the saved-model-vocabulary with current dataset instances by default rather than only banking on saved-model-vocabulary.
3. Add extensive test cases for new API. Check test-cases for more example usages.
Api now allows toggle `extend` in vocabulary params to configure whether to use `directory_path` for extending vocabulary, or use it alone and ignore the the dataset. The current API only allows either to load vocabulary from directory or load from dataset instances. However, vocabulary extension is important for undertaking any kind of transfer learning, fine tuning etc.
**Example …
> Add support for configurable vocabulary extension

- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
Continuation of (#1416) missed edge case.
@joelgrus I found an unhandled edgecase in `extend` function. If one tries to add new tokens for existing namespace it must always use same padding setting or err. Case A and B do give error, but C does not.
```python
vocab = Vocabulary(non_padded_namespaces=[])
vocab.add_token_to_namespace("a", namespace="tokens")
```
So in A, B, C: asking for "tokens" to be padded should give error:
A. Following gives error appropriately:
```python
vocab.extend(counter={"tokens": {"a":100}}, non_padded_namespaces=["tokens"])
```
B. Following does aswell:
```python
text_field = TextField([Token("a")], {"tokens": SingleIdTokenIndexer("tokens")})
vocab.extend_from_instances(Params({"non_padded_namespaces": ["tokens"]}),
Batch([Instance({"text": text_field})]) )
``` …
> Fix an edge case for incompatible vocabulary extension.

- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
the code to add `Vocabulary.extend_from_instances` introduced a lot of functions that no one other than a `Vocabulary` instance (or its tests) needs to call. this PR eliminates them or makes them private.
FYI @HarshTrivedi
> eliminate or make private most of the new Vocabulary methods

- allennlp/data/iterators/bucket_iterator.py
- allennlp/tests/data/iterators/bucket_iterator_test.py
Fix bug introduced in #1438 when resolving merge conflicts
> Make `BucketIterator` respect maximum_samples_per_batch

- tutorials/notebooks/embedding_tokens.ipynb
Fix a typo in embedding_tokens notebook : The vocabulary is `token_ids` and not `tokens_ids`.
> Fix a typo in embedding_tokens notebook.

- allennlp/commands/train.py
- allennlp/common/testing/model_test_case.py
- allennlp/data/__init__.py
- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
I think this is a cleaner solution, it allows you to override with a custom vocabulary without having to think of the usual vocabulary as a "type" of vocabulary
@matt-peters this means your code will need to use `@Vocabulary.register(...)`
> remove RegistrableVocabulary

- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
the constructor allows either an int or a Dict[str, int], but from_params assumed an int, making it impossible to configure an experiment the other way
> fix Vocabulary.from_params to accept a dict for max_vocab_size

- allennlp/commands/fine_tune.py
- allennlp/commands/train.py
- allennlp/common/util.py
- allennlp/tests/common/test_util.py
Fix issue in no-grad parameters logging as mentioned by @rulai-huajunzeng in (#1427).
If parameters were already set `requires_grad=False` not through no through nograd regex but other means then they were logged as Tunable instead of Frozen. This pr fixes that.
I have made the headings capitalized. They are more distinguishable this way amidst a long list of parameters.
> Fix logging of no-grad parameters.

- allennlp/modules/attention/bilinear_attention.py
- allennlp/modules/attention/linear_attention.py
- allennlp/modules/matrix_attention/bilinear_matrix_attention.py
- allennlp/modules/matrix_attention/linear_matrix_attention.py
- allennlp/modules/seq2vec_encoders/cnn_encoder.py
- allennlp/modules/similarity_functions/bilinear.py
- allennlp/modules/similarity_functions/linear.py
fixes #1477 
basically, when `Activation.by_name` was called as a default parameter, it was run at [python] module load time, resulting in a bunch of "hey, Activation.from_params got called" log lines before the training code even started running.
using `None` as a default value and moving the call inside the constructor makes it so the logging only happens if the corresponding [pytorch] module actually gets instantiated
(I also considered instantiating the functions directly e.g.
```
activation: Activation = lambda x: x
```
but the thing is that Activation isn't the "real" type of activation functions (it's just a construct to allow from_params), so that doesn't actually typecheck.
> instantiate default activation functions in constructor

- allennlp/common/from_params.py
- allennlp/tests/common/from_params_test.py
fixes #1480
also add a test that would have caught this case.
I'm not entirely thrilled with this solution, but it was cleaner than the other ways I thought of.
> don't call create_kwargs  for a class that has no constructor

- scripts/ai2-internal/run_with_beaker.py
This import got moved in the from params PR but it needs to be inside the path manipulation so that python knows where the repo is when running in a clone.
> Move param import

- allennlp/training/trainer.py
Looking at logs to get results in beaker is so annoying, so this makes it a bit nicer by aligning stuff.
Before:
```
2018-07-13 15:53:07,899 - INFO - allennlp.training.trainer - Training f1-measure-overall : 0.000000    Validation f1-measure-overall : 0.000000
2018-07-13 15:53:07,900 - INFO - allennlp.training.trainer - Training precision-overall : 0.000000    Validation precision-overall : 0.000000
2018-07-13 15:53:07,900 - INFO - allennlp.training.trainer - Training recall-overall : 0.000000    Validation recall-overall : 0.000000
```
After:
```
2018-07-13 15:50:03,244 - INFO - allennlp.training.trainer -                        Training |  Validation
2018-07-13 15:50:03,245 - INFO - allennlp.training.trainer - f1-measure-overall |     0.000  |     0.000
2018-07-13 15:50:03,245 - INFO - …
```
> make tables nice in validation summary

- allennlp/data/dataset_readers/dataset_utils/span_utils.py
- allennlp/tests/data/dataset_readers/dataset_utils/span_utils_test.py
- allennlp/training/metrics/span_based_f1_measure.py
Fixes `SpanBasedF1Measure` to work if the tags don't have conll labels (i.e., the labels are simply `{B, I, O}`).
The only thing that had to be changed was the check to see whether the `active_conll_tag` is not `None`, since `""` is `False`.
> Fix SpanBasedF1Measure for tags without conll labels

- allennlp/training/trainer.py
otherwise it would raise an error in line 505 (expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'other')
> fixing a bug in trainer for histograms

- allennlp/data/dataset_readers/dataset_utils/span_utils.py
- allennlp/tests/data/dataset_readers/dataset_utils/span_utils_test.py
- allennlp/training/metrics/span_based_f1_measure.py
This PR adds IOB1 support to the SpanBasedF1Metric. This was a bit tricky to write, so I'll add some details about my thought process below (might help in review).
So we've got 3 tags (B, I, O), meaning that there are 3^2 = 9 possible transitions between tags. We also have to take into account whether the current conll tag differs from the previous conll tag, bringing up the total to 9 * 2 = 18.
Here are the expected outcomes for each of the cases:
Here's where I believe they're each accounted for in the code (based on which branch they fall into of the main if-elif-else)
In particular, the else could also be written as `bio_tag == "I" and conll_tag == active_conll_tag`, and nothing would change (any and all combinations would still fall into one of these 3 categories).
> Add IOB1 support to SpanBasedF1Metric

- allennlp/training/trainer.py
Before:
```
2018-07-15 11:08:52,306 - Peak CPU memory usage MB: 839.0656
0%|          | 0/369 [00:00<?, ?it/s]2018-07-15 11:08:52,321 - Training
accuracy: 0.6882, prec: 0.6277, rec: 0.3557, f1: 0.4541, loss: 0.5876 ||: 100%|##########| 369/369 [00:37<00:00,  9.75it/s]
2018-07-15 11:09:30,161 - Validating
accuracy: 0.6933, prec: 0.7124, rec: 0.6560, f1: 0.6830, loss: 0.5581 ||: 100%|##########| 21/21 [00:00<00:00, 24.23it/s]
```
After:
```
2018-07-15 11:10:27,697 - Peak CPU memory usage MB: 839.528448
2018-07-15 11:10:27,707 - Training
accuracy: 0.6882, prec: 0.6277, rec: 0.3557, f1: 0.4541, loss: 0.5876 ||: 100%|##########| 369/369 [00:37<00:00,  9.91it/s]
2018-07-15 11:11:04,929 - Validating
accuracy: 0.6933, prec: 0.7124, rec: 0.6560, f1: 0.6830, loss: 0.5581 ||: 100%|##########| 21/21 …
```
> Fix start of tqdm logging in training.

- allennlp/data/fields/knowledge_graph_field.py
- allennlp/data/fields/text_field.py
- allennlp/data/token_indexers/dep_label_indexer.py
- allennlp/data/token_indexers/elmo_indexer.py
- allennlp/data/token_indexers/ner_tag_indexer.py
- allennlp/data/token_indexers/pos_tag_indexer.py
- allennlp/data/token_indexers/single_id_token_indexer.py
- allennlp/data/token_indexers/token_characters_indexer.py
- allennlp/data/token_indexers/token_indexer.py
- allennlp/tests/data/fields/text_field_test.py
- allennlp/tests/data/token_indexers/character_token_indexer_test.py
- allennlp/tests/data/token_indexers/dep_label_indexer_test.py
- allennlp/tests/data/token_indexers/elmo_indexer_test.py
- allennlp/tests/data/token_indexers/ner_tag_indexer_test.py
- allennlp/tests/data/token_indexers/pos_tag_indexer_test.py
- allennlp/tests/modules/elmo_test.py
- scripts/create_elmo_embeddings_from_vocab.py
I replaced
```
TokenIndexer.token_to_indices(self, token: Token, vocabulary: Vocabulary) -> TokenType:
```
with
```
TokenIndexer.tokens_to_indices(self, tokens: List[Token], vocabulary: Vocabulary, index_name: str) -> Dict[str, List[TokenType]]:
```
this addresses two things:
(1) the indices are no longer determined on a per-token basis; instead they can be determined by multiple tokens
(2) a single token indexer can now return multiple sets of indices
initially I was trying to leave things backward compatible, but eventually I decided this would be cleaner. this is a breaking change, but only for people who are writing their own token indexers or fields, which is probably not too many people?
> [for discussion] change token_to_indices -> tokens_to_indices (in preparation for byte pair encoding)

- allennlp/modules/encoder_base.py
- allennlp/tests/modules/encoder_base_test.py
`index_select()` doesn't ensure a contiguous tensor, which can cause a runtime exception since PyTorch RNNs require them to be .
> Ensure Contiguous Hidden State Tensors in Encoders 

- allennlp/commands/dry_run.py
- allennlp/commands/make_vocab.py
- allennlp/commands/train.py
- allennlp/data/dataset.py
- allennlp/data/vocabulary.py
- allennlp/tests/commands/dry_run_test.py
- allennlp/tests/commands/make_vocab_test.py
Usage of `vocab_params` ("vocabulary" key in config.json) in `make-vocab` command is not in sync with usage of `vocab_params` in other commands. IMO, behaviour of `vocab_params` should be similar in both.
In `train` command, `"vocabulary": "directory_path"` is the input for vocabulary construction. If `"extend"=true` is given, then vocabulary would be loaded from "directory_path" and dataset-read-instances will be used to extend it with. Otherwise, vocabulary is loaded from "directory_path" and is used as it is. 
```
"vocabulary": {
"directory_path": "vocabulary_dir_path"
"extend": true # false
}
```
In both cases, the output vocabulary is dumped in `serialization_dir/vocabulary`.
However, in `make-vocab`, `"vocabulary": "directory_path"` is taken as the **output path**, where vocabulary …
> Make usage of make-vocab, dry-run consistent with train and allow 'extend' to be used by both

- allennlp/commands/train.py
- allennlp/common/params.py
- allennlp/tests/common/params_test.py
This PR is in reference to (#1476). Besides that use case: I am generating bunch of experiment configs based on certain combinations of settings I want to explore. Having consistent ordering of keys generated across these output config files would be good for human parsing. Eg. Seeing `vocabulary` key to top, `train_data_path` at bottom and `validation_data_path` somewhere in middle seems quite off place . So this PR adds `to_file` counter part of `from_file` in Params, which saves the json in according to passed or default partial preference orderings. 
The default orderings are as: `dataset_reader > iterator > model > train_data_path > validation_data_path > test_data_path > trainer > vocabulary` and `type` key will always be on the top of its companions. This is the usual order in …
> Add to_file method in Params and default preference ordering.

- allennlp/models/crf_tagger.py
- allennlp/tests/training/optimizer_test.py
- allennlp/training/optimizers.py
- tutorials/getting_started/using_as_a_library_pt1.md
Adds:
- DenseSparseAdam - this is just the dense and sparse versions of adam in pytorch combined, which makes it a lot less annoying to handle. I'll probably submit a PR to Pytorch with this at somepoint. I didn't modify the source at all apart from docstrings, so it needed a lot of `pylint: ignore`s.
- Ability to add a `Feedforward` layer after the encoder part in the CRF model (I needed this to reproduce some fine-grained NER results).
> DenseSparseAdam + CRF Feedforward layer

- allennlp/models/model.py
It's quite confusing why a key from model.forward got ignored without this warning.
> Show warning before ignoring key with unseparable batches from forward.

- scripts/check_links.py
- scripts/verify.py
This PR adds a script to report broken links in all markdowns in the project.
```
time python scripts/verify.py --checks check-links
UnReachable Links:
Verifying with ['check-links']
LinksValidity (check):
UnReachable Links:
0.
Source: /Users/harshtrivedi/allennlp/tutorials/getting_started/using_as_a_library_pt2.md
Name: on GitHub
Link: https://github.com/allenai/allennlp-as-a-library-example/tree/0.5.1
1.
Source: /Users/harshtrivedi/allennlp/tutorials/getting_started/using_as_a_library_pt2.md
Name: `static_html`
Link: https://github.com/allenai/allennlp-as-a-library-example/tree/0.5.1/static_html
2.
Source: /Users/harshtrivedi/allennlp/tutorials/getting_started/using_as_a_library_pt2.md
Name: its own file
Link: https://github.com/allenai/allennlp-as-a-library-example/blob/0.5.1/static_htm …
```
> Add a scirpt to report broken links in all markdowns.

- Dockerfile.pip
I noticed that some of our master builds were slow.  Investigating the Docker build it looked like the cache was breaking when the commit SHA was specified--which makes sense as it changes for each commit.  This moves these potentially cache-breaking commands to the end so we can re-use more of our images.
> Move cache breaking command to the end.

- allennlp/commands/test_install.py
- allennlp/tests/models/semantic_parsing/wikitables/wikitables_erm_semantic_parser_test.py
- allennlp/tests/models/semantic_parsing/wikitables/wikitables_mml_semantic_parser_test.py
- allennlp/tests/predictors/wikitables_parser_test.py
- allennlp/tests/training/metrics/wikitables_accuracy_test.py
- pytest.ini
* Skip tests that require `java` when running `test-install` as we don't distribute Java via `pip`.
* Exit with the same exit code as `pytest` when running `test-install`.
* Run in the right directory so test fixtures are found.
> WIP: Skip tests that require Java in test-install

- allennlp/common/testing/test_case.py
Fixes https://github.com/allenai/allennlp/issues/1539 and makes AllenNLP less system-dependent.
> Don't use a hard-coded temp directory.

- scripts/verify.py
Checking to make sure `requirements.txt` and `setup.py` are the same no longer makes sense because we've merged `requirements.txt` and `requirements_test.txt`.  We may want to add this check back if we modified it to make sure that `requirements.txt` is a superset of `setup.py`.
> Remove a step from verify.

- allennlp/common/file_utils.py
- allennlp/common/params.py
- allennlp/common/util.py
- requirements.txt
- setup.py
these are small things that prevent allennlp from running on windows, this isn't all the way to getting it to work, but it's a step in that direction:
(1) jsonnet won't pip install on windows right now, so I disabled it in `requirements.txt` if the platform is windows
(2) accordingly, in `params.py` we wrap the `import _jsonnet` in a try-catch block, and if it can't be imported we stub in alternative functions that log a warning and assume the configuration is pure JSON
(3) the `resource` module doesn't exist on Windows, so in `util.py` we import it conditionally, and then we check that it's there before we use it
(4) on unix, urlparse.scheme is an empty string for a file, but on windows it isn't, so I just removed that check in `cached_path`, it should be fine to just check if the file …
> be friendlier to windows users

- Dockerfile
Our instructions for command line usage didn't work in a docker image because we didn't copy `bin/` into the image.
Fixes #1582
> copy bin/ into image

- scripts/check_links.py
I added this detail because the script appeared to be hanging.  The real issue was that `npm install` adds a ton of markdown files.  This is less likely going forward because the demo is no longer contained in this repository.
```
Finding all markdown files in the current directory...
16618 markdown files found
Checking to make sure we can retrieve each web URL...
404: /Users/michaels/hack/allenai/allennlp/demo/node_modules/resolve-dir/README.md
200: /Users/michaels/hack/allenai/allennlp/demo/node_modules/json3/README.md
200: /Users/michaels/hack/allenai/allennlp/demo/node_modules/parse-glob/README.md
200: /Users/michaels/hack/allenai/allennlp/demo/node_modules/babel-register/node_modules/core-js/CHANGELOG.md
200: /Users/michaels/hack/allenai/allennlp/demo/node_modules/babel-runtime/node_m …
```
> Output details when running check-links.

- allennlp/commands/elmo.py
Presently if you run a Beaker job with the `elmo` command, you don't get any progress.
This change somewhat unnecessarily outputs `stdout.txt` and `stderr.txt`--but this allowed maximal re-use of code and doesn't hurt.
> Add file friendly logging for elmo.

- allennlp/__init__.py
@schmmd suggested pinning to an early numpy version, but I'd rather not cause problems with people who might need the later version for some reason.
> filter out numpy 'size changed' warnings

- allennlp/common/util.py
fixes #1597 
(the root cause is that prior to 3.7, pkgutil.walk_packages let you get away with passing in an empty string as the path as a no-op, starting in 3.7 this throws an error, so I changed it to an empty list)
> use empty list for no package not empty string

- allennlp/tests/training/metrics/conll_coref_scores_test.py
- allennlp/training/metrics/conll_coref_scores.py
Fixes #1545.
@nelson-liu, can you run a quick check on this branch, to make sure this actually gives similar scores to pre-pytorch-0.4 in the first epoch of training?  From my test, I'm reasonably sure that this fixes the issue, but I don't have this model already set up to train, so I haven't checked that.
> Fix use of scalar tensors in ConllCorefScores

- allennlp/modules/conditional_random_field.py
- allennlp/tests/modules/conditional_random_field_test.py
This adds IOB1 coding as an allowed constraint for the CRF tagger.
Here's a table of allowed transitions for reference:
> Add IOB1 as allowed CRF constraint

- allennlp/commands/fine_tune.py
Changing this to match the behavior of other commands, like [`train`](https://github.com/allenai/allennlp/blob/82686c10bdca062a7e41825000c39372de354479/allennlp/commands/train.py#L222) and [`make-vocab`](https://github.com/allenai/allennlp/blob/1402b7c02aede1a8f832f64cdfb2e9ef1157faca/allennlp/commands/make_vocab.py#L83). 
This causes `fine-tune` to fail with beaker at the moment.
> Don't error if fine-tune serialization dir already exists

- allennlp/training/trainer.py
This line: https://github.com/allenai/allennlp/blob/6b37dd2be54c0ac178feee2d4428ac9f07d4c5a6/allennlp/training/trainer.py#L763
calculates (or incorrectly formats) the wrong estimated time remaining when [`estimated_time_remaining`](https://github.com/allenai/allennlp/blob/6b37dd2be54c0ac178feee2d4428ac9f07d4c5a6/allennlp/training/trainer.py#L761-L762) is greater than 1 day, since [`time.gmtime`](https://docs.python.org/3/library/time.html#time.gmtime) interprets the number of seconds as time since the epoch, not a time duration.
> Fix calculation of estimated time remaining

- requirements.txt
- setup.py
installing it on python3.7 causes AttributeError: type object 'Callable' has no attribute '_abc_registry'
refers #1457 and python/typing/issues/573.
To reproduce the issue simply install allennlp in a new environment with python3.7 and then run the command `allennlp predict https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz srl-examples.jsonl` given on the demo site https://allennlp.org/models.
It will produce the following error:
```text
Traceback (most recent call last):
File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/martino/kmi/allennlp_playground/venv/lib/python3.7/site-packages/allennlp/run.py", line 15, in <module> …
```
> typing is part of standard library from python3.6 (gives errors on python3.7)

- allennlp/modules/attention/linear_attention.py
- allennlp/modules/matrix_attention/linear_matrix_attention.py
- allennlp/nn/util.py
- allennlp/tests/modules/attention/linear_attention_test.py
- allennlp/tests/modules/matrix_attention/linear_matrix_attention_test.py
- allennlp/tests/nn/util_test.py
This removes the need for the `TriLinearAttention` that Chris implemented for #804, as our `LinearMatrixAttention` now uses memory-efficient operations.
cc @eunsol
> Make LinearAttention and LinearMatrixAttention memory-efficient

- allennlp/training/trainer.py
This adds the learning rate for all parameter groups to the logs for each epoch. This is especially helpful when trying to fine-tune the learning rate.
> Add learning rate to logs

- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
This change allows users to specify max_vocab_size per-namespace in an experiment config without having to provide a max_vocab_size for every namespace.
> make max_vocab_size default to None for a given namespace in Vocabulary._extend

- allennlp/tests/training/learning_rate_schedulers_test.py
- allennlp/training/learning_rate_schedulers.py
- allennlp/training/trainer.py
fixes #1642 
@matt-gardner I took a closer look at the discussion in [here](https://github.com/pytorch/pytorch/pull/6130), and I'm pretty sure this addresses all of those concerns. I think there's still room to add more features to this to match all of the options that tensor flow supports: https://github.com/tensorflow/tensorflow/blob/25c197e02393bd44f50079945409009dd4d434f8/tensorflow/python/training/learning_rate_decay.py#L608.
I choose to replace the registered `cosine` schedule from PyTorch with this one because the default expected behavior is the same. The behavior will differ of course if other options are supplied to the new scheduler, or if the total number of epochs is greater than `T_max`. However, in this scenario the behavior of PyTorch's cosine scheduler is actually …
> Implement cosine with restarts

- allennlp/training/learning_rate_schedulers.py
This is needed due to my last PR: https://github.com/allenai/allennlp/pull/1647, but I forgot to update this. Apologies.
> Fix module docstring for training.learning_rate_schedulers

- allennlp/nn/util.py
Fixes #1039.  This has been bugging me for a while, and seeing it being used in #1625 made me want to just fix it.  This should make any use of this code with large tensors a good deal more efficient, too, as it uses far fewer intermediate operations.
> Make replace_masked_values more efficient by using masked_fill

- allennlp/data/dataset_readers/conll2003.py
The docs for the conll2003 reader say:
```
feature_labels: ``Sequence[str]``, optional (default=``()``)
These labels will be loaded as features into the corresponding instance fields:
``pos`` -> ``pos_tags``, ``chunk`` -> ``chunk_tags``, ``ner`` -> ``ner_tags``
Each will have its own namespace: ``pos_labels``, ``chunk_labels``, ``ner_labels``.
If you want to use one of the labels as a `feature` in your model, it should be
specified here.
```
however, the namespaces are improperly named `pos_tags`, `chunk_tags`, etc. This fixes them.
cc @matt-peters this might affect you?
> Fix Conll2003 reader docs to reflect true label namespace names

- allennlp/models/bimpm.py
- allennlp/service/server_simple.py
- allennlp/tests/models/bimpm_test.py
Two changes:
1. Adding decoder to BiMPM model for demo.
2. Add model weights and overrides to the demo server.
With these change I can run BiMPM Quora Paraphrase demo by using:
```
python -m allennlp.service.server_simple \
--archive-path https://s3-us-west-1.amazonaws.com/handsomezebra/public/bimpm-quora-2018.08.17.tar.gz \
--predictor textual-entailment \
-o '{"dataset_reader": {"tokenizer": {"word_splitter": {"type": "spacy"}}}}' \
--title "Demo of the Paraphrase Identification" \
--field-name premise --field-name hypothesis
```
> Adding decoder to bimpm and improve demo server.

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- allennlp/__init__.py
- setup.py
fixes #1660 (as much as we can fix it)
> require Python 3.6.1

- scripts/check_links.py
- tutorials/getting_started/using_as_a_library_pt2.md
- tutorials/how_to/elmo.md
There were several links in the documentation that were broken, yet were not caught with `scripts/check_links.py`, since they were "local path" links to files within the directory and not urls. I fixed those links and improved `scripts/check_links.py` to handle local paths differently and catch paths to files that don't exist.
> Fix links in docs and improve check_links.py

- allennlp/tests/training/metrics/covariance_test.py
- allennlp/tests/training/metrics/pearson_correlation_test.py
- allennlp/training/metrics/__init__.py
- allennlp/training/metrics/covariance.py
- allennlp/training/metrics/pearson_correlation.py
- doc/api/allennlp.training.metrics.rst
This PR implements an online algorithm for calculating Covariance and the sample Pearson correlation coefficient.
This was actually nontrivial, I mostly referenced the tensorflow [streaming_covariance metric](https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/tensorflow/contrib/metrics/python/ops/metric_ops.py#L3127-L3264) in implementing this. Their implementation is a vectorized version of the weighted algorithm [on this wikipedia page](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online)
The tests simply ensure that the streaming Covariance and PearsonCorrelation match up with what numpy would calculate, which I believe is a reasonable correctness check.
> Add Covariance and PearsonCorrelation metrics

- allennlp/modules/conditional_random_field.py
Minor memory improvements possible in the _joint_likelihood() function of the ConditionalRandomField class by utilizing the advanced indexing feature of PyTorch (https://github.com/pytorch/pytorch/releases/tag/v0.2.0). 
Elliminates the need to expand transitions matrix by batch size (line 258 - 260) and to expand the tensor containing indices to the last tags by batch size (line 289).
> minor memory improvements in _joint_likelihood() of ConditionalRandomField with advanced indexing

- allennlp/models/biaffine_dependency_parser.py
- allennlp/models/biattentive_classification_network.py
- allennlp/models/constituency_parser.py
- allennlp/models/coreference_resolution/coref.py
- allennlp/models/decomposable_attention.py
- allennlp/models/esim.py
- allennlp/models/reading_comprehension/bidaf.py
- allennlp/models/reading_comprehension/dialog_qa.py
- allennlp/modules/seq2seq_encoders/intra_sentence_attention.py
- allennlp/modules/seq2seq_encoders/multi_head_self_attention.py
- allennlp/modules/span_extractors/self_attentive_span_extractor.py
- allennlp/nn/util.py
- allennlp/tests/nn/util_test.py
Back when we rolled our own `masked_softmax` and `masked_log_softmax`, we had to treat higher-dimension inputs separately.  We don't need to do that anymore, and so we should deprecate `last_dim_softmax` and `last_dim_log_softmax` in favor of just using the other versions, which will be more efficient.
> Removing last_dim_*softmax

- allennlp/training/metrics/covariance.py
this was modifying the labels inplace, which led to problems if you called something like
```
loss = some_function(pred, labels)
covariance(pred, labels)
```
This makes pytorch complain in the following way:
```
=============================================== FAILURES ================================================
___________ TestEventFactualityRegression.test_selective_tagger_role_can_train_save_and_load ____________
self = <tests.models.selective_regressor.event_factuality_test.TestEventFactualityRegression testMethod=test_selective_tagger_role_can_train_save_and_load>
def test_selective_tagger_role_can_train_save_and_load(self):
>       self.ensure_model_can_train_save_and_load(self.param_file)
tests/models/selective_regressor/event_factuality_test.py:20:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> Remove inplace modification in Covariance

- allennlp/data/dataset_readers/multiprocess_dataset_reader.py
- allennlp/data/iterators/multiprocess_iterator.py
this was a real nightmare to debug, but it seems like it fixes the problem. (as best as I can tell it was some kind of race condition with queues getting deleted before they were done being used. the `Manager` seems to avoid that.)
verified by building the Dockerfile.pip image and running the relevant tests inside it
> use managers for queues

- allennlp/training/trainer.py
The `from_params` method for the `Trainer` class was missing the `should_log_learning_rate` and `should_log_parameter_statistics` options.
> Fix trainer initialization

- allennlp/data/dataset_readers/semantic_parsing/wikitables.py
- allennlp/predictors/wikitables_parser.py
This is the reason that the wikitables demo doesn't ever return an answer - the table wasn't formatted correctly.  @schmmd FYI.  After this is merged, updating the demo to point to this commit (or later) will fix the "answer" value in the wikitables demo.
> Fixing the table format for the WikiTables executor

- allennlp/state_machines/transition_functions/basic_transition_function.py
- allennlp/state_machines/transition_functions/coverage_transition_function.py
- allennlp/state_machines/transition_functions/linking_coverage_transition_function.py
- allennlp/state_machines/transition_functions/linking_transition_function.py
The `num_start_types` parameter is only required in certain circumstances, but it was not an optional parameter, which made for some unnecessary code in some models.  This PR fixes that.
> Make num_start_types optional in transition functions

- allennlp/modules/token_embedders/embedding.py
- allennlp/tests/modules/token_embedders/embedding_test.py
This adds a `min_pretrained_embeddings` parameter to the `"embedding"` token embedder which will keep at least that many embeddings from the top of an embedding text file (like Glove). This is useful as a pragmatic way to support unseen words, say in a demo, at a cost of larger model size (e.g., specifying 200k here will increase model.tar.gz by about 75MB). This leverages the fact that at least for Glove files, the words are ordered by frequency, so by the time you get to, say, 200k, you're mostly missing out on rare words where the embeddings are less useful anyway. I'd use this in the QuaRel demo.
> Model can store extra pretained embeddings

- requirements.txt
- scripts/verify.py
`./scripts/check_requirements_and_setup.py` was failing silently because `ftfy` was in the wrong section in `requirements.txt`. I fixed `./scripts/verify.py` so that errors found by the requirements-checking script will cause the CI pipeline to fail, and I also moved `ftfy` to the right section.
> Move ftfy to right section in requirements.txt, fix requirements check script

- allennlp/semparse/contexts/sql_context_utils.py
- Fixes the warning `FutureWarning: split() requires a non-empty pattern match.` which occurs because `" wsp |wsp | wsp| ws |ws | ws|"` has an empty option at the end
- Compiles the regex once since it never changes
> Compile and fix warning for regex in SQL action seq formatting

- allennlp/semparse/worlds/atis_world.py
Fixes a bug where the base grammar binary expressions get mutated due to shallow copy. ``Grammar`` objects contain expressions i.e. ``OneOf`` that have tuples of the members that we want to modify. Just modifying the members will mutate the old copy.
https://github.com/erikrose/parsimonious/blob/master/parsimonious/grammar.py#L82 The docs in ``parsimonious`` states that all expressions are created from scratch but shallow copy doesn't actually clone child objects. Below is a simple example of the issue:
```
>>> from parsimonious import Grammar
>>> my_grammar = Grammar(r"""
...     styled_text = bold_text / italic_text
...     bold_text   = "((" text "))"
...     italic_text = "''" text "''"
...     text        = ~"[A-Z 0-9]*"i
...     """)
>>> new_grammar = my_grammar._copy()
>>> …
```
> Bug fix binary expression in updates to grammar

- training_config/dialog_qa.jsonnet
fix wrong config of `input_size` of `phrase_layer`.
This is the bug-fix to [\[Bug\] Wrong `input_size` of `phrase_layer` in `allennlp/training_config/dialog_qa.json`.](https://github.com/allenai/allennlp/issues/1874)
The better way to make config valid is to provide some `check_dimensions_match`s as in `bidaf.py`.
> input_size of phrase_layer: 1144 -> 1124

- tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt1.md
This fixes #1872 
I have updated the 2nd and 4th code snippets within predicting_paper_venues_pt1.md to reflect the test code that it references which is the [semantic scholar dataset reader test](https://github.com/allenai/allennlp-as-a-library-example/blob/master/tests/dataset_readers/semantic_scholar_dataset_reader_test.py) within the [allennlp as a library example repository](https://github.com/allenai/allennlp-as-a-library-example).
> predicting_paper_venues_pt1.md to reflect the updated test code

- allennlp/data/dataset_readers/semantic_parsing/atis.py
- allennlp/tests/data/dataset_readers/semantic_parsing/atis_test.py
The dev loss was not being recorded because we were not keeping target action sequences when we specify ``keep_unparseable`` instances. This PR adds an empty target action sequence to queries that cannot be parsed so we can still calculate dev loss on the rest of the instances.
> Track dev loss in ATIS model

- README.md
- doc/index.rst
This was rather buried in the README and the documentation landing page was rather sparse.  This idea came up on https://github.com/allenai/allennlp/issues/1610.
> Move 'What is AllenNLP' from README to docs.

- allennlp/modules/elmo.py
- allennlp/modules/scalar_mix.py
- allennlp/tests/modules/scalar_mix_test.py
This PR enables a user to specify a (frozen) scalar mix to use with ELMo
> Enable setting scalar mix parameters for ScalarMix and Elmo

- tutorials/getting_started/walk_through_allennlp/configuration.md
'throug' -> 'through' in link to example config
> Fix small typo

- allennlp/common/tee_logger.py
- allennlp/common/util.py
@splittingfield FYI. This won't take much effect until the next release but 🤷‍♂️
> Disable tqdm when there isn't a TTY

- allennlp/training/metrics/evalb_bracketing_scorer.py
This is necessary in order to get it to work on beaker, since otherwise the evaluation binary is never produced.
> Try compiling EVALB in metric if it doesn't exist

- training_config/constituency_parser_elmo.jsonnet
- renames existing `constituency_parser.jsonnet` (which has elmo) to `constituency_parser_elmo.jsonnet` to match the other configs
- adds new `constituency_parser.jsonnet` that follows the same embedding strategy as the original paper (https://arxiv.org/abs/1705.03919), 100d randomly initialized and updated word vectors.
> Add config for non-elmo constituency parser, rename existing parser config

- tutorials/README.md
Previously ctrl-f on https://github.com/allenai/allennlp for "tutorial" would send you first to `tutorials/README.md` which had no mention of Joel and Aaron's fancy new tutorial.
Should now be impossible to miss.
> Link tutorial site from tutorials/README.md.

- allennlp/data/token_indexers/token_characters_indexer.py
- allennlp/modules/token_embedders/elmo_token_embedder.py
- allennlp/tests/data/token_indexers/character_token_indexer_test.py
patch to #1954 
Although the parameter `min_padding_length` is provided a default value (`0`), I think it may be a better idea with no default value.
> add min_padding_length to TokenCharactersIndexer (#1954)

- allennlp/common/util.py
I'm really not sure what circumstance led me to run into this, but this change fixed the problem.  I don't understand why others haven't run into this issue; maybe it's because I was using `allennlp` just in my `PYTHONPATH`, instead of installing it through pip?
The exact command I was running was:
```bash
PYTHONPATH=~/clone/allennlp:. python ~/clone/allennlp/allennlp/run.py train training_config/latent_alignment.json -s /tmp/align -f --include-package weak_supervision
```
> Fix for import_submodules

- allennlp/data/dataset_readers/event2mind.py
- allennlp/tests/data/dataset_readers/event2mind_test.py
- I noticed this difference while retraining the model to account for https://github.com/allenai/allennlp/pull/1944.
- With this change we generate the exact same vocab as was used for the 10/5 model and now the new 10/26 model.
- In the long run we'll want to be more principled with our vocab. In the short term I'm more concerned with ensuring that we can retrain consistently.
> Match vocab generation in currently online Event2Mind model.

- allennlp/commands/find_learning_rate.py
- allennlp/tests/commands/find_learning_rate_test.py
It often takes a couple runs to get the right start and end learning rates and number of batches, so it's convenient when you can just overwrite the last serialization directory. This also just cleans up the docstrings a little for consistency.
> Add --force option to find-lr command

- scripts/inspect_cache.py
I was confused because the previous implementation was telling me:
```
No cached datasets found.
```
Instead of giving me a more accurate exception:
```
FileNotFoundError: file /Users/michael/.allennlp/datasets/dd04ba717be48bea13525e4293a243477876cdb0f0166abb8b09b5ed2e17cb3e.d68991c3e6de7fbcb5cf3e605d0e298f12cb857ca9d70aa8683abc886aa49edd.json.json not found
```
This change prevents such exceptions from being swallowed.
> Prevent inspect_cache from swallowing exception.

- allennlp/predictors/predictor.py
Since `bimpm` uses fields similar to `DecomposableAttention` model,  `textual-entailment` predictor is made as the default for `bimpm`.
> Added default predictor for bimpm model

- allennlp/common/registrable.py
This removes much of the noise from the `allennlp` command.
```
2018-11-01 15:48:30,734 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-11-01 15:48:30,735 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-11-01 15:48:30,736 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2018-11-01 15:48:30,736 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
usage: allennlp
Run AllenNLP
optional arguments:
-h, --help    show this help message and exit
--version     show program's version …
```
> Change log level to clean up allennlp command.

- allennlp/commands/find_learning_rate.py
This is just a small change to the `find-lr` CLI. I changed the default value for the option `stopping-factor` to `None`. Without this you were forced to use a value for `stopping-factor` which is unnatural in some cases.
> Change find-lr stopping factor default to None

- allennlp/commands/find_learning_rate.py
- allennlp/tests/commands/find_learning_rate_test.py
Modified checks  in find_learning_rate.py to add support for multi-gpu training from [#1944](https://github.com/allenai/allennlp/pull/1944/commits/6d0da18aa6abea2865229f7041d1a6e6221395da)
> Enable multi-gpu training in find_learning_rate.py

- allennlp/modules/elmo.py
I noticed some root-level log messages for ELMo in the demo logging.  After this change they will have the proper `__name__`.
```
INFO:__main__:loading coreference-resolution model
INFO:__main__:loading named-entity-recognition model
INFO:root:Initializing ELMo
```
> Fix logging statement so it has the proper scope.

- allennlp/tests/training/metrics/bleu_test.py
- allennlp/training/metrics/__init__.py
- allennlp/training/metrics/bleu.py
- doc/api/allennlp.training.metrics.rst
I thought I should share my implementation of BLEU. This is the first time I've implemented it, so there may be a more efficient way, but I'm pretty sure the math checks out at least. If anyone has thoughts on how to improve it please let me know!
> Add BLEU metric

- allennlp/service/server_simple.py
- allennlp/tests/service/server_simple_test.py
Some simple improvements to server_simple.py:
1. Add a predict_batch method so a client can send a list of items for prediction.
2. Add the command line option --cuda-device.
> Improve server_simple by adding predict_batch and adding GPU option

- allennlp/modules/seq2seq_encoders/intra_sentence_attention.py
In docstring,
type of ``output_dim`` 'bool' -> 'int'
> Fix typo in docstring

- .gitignore
- allennlp/data/tokenizers/word_splitter.py
- allennlp/predictors/coref.py
- allennlp/predictors/semantic_role_labeler.py
- allennlp/tests/predictors/coref_test.py
- allennlp/tests/predictors/srl_test.py
Adding method to support predicting on tokenized input in ``coref.py`` and ``semantic_role_labeler.py`` API methods.
Added methods:
``CorefPredictor.predict_from_list(self, tokenized_document: List[str]) -> JsonDict:``
``SemanticRoleLabelerPredictor.predict_from_list(self, tokenized_sentence: List[str]) -> JsonDict:``
This is very useful when user data is already tokenized (for example annotated corpus for some NLP task) and user would like to predict on that tokenized data without losing the original tokens ID's.. 
Avoid a workflow of: Creating document/sentence text from tokenized data -> input created text to predict method -> predict will tokenize the input text -> align output tokens with original tokens.
Usage code example in:
for coref: ``allennlp/tests/predictors/coref_test.py``, …
> Add support of tokenized input for coref and srl predictors

- allennlp/training/metrics/evalb_bracketing_scorer.py
Previously, the code would try to change directories to the expected path of the EVALB binary, which doesn't work since it doesn't exist --- the right thing to do is to change directories to the location of the EVALB source files, and run `make` in there.
fyi @schmmd
> Fix EVALB compilation by cd to directory path instead of binary path

- allennlp/data/iterators/basic_iterator.py
- allennlp/data/iterators/bucket_iterator.py
- allennlp/data/iterators/data_iterator.py
- allennlp/tests/data/iterators/basic_iterator_test.py
- allennlp/tests/data/iterators/bucket_iterator_test.py
- Previously when maximum_samples_per_batch was used overly large batches would be split into equal sizes.
- This could lead to a certain degree of fragmentation.
- This change packs batches until just before maximum_samples_per_batch (or batch_size) is exceeded.
> Pack batches more tightly with maximum_samples_per_batch.

- allennlp/modules/text_field_embedders/basic_text_field_embedder.py
- allennlp/tests/modules/text_field_embedders/basic_text_field_embedder_test.py
- allennlp/tests/training/optimizer_test.py
- allennlp/tests/training/trainer_test.py
While we would like to discourage the original behavior, we would like to remove the deprecation warning because we still follow it throughout our test fixtures and full models.  We can formally deprecate this behavior when AllenNLP gets off it.
> Remove the BasicTextFieldEmbedder warning

- allennlp/modules/text_field_embedders/basic_text_field_embedder.py
- allennlp/tests/modules/text_field_embedders/basic_text_field_embedder_test.py
with BERT + ELMo + OpenAI embedders this becomes a very easy mistake to make, so I changed it to give a more informative error message in the case where the input has too many keys, and left the same error message in the case where there's a total mismatch
> more informative message for BasicTextFieldEmbedder mismatched keys

- allennlp/data/dataset_readers/multiprocess_dataset_reader.py
fixes #2091 and #2005
(is slightly ugly)
> instantiate multiprocessing.log_to_stderr lazily

- allennlp/models/archival.py
- allennlp/tests/models/archival_test.py
Fixes the issue described in #2180 using the `atexit` hook proposed by @joelgrus.
Please let me know if there are any changes you'd like to see made and I'd be happy to make them.
> Clean up temporary archive directory at exit

- allennlp/modules/seq2seq_encoders/bidirectional_language_model_transformer.py
The subsequent_mask function in the bidirectional_language_model_transformer seemed to be unnecessarily convoluted.
> Simplifies Subsequent Mask 

- allennlp/modules/elmo.py
Some default values were wrong or not present in the documentation.
> Corrected documentation

- allennlp/modules/token_embedders/bert_token_embedder.py
the required parameter "pretrained_model" was mislabeled as "pretrained_model_name" in the documentation
> change mislabeled variable in description

- allennlp/modules/token_embedders/elmo_token_embedder.py
- allennlp/tests/modules/token_embedders/elmo_token_embedder_test.py
1. Fix get_output_dim() of ElmoTokenEmbedder with projection
2. Add test of get_output_dim() of ElmoTokenEmbedder with projection
#2227
> fix get_output_dim() for ElmoTokenEmbedder

- README.md
@matt-gardner here's a stab at a contributions section.  We can require a code owner to review, which we can manage in a [`CODEOWNERS` file](https://help.github.com/articles/about-codeowners/).  I don't think that's necessary presently.
If we want to grant others write access we could consider changing our code coverage tests, which often fail and require admin permissions to overwrite them.
> Add a Contributions section to README.md

- allennlp/data/fields/multilabel_field.py
- allennlp/tests/data/fields/multilabel_field_test.py
> Make `MultiLabelField.as_tensor` return `LongTensor`s.

- allennlp/data/vocabulary.py
As it currently stands, the following is logged during training:
```
2019-01-06 10:46:21,832 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.model
s.language_model.LanguageModel'> from params {'bidirectional': False, 'contextualizer': {'bidirectional':
False, 'dropout': 0.5, 'hidden_size': 200, 'input_size': 200, 'num_layers': 2, 'type': 'lstm'}, 'dropout
': 0.5, 'text_field_embedder': {'token_embedders': {'tokens': {'embedding_dim': 200, 'type': 'embedding'}
}}} and extras {'vocab': <allennlp.data.vocabulary.Vocabulary object at 0x7ff7811665f8>}
```
Note that the `Vocabulary` does not provide any useful information, since it doesn't have `__repr__` defined. This provides a fix.
> Add __repr__ to Vocabulary

- Dockerfile
- Dockerfile.pip
This also upgrades `pip` from 9 to 18.1.  We've had `pip` warnings in our builds for a long time and few of our users likely use as old as a version as we have in our continuous build.
> Update the base image in the Dockerfiles.

- allennlp/commands/train.py
- allennlp/common/checks.py
> Check train/dev/test-file-path before process

- allennlp/commands/__init__.py
- allennlp/commands/find_learning_rate.py
I thought it would be nice to display the default values in the help message when you do something like `allennlp find-lr --help`. This PR implements a custom `ArgumentParser` that just overrides the `add_argument` method to add any meaningful default values to the help description. Below is what the new output looks like:
> Display default values in help message for allennlp command

- tutorials/notebooks/embedding_tokens.ipynb
change "experimenation" to "experimentation"
> fix a typo in tutorials/notebooks/embedding_tokens.ipynb

- allennlp/data/vocabulary.py
- allennlp/tests/data/vocabulary_test.py
> enable pickling for vocabulary

- allennlp/models/model.py
Fixes https://github.com/allenai/allennlp/issues/2306
> Remove unnecessary line

- allennlp/data/token_indexers/wordpiece_indexer.py
`pretrained_model` is not an optional param, as stated in `PretrainedBertIndexer` docs, so I removed the "optional" part from it.
> Fix docstring for PretrainedBertIndexer's pretrained_model param

- allennlp/training/trainer.py
PR #2261 is incomplete. If we load an existing vocabulary, the key `vocabulary` still exists in `params`. This will cause the line `params.assert_empty('base train command')` in `commands/train.py` to raise an assertion later on.
This PR ensures that the key `vocab` is always popped off `params` in all cases.
> Ensure vocab is popped off params in recovery mode

- allennlp/data/vocabulary.py
In case of inheriting Vocabulary, the method `from_params` calls the same method of the registered class if `type` is given. If `from_params` is not overridden (even if it is), the default implementation calls hardcoded `Vocabulary.from_instances` and `Vocabulary.from_files` and the subclass implementations of these methods are not called.
With this commit the `Vocabulary` is replaced by `cls` allowing to customize behaviour of the subclass.
> Get rid of hardcoded Vocabulary class name.

- scripts/check_docs.py
We've had a couple of people recently not understand what "undocumented module" meant in a CI failure.  This adds a nicer error message explaining what needs to happen for the check to pass.
> Improve error message for "undocumented modules"

- allennlp/common/util.py
- allennlp/modules/sampled_softmax_loss.py
- allennlp/tests/nn/beam_search_test.py
- allennlp/tests/predictors/atis_parser_test.py
- Tests appear to pull down a DB file from S3.
- Spurious network failures are common, so mark as flaky to ameliorate the problem.
- Alternative: Bring DB file into fixtures directory. However, as we're trying to keep the size of the library down, this probably isn't advisable.
- Also disables some `pylint` warnings that hit with `numpy==1.16.0`.
> Mark Atis Parser tests as flaky. Fix pylint.

- allennlp/modules/seq2seq_encoders/__init__.py
- allennlp/modules/seq2seq_encoders/feedforward_encoder.py
- allennlp/tests/modules/seq2seq_encoders/feedforward_encoder_test.py
- doc/api/allennlp.modules.seq2seq_encoders.rst
This new class (`FeedforwardEncoder`) applies the `FeedForward` to each item in sequences. So we can specify a feedforward network for sequences just by changing a configuation file now.
> [Feature Enhanced]Add FeedforwardEncoder for Sequences

- allennlp/common/util.py
I've run into this a few times myself, and @nitishgupta spent a lot of time on it today.  This fixes the problem.  I'm not sure if there's a better way to solve it, though.
> Fix path issue for certain cases when using --include-package

- allennlp/training/moving_average.py
@joelgrus The original `Parameter.clone()` seems to consume much more memory than `Parameter.data.clone()`. The original one caused OOM when running a large model. But the new one could work. Also, I use the `tensor.copy_()` method to assign values when doing the moving average, which does not significantly reduce memory usage, but seems more reasonable.
> Fixes unnecessary parameter clone in moving average.

- allennlp/service/config_explorer.html
The config explorer is currently broken on master due to https://github.com/unpkg/unpkg.com/issues/176 . Here's a screenshot of what I see:
The fix seems to be to remove the `crossorigin` attribute on the `<script>` tag. Things seems to load fine after doing so (also recommended in https://github.com/unpkg/unpkg.com/issues/176#issuecomment-459252472 ).
> Fix CORS error for react in config explorer

- allennlp/data/token_indexers/token_characters_indexer.py
- allennlp/tests/data/token_indexers/character_token_indexer_test.py
Reverts allenai/allennlp#2494
We just merged a huge involved PR to get rid of all of our warnings when we run tests (https://github.com/allenai/allennlp/pull/2479, https://github.com/allenai/allennlp/pull/2282).  I won't repeat the justification for this here - anyone interested can go back and read that history.  The bottom line: it is intentionally difficult to introduce new warnings into our code.  The original PR that introduces a warning must also do whatever cleanup is necessary for it, so that the cleanup has a clear owner and actually gets done.  This PR bypassed that by using a `UserWarning` instead of a `DeprecationWarning`, so I am reverting it.  I had a discussion with @joelgrus, who hadn't followed all of the discussion involved in #2282, and approved the PR without realizing …
> Revert "Less restrictive token characters indexer"

- allennlp/modules/seq2vec_encoders/boe_encoder.py
Adding bag_of_embeddings as an alternate registered name for the boe encoder, as requested in issue #2268 and comment #2246
> Adding bag_of_embeddings as an alternate name for the boe encoder

- allennlp/training/tensorboard_writer.py
- allennlp/training/trainer.py
Fixes #2529.
This changes the metrics that get logged to tensorboard at the end of every epoch to use the epoch number as its counter, instead of the batch number.  This is what the behavior was prior to the refactoring.
I think there are still some very confusing things in this behavior, which we may want to change: "epoch_metrics" isn't actually "the metrics at the end of every epoch", it's "train metrics shown at `summary_interval` steps during an epoch".  So I propose that we regroup things into two sections: (1) `epoch_metrics/`, which use the epoch number as their counter and are shown for both training and validation, and (2) `train_metrics/`, which use the batch number as their counter and are logged at `summary_interval`.  This is just renaming the current `epoch_metrics` to …
> Restore tensorboard epoch metrics to pre-refactoring behavior

- pytest.ini
A couple of people have mentioned test failures when running locally.  I just tried it myself and discovered that updates to other libraries added some deprecation warnings that are causing our tests to fail.  This was not the intent of the deprecation-warning-into-error stuff that we did - we just wanted to make sure we weren't adding deprecation warnings ourselves without fixing our own code first.  So this PR changes the policy to ignore all non-allennlp deprecation warnings, and fail only on allennlp ones (I confirmed that adding a deprecation warning inside of allennlp causes test failures, as intended).
> Scope DeprecationWarning errors to just allennlp-internal stuff

- allennlp/common/testing/model_test_case.py
This was breaking for me when I wanted to create a unit test for a model, but also wanted to force certain parameter overrides as specified in the unit test. 
In this function, the model is instantiated from the params file with overrides.
But the second time params are created from file, it's missing the overrides argument, causing mismatches in the rest of the test.
> Fix broken model unit test function when using overrides

- allennlp/data/dataset_readers/reading_comprehension/drop.py
- allennlp/models/__init__.py
- allennlp/models/reading_comprehension/__init__.py
- allennlp/models/reading_comprehension/naqanet.py
- allennlp/tests/data/dataset_readers/reading_comprehension/drop_test.py
- allennlp/tests/fixtures/naqanet/experiment.json
- allennlp/tests/models/reading_comprehension/naqanet_test.py
- allennlp/training/metrics/drop_em_and_f1.py
- doc/api/allennlp.models.reading_comprehension.rst
- doc/api/allennlp.training.metrics.rst
This depends on #2556 and on #2559.
> Add NAQANet model for DROP

- setup.py
I figured out why the master commit was breaking - I added something to `requirements.txt` without adding a corresponding entry to `setup.py`.  I forgot that we had to do this.  I thought we had some check that made sure these were consistent?  Did that not actually happen?  Anyway, I'm going to merge this when tests pass, so I can get a demo deploy set up.
> Add missing requirement to setup.py

- allennlp/commands/evaluate.py
- allennlp/models/archival.py
- allennlp/tests/models/archival_test.py
- Fixes https://github.com/allenai/allennlp/issues/1052.
- Files like ELMo weight files aren't added to the serialization dir, but are added to the archive with `add_file_to_archive`.
- This results in misleading errors when using `load_archive` as it will attempt to load a serialization dir.
- Solution: Retain original paths when we're loading from a directory.
- Drive by fix for overrides not overriding.
> Make `load_archive` operate on serialization directories.

- allennlp/pretrained.py
Fixes #2540.  These predictors use old config files, before we introduced the `min_padding_length` parameter.  See #1954 if you need more context on this.
> Fix min padding length in pretrained NER predictors

- allennlp/tests/commands/train_test.py
- The error the test matches against is different depending on whether you have GPUs available.
- Simply make the match more general.
> Fix unit test to work with GPUs.

- allennlp/tests/training/checkpointer_test.py
- allennlp/training/checkpointer.py
- allennlp/training/trainer.py
Allows custom Checkpointer to be loaded from params.
Trainer now takes an optional `checkpointer` parameter. 
Also added some unit tests for Checkpointer
> Allow checkpointer to be initialized from params

- allennlp/tests/tutorials/tagger/basic_allennlp_test.py
it's breaking the master commit build (on account of the tutorial code not getting pip installed), and it's a really slow test, so I'm disabling it for now
> disable tutorial test

- allennlp/common/params.py
- allennlp/tests/common/params_test.py
Currently, when lists are popped off `Params`, `Params._check_is_dict()` will give each element in the list a history of `old_history.list.`. If this history is later intended to be used to construct an overrides dict (such as in`Params.add_file_to_archive()`) this will cause the overridden dict to be constructed incorrectly:
```python
from allennlp.common.params import with_fallback, unflatten
overrides_dict = {"old_history.list.some_value": 1}  
preferred = unflatten(overrides_dict) # => {"old_history": {"list": {"some_value": 1}}}
fallback = {"old_history": [{"some_value": 0}]}
config = with_fallback(preferred, fallback) # => {'old_history': {'list': {'some_value': 1}}}
```
We use allennlp's config system to compose simple transformations on data, and these transforms occasionally …
> Add support for overriding list elements

- allennlp/data/dataset_readers/seq2seq.py
- allennlp/tests/data/dataset_readers/seq2seq_test.py
- allennlp/tests/fixtures/data/seq2seq_copy.csv
- use Python core "csv" module
- add delimiter option for sth different than "\t"
- add tests for edgecases
> Seq2seq dataset reader improvements

- allennlp/predictors/predictor.py
- allennlp/tests/predictors/bidaf_test.py
as I said, this approach is slightly on the "cute" side, but I like how utterly non-intrusive it is
> context manager that allows predictor to capture model internals

- allennlp/commands/make_vocab.py
`make_vocab` on  dataset with size of few GB caused draining whole available RAM.  
Used generator instead of reading all instances to memory before
passing to Vocabulary class(as in train loop).
Now `make_vocab` respects `lazy` on dataset reader.
> Fixed memory error in `make_vocab` on big dataset.

- allennlp/common/testing/model_test_case.py
- allennlp/nn/beam_search.py
- allennlp/tests/nn/beam_search_test.py
Addresses the edge case brought up in #2486 (fixes #2486) as well as another. This actually turned out to be a little more nuanced...
I first thought the issue brought up was caused by `start_predictions` being the `end_index`, but it actually occurs in general with a beam size of 1 when the first predictions that the step function produces are the `end_index`, regardless of what `start_predictions` are, i.e. at this line: 
`start_class_log_probabilities, state = step(start_predictions, start_state)`
The other edge case is similar, and occurs when the beam size is smaller than the number of valid (non-zero probability) transitions that the step function produces. For example, this could happen in a semantic parsing task where a masked log softmax is used to create predicted log probs for …
> Handle edge cases in beam search

- allennlp/common/from_params.py
> Only log the keys in the "extras" dictionary when instantiating objects from_params

- allennlp/common/util.py
- allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py
- allennlp/data/tokenizers/token.py
- allennlp/data/tokenizers/word_splitter.py
- allennlp/data/tokenizers/word_stemmer.py
- allennlp/tests/data/token_indexers/ner_tag_indexer_test.py
- allennlp/tests/data/token_indexers/pos_tag_indexer_test.py
- allennlp/tests/data/tokenizers/word_splitter_test.py
largely fixes #2602, also fixes #1887 
the discussion at #2602 gives a lot of the justification for this, small-scale experiments suggest that it saves a lot of memory if you have a lot of text.
it is a breaking change in two (minor) ways:
1. the SpacyWordSplitter now by default returns allennlp Tokens instead of spacy Tokens. in theory everyone should be programming to the shared abstraction, but it's possible that someone somewhere is relying on having the actual spacy token, in which case they'll need to configure their word splitter to keep them.
2. a NamedTuple can't have different constructor parameters and field names. Our previous Token implementation used e.g. `pos` as the name of the constructor argument but then `pos_` as the name of the field. Converting this to a namedtuple …
> make spacy word splitter return allennlp Tokens (now NamedTuples) by default

- allennlp/modules/conditional_random_field.py
- allennlp/tests/modules/conditional_random_field_test.py
Currently, the transition from M to M is not allowed for BMES label as shows in this sample:
```
In [1]: from allennlp.modules.conditional_random_field import allowed_transitions
In [2]: labels = {0: "B", 1: "M", 2: "E", 3: "S"}
In [3]: allowed_transitions("BMES", labels)
Out[3]:
[(0, 1),
(0, 2),
(1, 2),
(2, 0),
(2, 3),
(2, 5),
(3, 0),
(3, 3),
(3, 5),
(4, 0),
(4, 3)]
```
If target spans could be longer than 3 tokens, the transition between `M` should be valid, for example `B -> M -> M -> E`.
This pull request adds the transition and modify the corresponding test case.
What do you think?
> Allow the transition from M to M in the BMES constraint type

- allennlp/modules/stacked_alternating_lstm.py
- allennlp/tests/modules/seq2vec_encoders/pytorch_seq2vec_wrapper_test.py
Fixes #2503. The `final_state_tuple` in the `StackedAlternatingLstm` was a generator instead of a tuple.
> final_state_tuple is a Tuple

- allennlp/data/tokenizers/sentence_splitter.py
- allennlp/tests/data/dataset_readers/text_classification_json_test.py
- allennlp/tests/data/tokenizers/sentence_splitter_test.py
- allennlp/tests/models/sniff_test.py
I am not thrilled about this, as the 2.0 code path is not really getting tested anymore (except manually, by me, as part of preparing this PR).
If we're not willing to have our CI test both ways (and I'm pretty sure we're not), then I'm not sure we should support 2.0.
> make things backward compatible with spacy 2.0

- tutorials/tagger/config_allennlp.py
Running the tutorial from the command line will cause a `FileNotFoundError`, so I added `cached_path`.
> config_allennlp.py uses open(file_path) where file_path is a URL

- allennlp/data/dataset_readers/penn_tree_bank.py
Some variants of the PTB dataset use `TOP` as the root node, rather than `VROOT`. This lets the dataset reader handle both.
> Ignore 2 root node types in PTB parsing reader

- allennlp/semparse/domain_languages/domain_language.py
- requirements.txt
- scripts/verify.py
Pinned pylint to the last 1.x version. Upgrading to 2.0 means much more changes.
This was motivated mostly because I realize that it was failing to check `allennlp/semparse/domain_languages/domain_language.py`, so it was ignoring checks there. I did the correspoding changes now that this file is checked. I also removed an unnecessary type ignore.
And I refactored `scripts/verify.py` a bit. This may be another PR, but I was wondering if the overhead it's worth it.
> Update pylint to 1.9.4

- tutorials/tagger/config_allennlp.py
Fixes issue #2704, where `cached_file` is not defined which was introduced in #2654
> Fix tagger tutorial

- allennlp/models/basic_classifier.py
I believe this got changed during the PR process and the docstring never got updated. ``Seq2VecEncoder`` is not an optional argument.
> Docstring for `BasicClassifier` incorrectly states that `Seq2VecEncoder` is optional.

- allennlp/models/language_model.py
- allennlp/training/metrics/__init__.py
- allennlp/training/metrics/perplexity.py
- doc/api/allennlp.training.metrics.rst
As discussed in #2400, this PR adds a `perplexity` metric to the `LanguageModel`. To do this, I created a `Perplexity` metric class which is updated with a negative log loss. @nelson-liu 
fixes #2400
> Add perplexity metric to LanguageModel

- allennlp/modules/token_embedders/elmo_token_embedder.py
Fixing typo in `ElmoTokenEmbedder` documentation
> Fixing typo in ElmoTokenEmbedder documentation

- allennlp/common/__init__.py
- allennlp/common/from_params.py
- allennlp/modules/feedforward.py
- allennlp/nn/activations.py
- allennlp/tests/common/from_params_test.py
- allennlp/tests/modules/feedforward_test.py
This removes the need for custom `from_params` for `FeedForward` (and lets me more easily add some other modules that have similar behavior).
> Allow FromParams to construct Union types

- allennlp/commands/train.py
- allennlp/common/params.py
- allennlp/common/util.py
- allennlp/data/dataset_readers/dataset_reader.py
- allennlp/data/dataset_readers/reading_comprehension/drop.py
- allennlp/data/dataset_readers/snli.py
- allennlp/data/fields/array_field.py
- allennlp/data/fields/field.py
- allennlp/data/instance.py
- allennlp/data/iterators/data_iterator.py
- allennlp/data/token_indexers/token_indexer.py
- allennlp/data/tokenizers/token.py
- allennlp/tests/commands/train_test.py
- allennlp/tests/data/dataset_readers/dataset_reader_test.py
- allennlp/tests/training/trainer_test.py
- allennlp/tests/training/util_test.py
- allennlp/training/trainer.py
- allennlp/training/util.py
- requirements.txt
- setup.py
This adds a parameter that lets you specify a path to a cache file, where we will save already-constructed `Instances` for faster loading on subsequent reads of the data.  If you do a lot of processing, like running a tagger or expensive tokenizer or other things, this should save you a lot of time.  If you have only minimal pre-processing, this probably won't buy you much.
> Add caching functionality to the base DatasetReader class

- allennlp/data/dataset_readers/multiprocess_dataset_reader.py
- allennlp/tests/data/dataset_readers/multiprocess_dataset_reader_test.py
- Fixes https://github.com/allenai/allennlp/issues/2620.
- Python resets the `random` library's seeds whenever a new process is spawned.
- Use numpy to avoid this.
> Use numpy's shuffle for reproducibility.

- training_config/ner_elmo.jsonnet
Fixes mismatch between code and comments, where attempting to run the pretrained NER model gives the following error: 
```allennlp.common.checks.ConfigurationError: "Extra parameters passed to CrfTagger: {'constraint_type': 'BIOUL'}"```
> Update comment on ELMo NER model to match current configuration

- allennlp/common/from_params.py
- allennlp/tests/common/from_params_test.py
Fixes #2665.
This ensures only extras relevant to a class are passed to its from_params constructor for classes with custom from_params. Additionally, also handles the hacky scenario when the class does not have a from_params method, the assumption there being that we want to pass extras for the class itself (instead if its from_params method)
> Extras checks

- allennlp/modules/seq2seq_encoders/qanet_encoder.py
- allennlp/pretrained.py
Fixes #2772.  `ModuleList` encodes it weight names differently, so I had to modify the saved model archive, and #2692 ended up adding each block twice, so I had to remove a line there.
We should figure out a better way to have sniff tests for all of our pretrained models, so we catch these things earlier...
> Fix bug in QaNetEncoder, update pretrained model

- allennlp/tests/training/metrics/fbeta_measure_test.py
- allennlp/training/metrics/fbeta_measure.py
- A stray squeeze caused batches of size one to be zero dimensional. Indexing into them was thus invalid and crashed.
- See https://github.com/allenai/allennlp/pull/2275#issuecomment-487486905
> Make FBetaMeasure work with batch size of 1.

- allennlp/tests/models/reading_comprehension/naqanet_test.py
- This test has caused a couple failures of the "GPU Unit Tests" over the past few days due to flakiness.
- Examples:
http://build.allennlp.org/viewLog.html?buildId=14497&buildTypeId=AllenNLP_GpuUnitTests&tab=buildLog&_focus=2658
http://build.allennlp.org/viewLog.html?buildId=14313&buildTypeId=AllenNLP_GpuUnitTests&tab=buildLog&_focus=2600
> Increase max_runs for NumericallyAugmentedQaNetTest.

- training_config/naqanet.jsonnet
It seems that there's a discrepancy between the registered model name for NAQANet (naqanet.py) and the name in the config file
> Changing model name in config file to match registered name

- allennlp/common/params.py
When running `allennlp --cache-directory`, directory name hashes are not consistent across program invocations because Python's builtin `hash` function is initialized with a different random seed each time. An easy fix is to use a deterministic hash function, as discussed here: https://stackoverflow.com/questions/27954892/deterministic-hashing-in-python-3.
I'm not an expert on the properties of hash functions but it seems like this should do fine.
> Make `allennlp train --cache-directory` hashes consistent across program invocations.

- allennlp/training/metrics/auc.py
Masks were not unwrapped to tensors in AUC metric
> Unwrap masks to tensors as well in AUC metric

- allennlp/training/trainer_base.py
- This code is relatively stable.
- However, our support isn't ideal as it's based on `torch.nn.DataParallel`.
- We should really investigate using `torch.nn.parallel.DistributedDataParallel`.
> Remove multiple GPU warning

- allennlp/commands/train.py
- Seeds are already logged, but before we're writing to `stdout.log`.
- `create_serialization_dir` and `prepare_global_logging` don't appear to rely on random seeds, so this should be safe.
> Log random seeds to disk.

- allennlp/tools/drop_eval.py
Leaderboard expects a json file with the evaluation metrics.
Having the evaluator code output a file that conforms to that format will simplify the maintenance of the DROP leaderboard, as the backend can just call 
`python -m allennlp.tools.drop_eval --gold_path path/to/gold --prediction_path path/to/predictions --output_path path/to/metrics`
> Add output path to drop eval

- allennlp/tests/tools/drop_eval_test.py
- allennlp/tools/drop_eval.py
In short, the problems this fixes:
1) EM wasn't length-aware, since only the bags were being compared.
2) The F1 calculation was taking the average of the optimal alignments between the gold and the predicted. However, if there are more predicted answers than gold answers, the precision isn't penalized. In the case where there are more predicted answers, the excess answers are all given an F1 of 0.
Before this patch:
```
In [1]: from allennlp.tools.drop_eval import get_metrics
In [2]: get_metrics(predicted=["td"], gold=["td", "td"])
Out[2]: (1.0, 0.5)
In [3]: get_metrics(predicted=["td", "td"], gold=["td"])
Out[3]: (1.0, 1.0)
In [4]: get_metrics(predicted=["the", "fat", "cat", "the fat", "fat cat", "the fat cat"], gold=["cat"])
Out[4]: (0, 1.0)
```
After this patch:
```
In [1]: from …
```
> Make DROP EM and F1 calculation length aware

- allennlp/modules/token_embedders/embedding.py
Make sure the `extra_weight` is shifted to the right device before trying to extend the embedding.
> Shift extra_weight for embedding extension to right device

- allennlp/data/fields/text_field.py
- allennlp/tests/data/fields/text_field_test.py
Related to (fixes?) #1591
The bug is about some `TextField` in some instance of the dataset that has no tokens and, at the same time, a `TokenCharactersIndexer` is used. When `to_tensor` is called it fails.
> Fix TextField padding when there are no tokens

- scripts/ai2-internal/run_with_beaker.py
The subprocess call that used to create a blueprint now throws a warning, which is also captured and interpreted as the name of a blueprint, causing the experiment creation to fail. This update fixes that issue as well.
> Change blueprint to image in run_with_beaker

- allennlp/models/basic_classifier.py
- allennlp/models/bert_for_classification.py
This fixes an issue where `basic_classifier` and `bert_for_classification`, when used with integer labels (`LabelField` created with `skip_indexing=True`) run into an issue during prediction, where the `decode` method tries to look up labels for label indices. Sample stack trace:
```Traceback (most recent call last):
File "allennlp_data_processor/run.py", line 14, in <module>
main(prog="python -m allennlp.run")
File "/Users/sumithrab/anaconda/envs/commonsense/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
args.func(args)
File "/Users/sumithrab/anaconda/envs/commonsense/lib/python3.6/site-packages/allennlp/commands/predict.py", line 204, in _predict
manager.run()
File "/Users/sumithrab/anaconda/envs/commonsense/lib/python3.6/site-packages/allennlp/commands/pre …
```
> Fix Invalid Index Reference for labels in Vocabulary

- allennlp/models/bert_for_classification.py
- allennlp/modules/seq2vec_encoders/bert_pooler.py
The two kwargs `trainable` and `requires_grad` in `BertForClassification` and `BertPooler` have no effect as described in #2927.
This PR fixes #2927 by simply looping over the model parameters and freezing/unfreezing them.
> Fix `trainable` and `requires_grad` kwargs in `BertForClassification` and `BertPooler`

- allennlp/pretrained.py
Fixes https://github.com/allenai/allennlp/issues/2930.
I've tested it manually with this code that failed before:
```python
In [1]: import allennlp.pretrained as pt                                                                                                                                 
In [2]: c = pt.neural_coreference_resolution_lee_2017()                                                                                                                  
In [3]: c.predict('I am Joe.')                                                                                                                                           
Out[3]: 
{'top_spans': [[0, 0]],
'antecedent_indices': [0],
'predicted_antecedents': [-1],
'document': ['I', 'am', 'Joe', '.'],
'clusters': []}
```
> Pad coreference model input to 5

- allennlp/models/reading_comprehension/bidaf.py
- allennlp/models/reading_comprehension/qanet.py
- allennlp/tests/training/metrics/boolean_accuracy_test.py
- allennlp/training/metrics/boolean_accuracy.py
Inputs to BooleanAccuracy must have the same dimensions. Here, the first argument has dimensions `(batch size, 2)`, while the second argument has dimensions `(batch size, 1, 2)`. Changing `torch.stack` to `torch.cat` makes the dimension of the second argument `(batch size, 2)`.
Note that span accuracy obtained earlier was not incorrect because of the way accuracy was being computed internally.
> Fixed minor error while calculating span accuracy

- allennlp/common/file_utils.py
> Use unsigned s3 requests when missing credentials

- allennlp/nn/regularizers/regularizer_applicator.py
- allennlp/tests/nn/regularizers_test.py
Fixes #2790 
Makes sure the regularizer doesn't include parameters that don't require gradients.
> ensure regularizers are only computed for parameters requiring gradients

- allennlp/data/tokenizers/word_filter.py
- allennlp/tests/data/tokenizers/word_tokenizer_test.py
The current default stopword list has some odd words like "prepatory", "irrespective", "accordance", "subsequent", etc. It's also missing words like "did", "so", "too", "can", and so on. This just replaces the hard-coded default list with one imported from spaCy, using the logic that since the default tokenizer uses spaCy, so should the default stopword list.
The biggest differences, beyond better word choices, are 1) punctuation is no longer filtered, 2) clitics like "'re" and "'ve" start getting filtered, and 3) potentially, a spaCy update could cause behavior to change. 
A regex filter could address (1); it seems odd to combine that behavior with stopword removal. (2), I think, is straightforwardly correct. Re: (3), the list looks like it's been pretty stable. The only changes in the …
> Replace current default stopword list with spaCy's.

- allennlp/common/file_utils.py
- allennlp/predictors/wikitables_parser.py
- allennlp/semparse/executors/wikitables_sempre_executor.py
Our tests have been consistently failing all day because of intermittent failed `requests.get` and `requests.head` calls to S3. It seems like these failures are rooted in AWS denying the requests (on account of volume / frequency?), so this PR implements retries with backoffs for all of our `requests` calls
> experimental: add backoff

- allennlp/nn/util.py
We only should raise this warning when both the previous and current timesteps are observations - before it was checking only the previous timestep, which wasn't correct.
> fix incorrect logging in viterbi decode

- allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py
- allennlp/semparse/action_space_walker.py
- allennlp/semparse/domain_languages/__init__.py
- allennlp/tests/semparse/action_space_walker_test.py
- scripts/nlvr/get_nlvr_logical_forms.py
- scripts/wikitables/search_for_logical_forms.py
Also moved the script used for searching for logical forms for WTQ from iterative-search-semparse.
> Modified ActionSpaceWalker to use DomainLanguage

- allennlp/tests/training/callback_trainer_test.py
- allennlp/training/callbacks/track_metrics.py
- allennlp/training/callbacks/train_supervised.py
This is a workaround that I am currently using for issue #3001.
Just changed the priorities a bit to make it work.
Another minor fix that I added is to assign trainer.train_metrics instead of update in train_supervised.py.
Originally that was causing cpu memory information to appear in tqdm which made it too long
> Fixes inconsistent resetting of metrics with Validate and TrackMetrics callbacks  (issue #3001)

- allennlp/predictors/semantic_role_labeler.py
This change exposes the Spacy model string in the constructor for the Semantic Role Labeler predictor. 
We currently monkey patch this as we use the large model in spacy and need the tokenization to be consistent.
> Expose the spacy language model for the word splitter in the semantic role label predictor. 

- allennlp/data/iterators/__init__.py
- allennlp/data/iterators/pass_through_iterator.py
- allennlp/tests/data/iterators/pass_through_iterator_test.py
- doc/api/allennlp.data.iterators.rst
This PR adds a new `PassThroughIterator` which tensorizes `Instances` one at a time, and returns them in the exact order that they are created in the `DatasetReader`. It generalizes the `LanguageModelIterator` written by @nelson-liu in #2414, which is specifically designed for the task of contiguous language modeling. Since it seems like this approach is generally useful for problems which apply stateful models to encode long sequences (see discussion #2828), and #2414 is currently blocked by the tangential (and rather thorny) issue #2373, I think it is worth adding this seperately.
The only non-trivial aspect of this iterator is that it needs to remove the batch dimension introduced when calling `Batch.as_tensor_dict()` (since this iterator is intended to be used in situations where …
> PassThroughIterator

- allennlp/training/trainer_pieces.py
no need to iterate through the datasets which will not be used for making vocabulary
> removing unnecessary data iteration in instantiating Vocabulary

- allennlp/tests/training/metrics/boolean_accuracy_test.py
- allennlp/training/metrics/boolean_accuracy.py
> Fix error in BooleanAccuracy when total count is 0

- allennlp/data/fields/multilabel_field.py
- allennlp/tests/data/fields/multilabel_field_test.py
Fixes #2415
Basically we don't check the configuration errors if labels is empty
> Multilabel bug

- allennlp/nn/util.py
- allennlp/tests/nn/util_test.py
Add focal loss to deal with class imbalance
> Add options for focal loss

- allennlp/tests/training/callback_trainer_test.py
- allennlp/tests/training/learning_rate_schedulers/learning_rate_scheduler_test.py
- allennlp/tests/training/trainer_test.py
- allennlp/training/learning_rate_schedulers/learning_rate_scheduler.py
- allennlp/training/scheduler.py
- allennlp/training/trainer.py
- allennlp/training/util.py
Reverts allenai/allennlp#2905
I shouldn't have approved this PR, sorry. It is incorrect for the following reasons:
1. It updates all `learning_rate_schedulers`, not just the `reduce_on_plateau`, which causes `from_params` to fail as there are extra items given to `__init__`.
2. It mutates the `Params` object which is really nasty and made it take a bit of time for me to figure out why this was happening which is bad. We should never accept PRs which do this
3. We should have just pushed this back onto people using allennlp because actually, it's quite hard to mis-configure this and the default is right most of the time
> Revert "Lr scheduler bug"

- allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py
- allennlp/models/semantic_parsing/wikitables/wikitables_erm_semantic_parser.py
- allennlp/models/semantic_parsing/wikitables/wikitables_semantic_parser.py
Earlier we used the final states from the ERM trainer both for training and prediction, but that meant that we could not use interactive beam search on an ERM trained model. The main change in this PR is to use beam search in the ERM model while testing. I confirmed that the dev accuracy of a trained model remains the same after this change.
> Minor WTQ ERM model and  dataset reader fixes for demo

- allennlp/interpret/attackers/hotflip.py
Fix runtime error due to a deprecated function call.
> remove deprecated function call in hotflip

- allennlp/data/fields/metadata_field.py
Unless I'm missing something, I think this was a typo: the overridden method `MetadataField.batch_tensors` was as annotated as a `classmethod` even though it should be a instance-bound method.
> Fix MetadataField.batch_tensors

- allennlp/training/callbacks/log_to_tensorboard.py
- allennlp/training/tensorboard_writer.py
- allennlp/training/trainer.py
This PR addresses #3082 .
Issue: At the end of a training run, pending events are not flushed to disk and tensorboard's event files are not closed properly.
Solution: Call the `close` method of the `SummaryWriter` at the end of the training. I added this call to the "normal" trainer as well as to the callback trainer.
Not sure if the introduced `close` method in the `TensorboardWriter` needs a unit test though.
> Close tensorboard's event files properly at the end of the training

- allennlp/commands/predict.py
This change just helps to make my scripts a bit cleaner. I can control this in the dataset reader but not when using a predictor. I didn't add it to the other part of predict that uses a dataset reader in case someone is doing something like passing in a directory instead of a filename.
> Adding cached_path to input file of the predictor

- allennlp/commands/train.py
- allennlp/tests/training/gan_trainer_test.py
- allennlp/tests/training/multi_task_trainer_test.py
- allennlp/training/callback_trainer.py
- allennlp/training/no_op_trainer.py
- allennlp/training/trainer_base.py
Currently the command line options `--cache-directory` and `--cache-prefix` are only utilized when using the default trainer, so they are ignored when using the callback trainer or any other custom trainer. This fixes that.
> pass cache_directory and cache_prefix to non-default trainers

- allennlp/data/tokenizers/__init__.py
- allennlp/data/tokenizers/character_tokenizer.py
- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
- allennlp/data/tokenizers/tokenizer.py
- allennlp/tests/data/tokenizers/pretrained_transformer_tokenizer_test.py
- doc/api/allennlp.data.tokenizers.rst
- requirements.txt
- setup.py
First (of many) PRs merging our hackathon project into the main repo.  This one adds a dependency on the new `pytorch-transformers` repo, and grabs a tokenizer from there.
This also fills a gap that we had in our data processing API, where there was no good way to get native BERT (or GPT, etc.) tokenization as input to your model - you had to use words, then split them further into wordpieces or byte pairs.  With this tokenizer, you can have wordpieces or byte pairs be your base tokens, instead of words.
> Adding a PretrainedTransformerTokenizer

- allennlp/data/token_indexers/__init__.py
- allennlp/data/token_indexers/pretrained_transformer_indexer.py
- allennlp/data/token_indexers/wordpiece_indexer.py
- allennlp/tests/data/token_indexers/bert_indexer_test.py
- allennlp/tests/data/token_indexers/pretrained_transformer_indexer_test.py
- doc/api/allennlp.data.token_indexers.rst
Second PR getting the hackathon project into the main repo.  This one adds a `TokenIndexer` for pretrained transformers.  This indexer assumes that you're using the corresponding pretrained tokenizer, so we don't have a mismatch between our tokenization and indexing, and things are easy.  There aren't any bells and whistles around windowing or anything, but this should be good enough for now.  This PR depends on #3145, so it shouldn't be reviewed just yet, but I'm getting CI going for it.
> Pretrained transformer indexer

- README.md
Old link returns a 404 now, updating to new doc location
> Fixing Conda download and install link on Readme

- allennlp/models/semantic_role_labeler.py
- allennlp/models/srl_util.py
- allennlp/tests/models/semantic_role_labeler_test.py
- allennlp/tests/training/metrics/srl_eval_scorer_test.py
- allennlp/training/metrics/__init__.py
- allennlp/training/metrics/srl_eval_scorer.py
- doc/api/allennlp.models.rst
- doc/api/allennlp.models.srl_util.rst
#2743 added the SrlEvalScorer, but I didn't actually change the metric used in the `SemanticRoleLabeler` 😅 
This PR has a few things:
- Fixes a circular import between SrlEvalMetric and SemanticRoleLabeler by moving the utility functions for converting between BIO / CoNLL tags to a separate `srl_utils.py` file. Let me know if you want them somewhere else.
- Switch `SemanticRoleLabeler.span_metric` from `SpanBasedF1` to `SrlEvalScorer`.
I'll try actually training this model in a bit, to make sure that nothing broke disastrously. The fact that the tests still work is somewhat promising, though...
> Switch SemanticRoleLabeler metric to SrlEvalScorer.

- allennlp/data/fields/knowledge_graph_field.py
- allennlp/tests/data/fields/knowledge_graph_field_test.py
This pull request handles the issue described in #3138 by adding a default tokenizer for the knowledge_graph_field and includes a test that catches this issue for future builds.
> bug fix for default tokenization of knowledge graph entities

- allennlp/tests/training/metrics/pearson_correlation_test.py
- allennlp/training/metrics/pearson_correlation.py
Fixes #3102. Since the input tensor may be, for example(a batch of label), a tensor ([[0.,0.,0.,0.],
[0.,0.,0.,0. ]), there will be a case where (math.sqrt(predictions_variance) or math.sqrt(labels_variance)) is zero, so a judgment is added here to prevent the denominator from being zero. If it is zero, the denominator is assigned a value of 1.
> Fix pearson correlation.py

- requirements.txt
- setup.py
https://github.com/allenai/allennlp/pull/3145#discussion_r314952073
@matt-gardner
> Set pytorch-transformer to 1.1.0

- allennlp/modules/seq2vec_encoders/bert_pooler.py
Documenting that the BertPooler actually returns just the [CLS] token from the BERT paper, followed by a non-linear transformation.
> Update documentation for bert_pooler.py

- allennlp/nn/initializers.py
In light of discussion on [this issue](https://github.com/allenai/allennlp/issues/3144), modified docstring to include example for initializing weights for all parameters using a pretrained checkpoint without passing named parameters.
> Modify docstring to add example for initializing weights from a pretrained model

- allennlp/common/testing/model_test_case.py
- allennlp/models/biaffine_dependency_parser.py
- allennlp/models/crf_tagger.py
- allennlp/models/graph_parser.py
- allennlp/models/language_model.py
- allennlp/modules/seq2seq_encoders/gated_cnn_encoder.py
- allennlp/modules/token_embedders/bag_of_word_counts_token_embedder.py
- allennlp/nn/util.py
- allennlp/tests/commands/docstring_help_test.py
- allennlp/tests/fixtures/biaffine_dependency_parser_multilang/experiment.json
- allennlp/tests/fixtures/naqanet/experiment.json
- allennlp/tests/models/biaffine_dependency_parser_multilang_test.py
- allennlp/tests/models/reading_comprehension/naqanet_test.py
- allennlp/training/metrics/attachment_scores.py
- allennlp/training/metrics/auc.py
- allennlp/training/metrics/bleu.py
- allennlp/training/metrics/fbeta_measure.py
- requirements.txt
- setup.py
as you can see, this ended up not being that much work. 
there are still two tests failing for me. 
the first is the new "docstring" test, which I don't entirely understand:
```
E               AssertionError: 'usag[1066 chars]tps://\n                        allennlp.s3.am[1452 chars]de\n' != 'usag[1066 chars]tps:/\n                        /allennlp.s3.am[1452 chars]de\n'
E               Diff is 4277 characters long. Set self.maxDiff to None to see it. : The documentation for the subcommand usage in the module allennlp.commands.elmo does not match the output of running `allennlp elmo --help`. Please update the docstring to match the output.
```
the second is `naqanet_test`:
```
Parameter: _question_weights_predictor.bias had incorrect gradient: zeros with shape ((1,))
```
I'll keep …
> upgrade to pytorch 1.2

- allennlp/modules/token_embedders/__init__.py
- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
- allennlp/tests/modules/token_embedders/pretrained_transformer_embedder_test.py
- doc/api/allennlp.modules.token_embedders.rst
This is very simple, because we assume you're using this with a matched tokenizer.  If we want to support mis-matched tokenization, we should have a separate class for that, with clear messaging about when to use each one.
> Add a TokenEmbedder for use with pytorch-transformers

- allennlp/modules/seq2seq_encoders/__init__.py
- allennlp/modules/seq2vec_encoders/__init__.py
This PR adds the `infer_type_and_cast` flags to the seq2seq and seq2vec modules, so we can pass e.g. float param values as strings.
> add infer_type_and_cast flags to seq2seq and seq2vec modules

- allennlp/common/params.py
- allennlp/training/trainer_pieces.py
This pull request is to address #3196.
The problem is there are some classes (Params, TrainerPieces, previously - Vocabulary #2418 ) having factory staticmethods like `from_params` those are hardcoded to return themselves instead of the class they were called on,
which makes us copy the body to the inherited class, the method body can't be reused.
The pull request switches from using `staticmethod`  to `classmethod` to be aware of the context.
While it is not obvious, but sometimes there we need to extend these classes, e.g. we may want custom behaviour of serializing the Params to save additional configs.
> Replace staticmethods with classmethods

- allennlp/data/fields/adjacency_field.py
- allennlp/data/fields/label_field.py
- allennlp/data/fields/metadata_field.py
- allennlp/data/fields/sequence_label_field.py
The `Instance` has a flag for whether or not its fields have been indexed, and our fields are mixed regarding whether or not they have their own check (e.g., `TextFields` always re-index when `index()` is called, while the ones in this PR don't).  I think it makes the most sense to have `Instance` own this, as it gives a user one place to reset the `Instance`, without having to check for all kinds of crazy places to know how to reset things (we need to do this in the interpret code).
This PR makes all `Fields` consistent: when `index()` is called, the field is re-indexed.  It's the `Instance`'s job to make sure this only happens when necessary.
> Make Instance in charge of when to re-index

- allennlp/common/params.py
- allennlp/common/registrable.py
- allennlp/tests/common/params_test.py
- allennlp/tests/common/registrable_test.py
this was an idea that came out of the allennlp summit, basically you can specify types as fully qualified classnames "mypackage.mymodule.readers.MyReader" and then not need to use include-package.
> allow implicit package imports

- allennlp/data/token_indexers/pretrained_transformer_indexer.py
- allennlp/nn/util.py
Two minor fixes: making the `PretrainedTransformerIndexer` comparable to itself, and adding another check for the updated BERT embedding in `find_embedding_layer`.  Both of these are necessary to get targeted attacks for masked LM working in the demo (PR coming to demo repo with this soon).
> Minor fixes for interpret code

- allennlp/models/language_model.py
- allennlp/tests/models/language_model_test.py
Changed `LanguageModel` so that, if there is no backward loss, then no backward loss key is added to the state dict. This was causing an issue when using `Predictor` with trained language models.
Fixes https://github.com/allenai/allennlp/issues/3255.
> Unidirectional LM doesn't return backward loss.

- allennlp/tests/tools/drop_eval_test.py
- allennlp/tools/drop_eval.py
This pull request is to address https://github.com/allenai/allennlp/issues/3262.
The problem was that max_type was updated even if the candidate answer didn't have metrics that maximized both em and f1, due to use of `or` instead of `and`.
> Fix wrong partition to types in DROP evaluation

- allennlp/data/token_indexers/elmo_indexer.py
- allennlp/interpret/attackers/hotflip.py
- allennlp/interpret/attackers/input_reduction.py
- allennlp/interpret/saliency_interpreters/integrated_gradient.py
- allennlp/interpret/saliency_interpreters/simple_gradient.py
- allennlp/interpret/saliency_interpreters/smooth_gradient.py
- allennlp/models/next_token_lm.py
- allennlp/nn/util.py
- allennlp/predictors/predictor.py
- allennlp/tests/predictors/predictor_test.py
This PR has two fixes for the interpret code:
1. When we have to compute a fake embedding matrix for hotflip (e.g., when using ELMo), the vocab size can be so large that the embedding matrix is way too big.  This PR adds a parameter to limit the vocab size, with a default of 5000 (meaning we'll do our hotflip search over only the most frequent 5000 tokens).  For reference, the full BiDAF-ELMo vocab is close to 100,000, so this dramatically cuts down memory usage, such that I can easily fit it in RAM on my laptop.  The cost is a less rich vocab for hotflipping, but I think it still gets the point across, so it's probably ok.
2. It batches the beam search inside of the input reduction code.  This required a few small changes to everything else, because `get_gradients` used to assume that it …
> Reduce hotflip vocab size, batch input reduction beam search

- allennlp/interpret/saliency_interpreters/smooth_gradient.py
Smoothgrad is really slow with 25 samples, speed it up with only 10.
> Reduce number of samples in smoothgrad

- allennlp/models/semantic_role_labeler.py
The URL `https://homes.cs.washington.edu/~luheng/files/acl2017_hllz.pdf` is in the state of 404.
I replace it by the url from ACL Anthology `https://www.aclweb.org/anthology/P17-1044`.
> Replace Invalid Link

- allennlp/state_machines/transition_functions/basic_transition_function.py
I also update self._input_projection_layer = Linear(output_dim + action_embedding_dim, input_dim) to self._input_projection_layer = Linear(encoder_output_dim + action_embedding_dim, input_dim). Though as a matter of fact, output_dim equals encoder_output_dim, using encoder_output_dim is more consistent in this context.
> fix an annotation issue in basic_transition_function.py

- allennlp/data/dataset_readers/reading_comprehension/squad.py
According to docstring of SquadReader the instance's ID should be
accessible as metadata['id'].
> Add question id to MetadataField

- training_config/basic_stanford_sentiment_treebank.json
- training_config/basic_stanford_sentiment_treebank.jsonnet
This is needed for the demo https://github.com/allenai/allennlp-demo/pull/274, to provide a basic training config for training a sentiment analysis model.
> add basic SST training config

- Dockerfile
- Dockerfile.pip
Reverts allenai/allennlp#3236
Reverting--as this breaks a rather brittle test in our CI that tests against Python 3.7.
> Revert "Use a NVIDIA base image"

- allennlp/state_machines/transition_functions/linking_transition_function.py
I think the annotation in line 130 of linking_transition_function.py is not correct. The shape of linked_action_logits should be (num_entities, 1) instead of (num_question_tokens, 1) since we are copying from the entities list (columns, rows, cells, numbers, e.t.c) rather than the question tokens.
> fix an annotation error in linking_transition_function.py

- allennlp/tests/training/metrics/fbeta_measure_test.py
- allennlp/training/metrics/fbeta_measure.py
I also added a check in the `__init__` that labels list cannot be empty and a test for it
> #3335 fixed FBetaMeasure with both average and labels specified

- scripts/ai2_internal/resume_daemon.py
- scripts/ai2_internal/run_with_beaker.py
- Execute w/ `python3 resume_daemon.py` in case the exec bit isn't set.
- Create `~/.allennlp` if it wasn't already in case `allennlp` hadn't been run locally.
- Handle empty crontab case where `crontab -l` has a non-zero exit code.
> Fix several resume daemon bugs.

- requirements.txt
- setup.py
Resolution of https://github.com/allenai/allennlp/issues/3367. Pytorch has fixed their binaries for 1.3.0. Now we'll use 1.3.0.post2.
I've tested this locally on macOS 10.13.6 and both `pip install -r requirements.txt` and `pip install --editable allennlp` fix broken installations.
> Tighten pin to avoid only broken binaries and allow 1.3.0.

- allennlp/training/tensorboard_writer.py
Fixes an issue similar to https://github.com/allenai/allennlp/issues/3116. When a parameter has no elements, do not log its mean. Otherwise, a warning is raised.
> Fix tensorboard logging edge case.

- tutorials/tagger/config_allennlp.py
The return type of the method `forward` should be `Dict[str, torch.Tensor]`, not `torch.Tensor`.
> Fix the annotation for a method's return type

- requirements.txt
Adding the version number for overrides package in requirements to avoid the error reported in issue #3401
> adding version to overrides packages

- allennlp/commands/train.py
- allennlp/tests/training/gan_callback_trainer_test.py
- allennlp/training/callback_trainer.py
- allennlp/training/trainer.py
- allennlp/training/trainer_base.py
This is the second PR after #3372 to bring in distributed training support. Following are the high level changes done:
* Extra params to `TrainerBase`, `Trainer` and `CallbackTrainer` classes to include rank and world_size options
* In a distributed setup, the plan is to run training in sub processes by using `multiprocessing.spawn`. Hence parts of `train_model` function in `train.py` is isolated to a new `_train_worker` function which is invoked as a process
* In this PR, changes for distributed training are still not in. Only the isolation of the above mentioned function is done, to mostly test its correctness when run with existing tests/experiments
~~P.S: Since this is a dependent PR, the changes done for the previous PR is being shown until the older one is merged. I'd be happy to …
> Changes to `train_model` for distributed training support

- allennlp/data/iterators/data_iterator.py
The `epoch_num` field is a MetadataField and hence tensorized as a List[int]. 
The cache_instances branch of the data_iterator was treating it as a Tensor and hence throwing an error.
> fix epoch tracking in cache_instances feature of the iterator

- allennlp/models/crf_tagger.py
- allennlp/modules/conditional_random_field.py
- allennlp/nn/util.py
- allennlp/tests/models/crf_tagger_test.py
- allennlp/tests/modules/conditional_random_field_test.py
- allennlp/tests/nn/util_test.py
Adds a top_k option to `viterbi_decode`, `ConditionalRandomField` and `CrfTagger` 
To maintain backwards compatibility the returned value types are different depending on whether `top_k` is supplied. Another option would be to implement `viterbi_decode` as a thin wrapper around a separate `top_k_viterbi_decode` function. I wasn't sure which was the preferred method.
This can be used for prediction on models serialized before this feature, e.g. by calling `allennlp predict --overrides {"model": "top_k": 10}` I wasn't sure where to document this use case.
The code is based on the implementation at https://gist.github.com/PetrochukM/afaa3613a99a8e7213d2efdd02ae4762 (which is in turn based on AllenNLPs implementation)
> Add top-k sequence decoding

- requirements.txt
I don't think this message is accurate anymore, so I'm deleting it.  I don't think new releases of PyTorch are even compatible with CUDA 8.
> Remove CUDA8 note from requirements.txt

- allennlp/models/srl_util.py
- allennlp/tests/training/metrics/srl_eval_scorer_test.py
This PR fixes unexpected behavior in `write_conll_formatted_tags_to_file` when a verbal predicate is at the beginning of a sentence. Previous code checks whether a sentence has a predicate by `if verb_index:`, but this means that a sentence has no predicate when the predicate is at the beginning of the sentence.
Actually, this error affects the result of `srl-eval.pl`, though I don't know the detail of this script. The added test code did not pass before modifying `write_conll_formatted_tags_to_file`.
Because this fix affects `SrlEvalScorer`, it may be needed to make changes to some model's predictive score provided in https://github.com/allenai/allennlp/blob/master/MODELS.md.
> Fix verb_index condition in write_conll_formatted_tags_to_file

- allennlp/data/vocabulary.py
- allennlp/models/model.py
- allennlp/tests/data/vocabulary_test.py
- allennlp/training/trainer_pieces.py
I added `padding_token` and `oov_token` as parameters of the `Vocabulary` class initialiser.
When using any pre-trained token embedder where OOV and unknown tokens are defined differently (e.g., OOV is `[UNK]` instead of `@@UNKNOWN@@`) this is useful.
Fixes #3434.  Partial fix for #3097.
> Adding padding_token and oov_token as parameters of Vocabulary

- allennlp/data/dataset_readers/seq2seq.py
- allennlp/tests/data/dataset_readers/seq2seq_test.py
`Seq2SeqDatasetReader` has `source_add_start_token` parameter to control whether to add a start token to the source. I added `source_add_end_token` to control whether to add the end token to the source. The default is `True` so it is compatible with previous versions.
> Adding source_add_end_token to Seq2SeqDatasetReader

- allennlp/commands/train.py
- allennlp/common/util.py
- allennlp/models/biattentive_classification_network.py
- allennlp/run.py
- allennlp/training/callback_trainer.py
- allennlp/training/trainer.py
- allennlp/training/trainer_base.py
- allennlp/training/trainer_pieces.py
- allennlp/training/util.py
Followup PR to #3390 and #3372 to bring in distributed training support. Following are the major changes done:
* Workers are spawned using `mp.spawn` and each worker creates its own `Trainer` instance
* `Trainer.__init__` wraps up `self.model` with `DistributedDataParallel`
*  Logging and metric aggregation are already done in the previous PRs
* `Vocabulary` creation in case of distributed training is done before spawning the workers and creating `Trainer` class
To run distributed training, the trainer needs to have the following flag to be enabled:
```jsonnet
{
"trainer": {
"distributed": true,
// ...
}
}
```
TODO:
* Try to reproduce comparable results and share extensive results for existing/selected models
* Check if other commands like `evaluate`, `predict`, `fine-tune` works well …
> WIP: `Trainer` changes for distributed training

- allennlp/training/metrics/srl_eval_scorer.py
After trying to do semantic role labeling on Hebrew files, I noticed that the evaluation crashes due to the files opening with the wrong encoding. This PR fixes the issue.
> Change SrlEvalScorer to use UTF-8 encoded files

- allennlp/data/token_indexers/pretrained_transformer_indexer.py
There is a `KeyError` message in `pretrained_transformer_indexer.py` that appears to be an f-formatted string with broken syntax. This resulted in the literal string `token.text` being printed when the error is raised, instead of the value of the `text` attribute of `token`.
I simply fixed the syntax, so now this error message will print the value of `token.text` to screen when the error is raised.
> Fix an f-formatted string

- tutorials/tagger/README.md
Just a tiny aesthetic change to the markdown of the Getting Started tutorial.
I noticed the code fences for the jsonnet configs specified `json` as the language, which leads to these unsightly red highlights
This is easily solved by specifying the language as `jsonnet`, which is a valid keyword in [linguist](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2540), the [library used by GitHub for syntax highlighting](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).
I also added the `python` keyword to a code fence that appeard to be missing it.
> Update code fences in getting started tutorial

- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
- requirements.txt
- setup.py
During `pip install`, we see this:
```
ERROR: botocore 1.13.36 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
```
Then, at runtime, we see this:
```
dirkg@Dirks-MacBook-Air ~/D/allennlp> allennlp train training_config/bidaf.jsonnet -s output_path
Traceback (most recent call last):
File "/Users/dirkg/miniconda3/envs/allennlp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
ws.require(__requires__)
File "/Users/dirkg/miniconda3/envs/allennlp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
needed = self.resolve(parse_requirements(requirements))
File "/Users/dirkg/miniconda3/envs/allennlp/lib/python3.7/site-packages/pkg_resources/__init__.py", line …
```
> Pins the version of python-dateutil to one that works

- allennlp/commands/train.py
- allennlp/run.py
- allennlp/tests/commands/train_test.py
Add some tests, fix a couple of minor bugs:
- Include packages was the wrong type, so we crashed
- `torch.multiprocessing.set_start_method` needs to be called with a `force` flag, otherwise in some environments it will raise an error.
I tested this on my multi-gpu machine, will run on CI too.
> Dist tests

- pyproject.toml
`pyproject.toml` had a `[tool.poetry]` section that was incomplete. This removes that section and adds a `[build-system]` section that properly instructs any build system using `pyproject.toml` that it should use `setuptools` and `wheel` to build AllenNLP.
This should solve #3504
> Remove [tool.poetry] and add [build-system]

- tutorials/getting_started/using_pretrained_models.md
There were a few dead links (404) in the text. I guess I found out where they are supposed to go.
> Corrected outdated links to models

- allennlp/commands/find_learning_rate.py
- allennlp/commands/fine_tune.py
- allennlp/commands/train.py
- allennlp/common/checks.py
- allennlp/tests/commands/train_test.py
- allennlp/tests/models/simple_tagger_test.py
- allennlp/tests/training/callback_trainer_test.py
- allennlp/tests/training/gan_callback_trainer_test.py
- allennlp/tests/training/trainer_test.py
- allennlp/training/callback_trainer.py
- allennlp/training/callbacks/log_to_tensorboard.py
- allennlp/training/callbacks/validate.py
- allennlp/training/trainer.py
- allennlp/training/trainer_base.py
- allennlp/training/util.py
- `DataParallel` is removed
- `Trainer` and `CallbackTrainer` now take a single cuda device
- `batch_loss` now takes only a single batch, rather than a list (prev required for DataParallel training).
- `trainer._cuda_devices` removed and replaced with `trainer.cuda_device`
- `trainer._multi_gpu` is removed
- Config for distributed training is now read from the top level of the config, rather than the `Trainer`, because it is not explicitly used to construct the `Trainer` object. This means we have to do less config inspection in `allennlp train`, as well as ensuring that `Trainer` configs work with all other commands.
> strip out old DP stuff, ensure multiple cuda devices raises errors

- allennlp/common/util.py
I was dealing with a similar problem of downloading spaCy models programmatically in an internal python package I'm working on. Seeing the way you handled the issue presented in https://github.com/explosion/spaCy/issues/3435 was invaluable in coding up our solution. Since spaCy supports [native imports of their models](https://spacy.io/usage/models#usage-import) (the team even recommends native imports for large projects) and since this method seems to work in the same python session I think using native imports to load the model vs the `link` workaround is a better solution. In fact, I've seen some issues with the `link` workaround on some Windows machines, whereas the native import always seems to work.
Just figured I'd throw this out there since looking at your solution was invaluable …
> import spaCy model module directly instead of forcing a link after download

- allennlp/modules/conditional_random_field.py
- allennlp/tests/modules/conditional_random_field_test.py
Before the fix, viterbi_tags takes a mask as an argument, but it doesn't really use it as a mask - it just truncates the sequence to the number of masked positions: https://github.com/allenai/allennlp/blob/9fa0bde5ce99abf2d5ec12a36366e662241f7099/allennlp/modules/conditional_random_field.py#L392-L400
This commit fixes it and also makes the mask optional.
Tests are modified accordingly.
Fixes https://github.com/allenai/allennlp/issues/3523.
> Fix mask usage in CRF decoding

- allennlp/tests/training/trainer_test.py
- allennlp/training/trainer.py
I re-did gradient accumulation with the distributed trainer.
> Gradient accumulation with the distributed trainer

- allennlp/data/dataset_readers/seq2seq.py
The input argument `file_path` to the `_read` method of `Seq2SeqDatasetReader` was missing a type hint (`str`).
> Add missing type hint

- requirements.txt
This update has no backwards compatible changes, and all tests run clean ([meaning the same four tests fail as without this change](3570)) after this change.
> Update conllu to 2.2

- allennlp/modules/seq2seq_encoders/__init__.py
- allennlp/modules/seq2seq_encoders/compose_encoder.py
- allennlp/tests/modules/seq2seq_encoders/compose_encoder_test.py
- doc/api/allennlp.modules.seq2seq_encoders.rst
I have often faced the problem of wanting to add a "pre-contextualizer" before another kind of `Seq2SeqEncoder`. Currently, it seems the best way to accomplish this is to change a `Model` to have two encoder slots, or to add a nested sub-encoder to the `Seq2SeqEncoder` you are using. Both of these are ad hoc solutions, requiring code modifications as opposed to a simple fix in the configuration file.
In order to solve this problem easily, I created a `ComposeEncoder` that allows you to create a new `Seq2SeqEncoder` out of a sequence of sub-encoders. If you are creating a `LanguageModel` and want to add an LSTM as a pre-contextualizer before `ENCODER`, you can simply write:
```json
"contextualizer": {
"type": "compose",
"encoders": [
{
"type": "lstm",
"input_size": 100,
"hidden_size": 64, …
```
> Add ability to compose Seq2SeqEncoders.

- allennlp/data/token_indexers/pretrained_transformer_indexer.py
- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
- allennlp/tests/data/token_indexers/pretrained_transformer_indexer_test.py
- allennlp/tests/modules/token_embedders/pretrained_transformer_embedder_test.py
Fix this issue https://github.com/allenai/allennlp/issues/3465
I also experimented with the MRPC dataset.
https://github.com/RyujiTamaki/mrpc-allennlp
Results is bellow.
```
2019-12-27 22:08:17,420 - INFO - allennlp.common.util - Metrics: {
"best_epoch": 2,
"peak_cpu_memory_MB": 3267.492,
"peak_gpu_0_memory_MB": 10369,
"peak_gpu_1_memory_MB": 19,
"peak_gpu_2_memory_MB": 19,
"training_duration": "0:01:17.479140",
"training_start_epoch": 0,
"training_epochs": 2,
"epoch": 2,
"training_accuracy": 0.9175637393767705,
"training_loss": 0.20614140655274862,
"training_cpu_memory_MB": 3267.492,
"training_gpu_0_memory_MB": 10369,
"training_gpu_1_memory_MB": 19,
"training_gpu_2_memory_MB": 19,
"validation_accuracy": 0.8505154639175257,
"validation_loss": 0.4683948732339419, …
```
> Use attention_mask in pretrained transformers

- allennlp/modules/span_extractors/self_attentive_span_extractor.py
Remove the unnecessary argument `sequence_mask` in self_attentive_span_extractor.py
Fixes https://github.com/allenai/allennlp/issues/3565
> Remove `sequence_mask` in self_attentive_span_extractor.py

- allennlp/data/dataset_readers/universal_dependencies.py
- allennlp/data/dataset_readers/universal_dependencies_multilang.py
This changed in conllu==1.0 (https://github.com/EmilStenstrom/conllu/wiki/Migrating-from-0.1-to-1.0#parsing-of-ids-now-include-ranges-and-decimals) which is what allennlp uses since 9db0042. I must have missed this when doing the last update over 6 months ago.
(It might be a good idea to see if it's possible to unify universal_dependencies.py and universal_dependencies_multilang.py, since they have duplicate code in them)
>  Filter by int instead of None to remove elided tokens

- allennlp/modules/attention/additive_attention.py
- allennlp/modules/attention/bilinear_attention.py
- allennlp/modules/attention/linear_attention.py
- allennlp/modules/augmented_lstm.py
- allennlp/modules/conditional_random_field.py
- allennlp/modules/drop_connect.py
- allennlp/modules/feedforward.py
- allennlp/modules/highway.py
- allennlp/modules/matrix_attention/bilinear_matrix_attention.py
- allennlp/modules/matrix_attention/linear_matrix_attention.py
- allennlp/modules/maxout.py
- allennlp/modules/sampled_softmax_loss.py
- allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py
- allennlp/modules/seq2seq_decoders/seq_decoder.py
- allennlp/modules/seq2seq_encoders/gated_cnn_encoder.py
- allennlp/modules/seq2seq_encoders/intra_sentence_attention.py
- allennlp/modules/seq2vec_encoders/bert_pooler.py
- allennlp/modules/seq2vec_encoders/boe_encoder.py
- allennlp/modules/seq2vec_encoders/cnn_encoder.py
- allennlp/modules/seq2vec_encoders/cnn_highway_encoder.py
- allennlp/modules/span_extractors/bidirectional_endpoint_span_extractor.py
- allennlp/modules/span_extractors/endpoint_span_extractor.py
- allennlp/modules/stacked_alternating_lstm.py
- allennlp/modules/stacked_bidirectional_lstm.py
- allennlp/modules/token_embedders/bert_token_embedder.py
- allennlp/modules/token_embedders/embedding.py
- allennlp/modules/token_embedders/pass_through_token_embedder.py
I formated docstrings so that sphinx can recognize arguments and types separately. 
```python 
class ClassName: 
"""
arg1: ``int``, required 
explanation of argument 1 
arg2: ``str``, optional (default = None)
explanation of argument2
"""
def __init__(self, arg1: int, arg2: str = None): 
pass
```
On documentation, this modification will be reflected like [this](https://allenai.github.io/allennlp-docs/api/allennlp.modules.elmo.html#allennlp.modules.elmo.Elmo).
Previously, some classes had troubles on documentations like 
```
arg1int
arg2str
```
These were caused by below docstrings
```python
class ClassName
"""
Parameters
----------
arg1 : int 
arg2 : str
"""
def __init__(self, arg1: int, arg2: str = None): 
pass
```
1. Don't add whitespace between argument name and type 
2. Wrap type name …
> add double backquotes on doc strings 

- allennlp/common/util.py
- allennlp/training/trainer_pieces.py
- One can't call `distributed.is_initialized()` if `not distributed.is_available()`.
- This caused test failures on macOS High Sierra.
> Be robust to not having torch.distributed.

- allennlp/data/iterators/bucket_iterator.py
- allennlp/tests/data/iterators/bucket_iterator_test.py
In refactoring the TokenIndexer stuff, I had to change how padding keys are determined, to make things a bit more sane.  That change makes figuring out which keys to use even more annoying than it was.  As I was thinking of how to fix that, it occurred to me that we could just guess which key to use and be right basically every time, by just finding the padding key with the longest value.
One potential failure case is when you have a large embedding matrix that's preprocessed (e.g., spacy vectors) and we use that length instead of the number of tokens, or something.  That's a rare case, and we could still handle it by taking the top k keys instead of the top 1, as the top one should be equal for all instances.
I guess we could detect variance of the keys and use that instead of just the …
> Guess sorting keys when none are given to BucketIterator

- setup.py
See the discussion at https://github.com/allenai/allennlp/pull/3509.
This is uncomfortable. The root problem was a bug in `pip`. This undoes the workaround. The workaround breaks the library for people like @AlJohri, but without the workaround, people with an old version of boto are broken.
On balance, I think it's more important to have this work for future versions than for past ones, so I'm removing the workaround.
> Unpins the version of datautil

- dev-requirements.txt
> Remove pypandoc

- allennlp/training/optimizers.py
The minimum PyTorch version is now 1.2.0, so keeping this code doesn't make sense.
> Remove code for a previous PyTorch version

- .bulldozer.yml
I hope that this tool will help address the problem where we want to merge a PR after we update master, but forget to check back.  With `bulldozer` we just add the `merge when ready` label and it will merge the PR automatically after all the CI tests are green.
I enabled bulldozer for `allenai/allennlp` but I don't think it will do anything until we merge in a `.bulldozer.yml`.
> Add bulldozer configuration to allennlp.

- allennlp/data/token_indexers/pretrained_transformer_indexer.py
- allennlp/data/token_indexers/pretrained_transformer_mismatched_indexer.py
- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
- allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
- allennlp/nn/util.py
- allennlp/tests/data/token_indexers/pretrained_transformer_indexer_test.py
- allennlp/tests/data/token_indexers/pretrained_transformer_mismatched_indexer_test.py
- allennlp/tests/modules/token_embedders/pretrained_transformer_embedder_test.py
- allennlp/tests/modules/token_embedders/pretrained_transformer_mismatched_embedder_test.py
Split, independently embed, and finally concatenate back to get to original sequence representation.
> Support splitting long sequences into multiple segments for transformers

- allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py
I noticed that the annotations for `target_tokens` in `AutoRegressiveSeqDecoder` could/should be swapped from `Dict[str, torch.Tensor]` to the newer `TextFieldTensors`.
I also saw a few places where `target_tokens["tokens"]["tokens"]` could/should be replaced with the new `allennlp.nn.util.get_token_ids_from_text_field_tensors(...)` function.
I hope this is helpful.
> Fix AutoRegressiveSeqDecoder annotations and refactor to use get_token_ids_from_text_field_tensors

- allennlp/interpret/attackers/hotflip.py
- allennlp/tests/interpret/hotflip_test.py
I'm working on fixing breakages in allennlp-reading-comprehension, and this came up.  I need to fix this here in order for tests to pass there (and I added a test here that would have caught the issue in this repo).
> Fix handling of TokenCharactersIndexer in Hotflip

- allennlp/data/dataset_readers/coreference_resolution/conll.py
- allennlp/data/token_indexers/pretrained_transformer_indexer.py
- allennlp/data/token_indexers/pretrained_transformer_mismatched_indexer.py
- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
- allennlp/tests/data/dataset_readers/coreference/coref_reader_test.py
- allennlp/tests/data/dataset_readers/dataset_utils/ontonotes_test.py
- allennlp/tests/data/token_indexers/pretrained_transformer_indexer_test.py
- allennlp/tests/data/tokenizers/pretrained_transformer_tokenizer_test.py
- allennlp/tests/fixtures/coref/coref.gold_conll
Add label distribution logic to Conll dataset reader and move some logic to `PretrainedTransformerTokenizer` for better reuse.
> Add label distribution logic to coref

- allennlp/common/file_utils.py
- allennlp/tests/common/file_utils_test.py
I want to use this in https://github.com/allenai/allennlp-reading-comprehension/pull/19.
Once this got promoted to being a general utility, I had to take care of some differences in the default arguments to `open` and `gzip.open`. Hence the extra parameters.
> Adds a utility function to open potentially compressed files

- setup.py
`roberta-large` in the `transformers` library has some bugs involving token type ids. They are fixed in 2.4.0 and above.
I'm getting the feeling I'm the only person in the world using token type ids for anything.
> New transformers version

- allennlp/common/util.py
According to the discussion in #2167 , there are known occasional failures in this non-critical function.
Log as a warning with the stack trace and error information.
> Update gpu_memory_mb() not to log at error level

- allennlp/tests/fixtures/coref/coref_bert_lstm_small.jsonnet
- allennlp/tests/models/coreference_resolution/coref_test.py
- training_config/coref_bert_lstm.jsonnet
E2E-coref + `bert-base-uncased`. Keeping LSTM. Limited hyperparameter tuning.
Trained model at https://storage.cloud.google.com/allennlp-public-models/coref-bert-lstm-2020.02.04.tar.gz
> Add coref + bert training config

- allennlp/commands/find_learning_rate.py
- allennlp/common/params.py
- allennlp/data/dataset_readers/text_classification_json.py
- allennlp/models/archival.py
- allennlp/models/model.py
- allennlp/training/util.py
Remove the `, None)` part when calling `.get(..., None)` in a dictionary or `Params`.
It improves readability and it's the default value.
> Remove default None in dict get calls

- .github/workflows/nightly.yml
- allennlp/tests/commands/find_learning_rate_test.py
- allennlp/version.py
- scripts/24hr_diff.sh
This actually turned out to be not so hard, but it requires a couple of changes:
1. I need to change `allennlp/version.py` to look for an environment variable when setting the version, so I can change it to `MAJOR.MINOR.GITSHA` for the nightly versions
2. It requires adding our release details for pypi to github secrets
I didn't use TC for this because I thought it might be helpful to be able to generalise this across all of the allennlp* packages eventually, and it's easier for outside maintainers to see what is happening. 
I'll need to merge this before I actually know whether it works or not, but equally the nightly releases are a good place to test this functionality before we try using it for our proper releases. LMK what you think.
For our proper releases, we can configure these to …
> test out github actions for automated nightly releases

- .github/workflows/nightly.yml
- dev-requirements.txt
Turns out that you need the `wheel` package installed to build wheels, which we never knew because we did our builds in non-automated python environments 🤷‍♂
> add missing dependencies for build

- allennlp/modules/seq2seq_encoders/compose_encoder.py
- allennlp/tests/modules/seq2seq_encoders/compose_encoder_test.py
- allennlp/tests/nn/util_test.py
- allennlp/tests/training/metrics/spearman_correlation_test.py
- scripts/ai2_internal/resume_daemon.py
- scripts/pylint.sh
`pylint` isn't used anymore, so I removed references to it.
> Remove occurrences of 'pylint'

- .github/workflows/nightly.yml
**TL;DR:** the nightly build GH action is failing because PyPI doesn't accept the suffix "+commit-sha". This patch fixes it.
<details>
<summary>Longer explanation</summary>
If you do `python setup.py check` with the nightly build version with the `ALLENNLP_VERSION_SUFFIX` used in the file, it's gonna say it's correct. If you check it with the [2nd regex in PEP 440 Appendix B](https://www.python.org/dev/peps/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions), it will also be fine. However, if you check it with the first one, you'll see it's not gonna be "canonical". There it says:
> As noted earlier in the _Public version identifiers_ section, published version identifiers SHOULD use the canonical format.
Versions that have a `+something` are called in [PEP 440 "local …
> Fix the nightly build version number

- allennlp/modules/seq2seq_encoders/__init__.py
- allennlp/modules/seq2vec_encoders/__init__.py
These __init__ files shouldn't offer these imports if they don't use them, they should just offer whatever is inside their folders.
> Remove some unused imports

- MANIFEST.in
I found one in the latest stable version.
Btw, "scripts", "training_config" and "tutorials" aren't being part of the packaging. Should those be removed as well?
> Exclude .DS_Store files from the Pip package

- allennlp/models/coreference_resolution/coref.py
- allennlp/models/encoder_decoders/copynet_seq2seq.py
- allennlp/models/encoder_decoders/simple_seq2seq.py
- allennlp/models/semantic_role_labeler.py
- allennlp/modules/elmo.py
- allennlp/modules/sampled_softmax_loss.py
- allennlp/modules/span_extractors/bidirectional_endpoint_span_extractor.py
- allennlp/modules/span_extractors/endpoint_span_extractor.py
- allennlp/modules/token_embedders/embedding.py
- allennlp/tests/common/registrable_test.py
- allennlp/tests/modules/seq2seq_decoders/auto_regressive_seq_decoder_test.py
- allennlp/tests/modules/token_embedders/embedding_test.py
Following up on #3763.  Turns out the problem was just a mismatch between expected names.  The model was passing something called `vocab`, and the argument name in your original commit was `vocabulary`.  It's a bit magical to find this error, and unfortunate that we don't have better error handling here, but I'm not sure how to make this better.  The good news is that it's not magical if you're not using config files, and this change makes it easier to do that.
> Remove embedding from params

- allennlp/data/dataset_readers/coreference_resolution/conll.py
- allennlp/data/dataset_readers/coreference_resolution/preco.py
- allennlp/data/dataset_readers/coreference_resolution/util.py
- allennlp/tests/data/dataset_readers/coreference/coref_reader_test.py
Sometimes the documents are very long which creates memory issues when using large models and large representations. This option allows sampling a subset of sentences for each document. It should be used during training only.
> Allow specifying max_sentences in coref readers

- allennlp/common/from_params.py
We don't need this much verbose logging, especially now that we don't have custom `from_params` methods anymore.
> Make instantiation logging in FromParams use debug instead of info

- allennlp/training/tensorboard_writer.py
Fix for issue #3841 
Create tensorboard directories explicitly to avoid race condition in distributed training.
> Avoid race condition in tensorboard directory creation

- allennlp/predictors/coref.py
Reverts allenai/allennlp#3786. This was fixed more fundamentally in #3808 . So we are rolling this back to be able to discover similar underlying bugs in the future.
> Revert "Fixes contiguous whitespaces causing coref model to produce bad results"

- allennlp/data/samplers/samplers.py
[In multiple inheritances in Python, the first superclass has priority in defining a method.](https://stackoverflow.com/questions/21657822/python-and-order-of-methods-in-multiple-inheritance) I was subclassing `BasicBatchSampler` without defining `__iter__` and I got an exception because `BatchSampler.__iter__` got called.
> Fix samplers inheritance order

- allennlp/models/coreference_resolution/coref.py
- allennlp/tests/models/coreference_resolution/coref_test.py
- allennlp/training/metrics/conll_coref_scores.py
- training_config/coref_spanbert_large.jsonnet
Based on https://arxiv.org/pdf/1804.05392.pdf. 79.17 dev 78.87 test. URL: https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz
SpanBERT reports 79.6 on test. According to the e2e-coref paper, speaker and genre metadata, which we aren't using, contributes 1.4 F1. So I assume that's where the difference is coming from.
> Add coarse-to-fine and second order inference for coref. Also a new coref config

- allennlp/data/dataset_readers/snli.py
- allennlp/tests/data/dataset_readers/snli_reader_test.py
- training_config/mnli_roberta.jsonnet
- training_config/snli_roberta.jsonnet
SNLI: dev 92.47, test 91.65, URL https://storage.googleapis.com/allennlp-public-models/snli-roberta-large-2020.02.27.tar.gz
MNLI: dev-matched 89.10, dev-mismatched 88.71, URL https://storage.googleapis.com/allennlp-public-models/mnli-roberta-large-2020.02.27.tar.gz
> Add NLI models

- allennlp/training/trainer.py
The tqdm progress bar in training is shown twice because there's a log "Training" in the middle. So moved it before the tqdm object is created.
> Show "Training" before tqdm

- allennlp/tests/training/trainer_test.py
- allennlp/training/trainer.py
- dev-requirements.txt
This PR enables automatic mixed precision training with NVIDIA's [Apex](https://nvidia.github.io/apex/index.html) which has been much discussed in #2149 and is one of the action items on the [roadmap](https://github.com/allenai/allennlp/blob/master/ROADMAP.md).
The modifications were very straightforward. Here is the high-level:
1. Add argument `opt_level` to `Trainer`. This coincides with the [opt levels of Apex](https://nvidia.github.io/apex/amp.html#opt-levels).
2. In the constructor of `Trainer`, if `opt_level is not None`, wrap `self.model` and `self.optimizer` with `amp.initialize`.
3. `rescale_gradients` needs to be modified slightly when using Apex. See [here](https://nvidia.github.io/apex/advanced.html#gradient-clipping) for more info.
4. In `_train_epoch`, `if opt_level is not …
> Enable AMP with Apex

- allennlp/data/fields/adjacency_field.py
- allennlp/data/fields/array_field.py
- allennlp/data/fields/field.py
- allennlp/data/fields/index_field.py
- allennlp/data/fields/label_field.py
- allennlp/data/fields/multilabel_field.py
- allennlp/data/fields/namespace_swapping_field.py
- allennlp/data/fields/span_field.py
- allennlp/data/samplers/bucket_batch_sampler.py
- allennlp/tests/common/params_test.py
- allennlp/tests/data/samplers/bucket_batch_sampler_test.py
- allennlp/tests/fixtures/coref/coref_bert_lstm_small.jsonnet
- allennlp/tests/fixtures/simple_tagger/experiment.json
- docs/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt1.md
- training_config/coref_bert_lstm.jsonnet
- training_config/coref_spanbert_large.jsonnet
- training_config/stanford_sentiment_treebank_roberta.jsonnet
- tutorials/tagger/exercise.jsonnet
- tutorials/tagger/experiment.jsonnet
Fixes #3664 
Radical idea for sorting instances - we don't call `get_padding_lengths` at all.
Instead, we just specify what fields we want to sort by, and implement `__len__` for all fields.
I'm pretty sure this has zero downsides, and many upsides:
1. Bucketing now no-longer requires the instances to be indexed, which is a potentially expensive operation.
2. Configs are simpler, because you just pass the name of the field you want to sort by.
3. There are cases for which `len(field)` doesn't correspond directly to what will be padded - e.g wordpiece tokenizers may cause this to be slightly different. We should be willing to gamble that sentence length and wordpieced sentence length are highly correlated in the general case, and so bucketing like this is actually fine.
The only edge case …
> Sorting keys api

- allennlp/tests/training/trainer_test.py
Fix https://github.com/allenai/allennlp/pull/3866#issuecomment-593707746. This should fix the GPU tests in master.
The problem is that amp can change PyTorch's state. Then, after running an amp test, the rest of the tests that run along get affected. I used `pytest.mark.spawn` so the amp test runs in its own subprocess, not affecting the main one. I copied the idea from PyTorchLightning/pytorch-lightning#661.
Apex's amp does a lot of monkey patching, and as far as I understand, there's only one flag that affects PyTorch itself (as opposed to just affecting the models and optimizers, that I don't consider a secondary effect), which is `patch_torch_functions` (or when `opt_level==O1`). It wraps a lot of PyTorch functions based on several criteria, leaving the patches there. And it makes …
> Fix trainer tests in GPU

- allennlp/tests/training/trainer_test.py
Hey ya'll,
So I ran into a bunch of issues running the trainer tests after installing Apex. After debugging, I realized this was because the trainer test that uses Apex modifies the model itself, and so every non-Apex test that ran after the Apex test would be using the modified model, which would cause them to fail.
So this PR just refactors the trainer tests so that the Apex test runs with it's own model, vocab, data, etc.
> Fix trainer tests when Apex installed

- scripts/build_docs.py
Related to https://github.com/allenai/allennlp/issues/3917
This speeds up docs generation from 1165s (20 minutes) to 6s for a 194x speedup.  The code has some gnarly workarounds for the fact that the code in `mathy_pydoc` is not very modular (the main method reads from the args directly and writes directly to stdout).
> Speed up docs generation.

- mkdocs.yml
- scripts/build_docs.py
- scripts/build_docs.sh
https://github.com/allenai/allennlp/pull/3916 didn't fix https://github.com/allenai/allennlp/issues/3914 because a default value is set when `repo_url` is set.  See https://www.mkdocs.org/user-guide/configuration/.
> On a few known hosts (specifically GitHub, Bitbucket and GitLab), the edit_uri is derived from the 'repo_url' and does not need to be set manually. Simply defining a repo_url will automatically populate the edit_uri configs setting.
> Remove the edit link from the docs.

- README.md
- docs/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt1.md
- docs/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt2.md
- docs/tutorials/getting_started/walk_through_allennlp/configuration.md
- docs/tutorials/getting_started/walk_through_allennlp/creating_a_model.md
- tutorials/README.md
- tutorials/tagger/README.md
Switches URLs from `allenai.github.io/allennlp-docs` to `docs.allennlp.org/master`.
> Use docs.allennlp.org for documentation URLs.

- .github/workflows/nightly.yml
The check was checking if the owner of the repo was equal to the string "repo-owner". Also, switched to checking the full repo name instead of just the owner being allenai for clarity. I tested it on my fork, not really any other way to test github actions that I'm aware of other than pushing it and seeing what happens.
Fixes #3931
> Fix repo check for nightly build

- allennlp/models/biattentive_classification_network.py
- allennlp/models/coreference_resolution/coref.py
- allennlp/models/encoder_decoders/copynet_seq2seq.py
- allennlp/models/esim.py
- allennlp/models/graph_parser.py
- allennlp/modules/attention/cosine_attention.py
- allennlp/modules/bimpm_matching.py
- allennlp/modules/layer_norm.py
- allennlp/modules/masked_layer_norm.py
- allennlp/modules/matrix_attention/cosine_matrix_attention.py
- allennlp/modules/sampled_softmax_loss.py
- allennlp/modules/scalar_mix.py
- allennlp/modules/seq2seq_encoders/bidirectional_language_model_transformer.py
- allennlp/nn/util.py
- allennlp/tests/modules/masked_layer_norm_test.py
- allennlp/tests/modules/scalar_mix_test.py
- allennlp/tests/nn/util_test.py
- allennlp/training/callbacks/log_to_tensorboard.py
- allennlp/training/trainer.py
- allennlp/training/util.py
We currently use a lot of extremely positive/negative/tiny for special values in masked operations. However these cause overflow/underflow with AMP. So this PR changes them to unified constants depending on the dtype.
> Fix special values overflow/underflow for amp

- allennlp/tests/training/learning_rate_schedulers/cosine_test.py
- allennlp/tests/training/learning_rate_schedulers/learning_rate_scheduler_test.py
- allennlp/tests/training/learning_rate_schedulers/slanted_triangular_test.py
- allennlp/tests/training/momentum_schedulers/inverted_triangular_test.py
- allennlp/tests/training/trainer_test.py
- allennlp/training/learning_rate_schedulers/learning_rate_scheduler.py
- allennlp/training/learning_rate_schedulers/noam.py
- allennlp/training/learning_rate_schedulers/slanted_triangular.py
- allennlp/training/scheduler.py
- allennlp/training/trainer.py
closes #3922 
We might also want to consider removing the `batch_num_total` parameter in `Scheduler.step_batch`, as I think that's equally unnecessary.
This does change the behavior of the `ExponentialLearningRateScheduler`, but I believe the change is actually a fix, i.e. it makes this LR scheduler behave how it was intended (the LR will now be updated after the first epoch, whereas before it would only start updating after the second epoch).
> Remove unnecessary epoch param in Scheduler.step()

- allennlp/common/util.py
This commit does the padding in a more pythonic way which significantly improves the speed.
A preliminary benchmark on my own dataset and model:
The original version:
new version:
The second column is the call count. The third is the execution time and the percentage. The forth is the execution time of `pad_sequence_to_length` excluding the functions it calls 
I think the difference is mainly due to that doing  lots of insertion and append is expensive.
> pads in a more pythonic way which is significantly faster.

- allennlp/training/tensorboard_writer.py
- allennlp/training/trainer.py
Just moving things around, to have less logic inside of `Trainer`, and making it easier to customize what happens in tensorboard logging, if you want.
This fixes another part of #3913, specifically all of part 3 up to the "question".  I'm thinking at this point that the answer to the "question" should be to not worry about changing the tensorboard writer at all, but instead add two callbacks: a `BatchCallback`, and an `EpochCallback`, that are given appropriate objects that a person can do whatever they want with.  By default we do nothing.  This adds very little complexity to our code, but gives people a lot of flexibility to customize things.
> Move Tensorboard logic into TensorboardWriter

- allennlp/data/fields/__init__.py
- allennlp/data/fields/flag_field.py
- allennlp/models/crf_tagger.py
- allennlp/models/simple_tagger.py
- allennlp/predictors/sentence_tagger.py
- allennlp/tests/data/fields/flag_field_test.py
I finally figured out why our NER interpret demo never worked as well as the original implementation that was used when @Eric-Wallace created his video.  Somehow the loss masking code never got checked in, so we were computing the loss for the whole sequence.  As that includes "O" tags that were intentionally changed away from predicted NER tags, the loss for those tags was quite high, and dominated the loss computation, so the result was basically the opposite of what we wanted.
This PR adds the ability to mask the loss computation in our CRF model, so that the loss is only calculated on non-O tags.  In order to set this flag at interpretation time, but not any other time, I added a `FlagField` that batches as a single (in this case boolean) value that gets passed to the model, and I …
> Allow CRF to compute loss just for single span prediction

- allennlp/data/dataset.py
It was deprecated a long time ago, and now with `AllenNlpDataset` existing, it's misleading.  It should be removed before 1.0.
> Remove dataset.py

- allennlp/data/fields/flag_field.py
I didn't add this method when I first implemented `FlagField`, because I didn't know what it was for and thought it was unnecessary.  Then I looked at the bucket sampler code and realized that we needed this.  I'm a bit unhappy that our CI didn't warn me about an unimplemented abstract method - pylint would have done that.  Oh well.
> Add __len__ to FlagField

- allennlp/data/samplers/bucket_batch_sampler.py
- allennlp/tests/data/samplers/bucket_batch_sampler_test.py
In writing a chapter for the allennlp course, I trained a model and discovered that the batches were not shuffled when using the `BucketBatchSampler`, so the model was seeing shortest instances first, then longer instances.  This isn't great from a learning standpoint.  This PR fixes that issue.
> Shuffle batches in bucket sampler

- allennlp/tests/models/simple_tagger_test.py
- allennlp/training/trainer.py
- allennlp/training/util.py
As #2300 was tagged with ``Good First Issue``  - there is PR extracting regularization loss to separate metric (also checked in unit test).
I wasn't able to come up with better idea than wrapping ``get_regularization_penalty`` value in ``batch_outputs`` (as there isn't any device information in model).
I'm happy to address issues.
> Add separate logging for regularization loss.

- allennlp/common/util.py
ALBERT uses "▁" to denote the start of a wordpiece in their vocabulary. Adding this has enabled the support for ALBERT models when using `PretrainedTransformerTokenizer`.
> Add sanitize_wordpiece for ALBERT

- allennlp/models/model.py
- allennlp/modules/token_embedders/embedding.py
There were to issues in my last PR that threw errors when loading a model trained with amp:
-  a misspelling of the `amp.initialize` method in my last PR (#3992). This caused an error when trying to load a model trained with `amp` (I also found the word initialize misspelled in a docstring so I fixed that as well).
- the code that moves the loaded model to GPU was moved to before the call to `amp.initialize`, otherwise, it will throw an error.
> Fix amp initialize issues in Model._load

- allennlp/data/dataset_readers/dataset_reader.py
This PR addresses #3924 by decoupling the `instance_generator` argument to `_LazyInstances` into two arguments: `instance_generator` and `file_path`. Intead of passing a `lambda: self._read(file_path),` to `_LazyInstances` in `DatasetReader`, we now pass `self._read` and `file_path`, and `_LazyInstances` just calls: `self._read(filepath)`.
I tested that this fixes #3924 by training in distributed mode with a lazy dataset reader.
Thanks to @matt-gardner for the solution.
Closes #3924.
> Decouple generator and filepath to fix pickle bug

- allennlp/data/dataset_readers/text_classification_json.py
- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
- allennlp/modules/elmo_lstm.py
- allennlp/modules/input_variational_dropout.py
- allennlp/modules/lstm_cell_with_projection.py
- allennlp/modules/stacked_alternating_lstm.py
- allennlp/modules/stacked_bidirectional_lstm.py
- allennlp/nn/beam_search.py
- allennlp/nn/util.py
- allennlp/predictors/predictor.py
- allennlp/training/trainer.py
Addresses some parts of #3630.
External urls in parameters sections are not rendering correctly (i.e. http://docs.allennlp.org/master/api/modules/stacked_alternating_lstm/). I have used reference style links (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) to avoid that.
Also fixed some broken links in "regular" places.
> Fix some external url formatting.

- Makefile
- dev-requirements.txt
- scripts/build_docs.sh
- scripts/py2md.py
A few things:
- tweaks the Makefile to make sure all of the API docs are re-built whenever the `scripts/py2md.py` file changes.
- runs `make clean` before `make build-docs` in `scripts/build-docs.sh` to ensure the docs are built from scratch in CI.
- avoids shelling out to Python multiple times when building docs from scratch. Several orders of magnitude faster now.
> ensure all API docs rebuilt when script changes, and always build from scratch in CI

- .github/workflows/main.yml
The docs ended up being pushed to a directory named `refs/head/master` instead of just `master`.
> Fix docs output directory

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
This separates the workflow that is ran on pull requests from the one that is ran on master commits and releases.
The benefit of this is that **only the relevant jobs will show up on pull requests** instead of all jobs (most of which are skipped). The downside is that two of the jobs need to be duplicated across the workflows.
I definitely don't like duplicated configs, but I also don't like having so many jobs showing up on pull requests. I imagine that would be a source of confusion for contributors.
Also @bryant1410 this covers the `pip install -e . -r dev-requirements.txt` optimization you pointed out.
> Simplify pull request workflow

- README.md
Also matches the formatting of the logo with what's in allennlp-models and adds a badge for PyPI.
> Update README with new CI links / badge

- .github/workflows/master.yml
- Makefile
This will run Sunday through Thursday night. It runs through the same workflow as a usual release except that the docs and docker images are not updated.
> Add nightly release schedule back

- .github/workflows/master.yml
This will allow more jobs to run in parallel, leading to a speed up in the overall workflow.
> Simplify GitHub Actions job graph

- .github/workflows/master.yml
I think it's good to always have a 'latest' tag. I was also going to try Docker layer caching here but I think I'll put that in another PR.
> Push 'latest' tag versions of Docker images

- README.md
Fix broken link pointing to GitHub Actions in README
> Fix broken link pointing to GitHub Actions

- Makefile
Ugh, somehow fix # 2 still didn't do it
> ensure typing backport uninstalled first

- allennlp/commands/elmo.py
- allennlp/commands/train.py
- allennlp/common/logging.py
- allennlp/common/tee.py
- allennlp/common/util.py
Closes #3785 and also ensures tqdm logged to file.
The solution just patches `sys.stdout` and `sys.stderr` with our own `TeeHandler` class.
@OyvindTafjord pinging you so you can give this a review as well
**With `--file-friendly-logging`**
**Without `--file-friendly-logging`**
And in both cases the `stderr.log` looks like this:
- Relies on patching `sys.stdout` and `sys.stderr`. This is scary.
- The tqdm progress bars are not as pretty. Compare the output above to the status bars before this PR:
We can partially fix this by setting `ascii=False` when initializing the Tqdm instance. With that, it looks like this:
But it's still not as pretty because it doesn't take up the entire terminal width.
> Fix logging

- allennlp/training/learning_rate_schedulers/learning_rate_scheduler.py
It's probably a bug.
I see `threshold_mode` as a param of `__init__` of `ReduceOnPlateauLearningRateScheduler`, but it misses in the initializer of `torch.optim.lr_scheduler.ReduceLROnPlateau`.
I found this problem in my experiment, by observing exceptional learning rate decay, and further found that the `threshold_mode` of `ReduceOnPlateauLearningRateScheduler.lr_scheduler` is always equal to "rel", even I had set `threshold_mode = 'abs'`.  
If this is not intended, then it's probably an oversight.
> add missing param `threshold_mode`

- Makefile
I feel like with `-v` it takes more effort to figure out what the issue is when one of the linters complains. For example, in [this run](https://github.com/allenai/allennlp/pull/4175/checks?check_run_id=633723168) you have to scroll up throw the output just to find which file black is complaining about.
> remove verbose mode of linters

- .github/workflows/pull_request.yml
This will also help verify that dev dependency upgrades don't break the doc building process: https://github.com/allenai/allennlp/pull/4174
> Ensure docs can build in PR workflow

- allennlp/nn/util.py
I was diagnosing an error in the interpret code for a scibert NER model, and found this.  Comments in the code should explain the problem and solution well enough, let me know if they don't.
> Find the right embedding layer for mismatched cases

- .github/workflows/master.yml
Adds a condition to only run GPU checks on main repo and PRs to main repo so that the workflows will work for forks that have GitHub Actions enabled.
> update GPU checks CI

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- CONTRIBUTING.md
- Makefile
I think it's more clear if we separate flake8 linting from black formatting into two separate steps of the CI workflow. This also ensures all steps of the "Check Core" workflow run even if one fails.
> Separate linting from formatting in CI, always run all steps of workflow

- allennlp/data/token_indexers/pretrained_transformer_indexer.py
The `pretrained_transformer_mismatched` has a mask called `wordpiece_mask`, but calls into `pretrained_transformer.as_padded_tensor_dict` which doesn't properly default to `BoolTensor` for this mask. I'm not certain this is the right fix, but I ran into this with a `ListField[TextField]` getting padded with empty `TextField`s, and this fixes it for me so thought I would offer a PR.
> Add wordpiece_mask to default to bool tensor

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- Makefile
- Uses correct naming convention. Image tag = "latest", image name = "allennlp/allennlp:latest", for example
- Doesn't push "latest" tag for commit images, since if a previous workflow was re-ran, it would override the "latest" image.
> improve Docker workflows

- allennlp/common/testing/__init__.py
- allennlp/common/testing/test_case.py
- allennlp/tests/commands/find_learning_rate_test.py
- allennlp/tests/commands/train_test.py
- allennlp/tests/modules/encoder_base_test.py
- allennlp/tests/training/trainer_test.py
@dirkgr, this should clean up how we mark that a test requires one or more GPUs. I'll follow up with a similar PR on allennlp-models.
> consolidate GPU testing decorators

- allennlp/commands/find_learning_rate.py
- allennlp/common/params.py
- allennlp/common/tqdm.py
- allennlp/common/util.py
- allennlp/data/fields/metadata_field.py
- allennlp/data/instance.py
- allennlp/data/vocabulary.py
- allennlp/interpret/attackers/utils.py
- allennlp/tests/modules/feedforward_test.py
- scripts/ai2_internal/run_with_beaker.py
- scripts/py2md.py
Fixes new linting errors introduced by a new version of flake8. Most of the lints are uncontroversial, such as F541 ("f-string is missing placeholders"). But one that I don't totally agree with is E741 ("ambiguous variable name") - which occurs whenever you use `l` as a variable name - since syntax highlighting (and a good font) usually removes the ambiguity.
> fix new linting errors

- allennlp/common/checks.py
I'm not sure this is coded up particularly well, but I wanted to put a PR together to clearly demonstrate what we need.  Our present exception is rather vague, whereas PyTorch will give a clear an informative error.  I spent a few hours yesterday tracking down a problem when the PyTorch exception would have clearly explained the root problem immediately.
`cuda.current_device()` will throw an exception if CUDA is not available.  For example:
1.  On a system with an incompatible driver.
```
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your …
```
> Add a more informative exception when there's no GPU available.

- allennlp/training/util.py
I'm using this function in the allennlp course, and noticed that some of its arguments really should be optional.
> Make some arguments to evaluate() optional, add docstring

- .github/workflows/master.yml
> ensure nightly builds don't run for forks

- allennlp/common/file_utils.py
- allennlp/tests/common/file_utils_test.py
This also does some additional clean up to `file_utils.py`, in particular renaming the internal functions of the module with a leading underscore so that they won't be included in the API docs.
> make 'cached_path' work offline

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- Makefile
> switch to tokenless codecov upload

- RELEASE_PROCESS.md
I'm not really sure what the previous command does.  It seems easier if we simplify the syntax to specify the version range.  I think it will make it less likely to make a mistake.
> Clean up the command to create a commit list.

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/common/checks.py
- allennlp/common/testing/__init__.py
- allennlp/common/util.py
- allennlp/nn/util.py
- allennlp/training/trainer.py
- allennlp/training/util.py
- tests/commands/train_test.py
- tests/nn/util_test.py
This is probably only useful during testing.
> Enable multi-process training on CPU

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/data/dataloader.py
- allennlp/data/samplers/bucket_batch_sampler.py
- allennlp/data/samplers/samplers.py
- allennlp/data/vocabulary.py
- allennlp/models/model.py
- allennlp/modules/token_embedders/embedding.py
- allennlp/training/checkpointer.py
- allennlp/training/learning_rate_schedulers/cosine.py
- allennlp/training/learning_rate_schedulers/learning_rate_scheduler.py
- allennlp/training/learning_rate_schedulers/noam.py
- allennlp/training/learning_rate_schedulers/slanted_triangular.py
- allennlp/training/momentum_schedulers/inverted_triangular.py
- allennlp/training/moving_average.py
- allennlp/training/no_op_trainer.py
- allennlp/training/optimizers.py
- allennlp/training/tensorboard_writer.py
- allennlp/training/trainer.py
The point of `FromParams` is to have a config file's keys exactly match constructor parameters.  There are a few cases where that isn't actually true, because we construct an object separately and pass it in, removing the need to specify that constructor argument in a config file.  In writing about how config files work for the allennlp course, I realized that this was a pretty big piece of magic that needed explanation and documentation.  This PR adds documentation for that behavior.
I additionally noticed that there was a `batch_weight_key` in `commands.train` that could be simplified quite a bit, so I simplified it.
> Document when parameters do not need an entry in a config file

- CHANGELOG.md
- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
- tests/data/tokenizers/pretrained_transformer_tokenizer_test.py
I tried to use a small transformer model in part of the course, and it failed the assertions in the tokenizer (because "1" and "2" were not in the vocabulary, so they were both mapped to the same UNK token).  This PR makes the logic more robust to other transformer models.
> Make special token inference logic more robust

- allennlp/interpret/saliency_interpreters/saliency_interpreter.py
The documentation was wrongly copy-pasted from `allennlp/interpret/attackers/attacker.py`.
> Update documentation of saliency_interpreter.py

- .github/workflows/pull_request.yml
- CHANGELOG.md
- dev-requirements.txt
- setup.py
- Removes `conllu` dependency (see https://github.com/allenai/allennlp-models/pull/61)
- Removes `semantic_version` dependency (we don't use this at all anymore)
- Removes the `tests_requires` and `setup_requries` section of `setup.py`, since we don't use the `python setup.py test` command. Also see the deprecation notice of `pytest-runner` for why we shouldn't be using this: https://github.com/pytest-dev/pytest-runner#deprecation-notice.
- Moves a few other requirements in the `install_requires` section of `setup.py` to `dev-requirements.txt`, since they are only imported in our `tests/`.
- Removes `aiohttp` from `dev-requirements.txt` since it isn't used anywhere.
> clean up dependencies

- CHANGELOG.md
- allennlp/data/fields/field.py
- allennlp/data/fields/text_field.py
- allennlp/data/instance.py
- allennlp/predictors/sentence_tagger.py
- allennlp/predictors/text_classifier.py
- tests/data/instance_test.py
Closes https://github.com/allenai/allennlp/issues/4270.
This new method should be used in place of `copy.deepcopy()`. It can be overridden on certain fields to avoid making deep copies of certain attributes when deep copying is unnecessary or not possible.
---
Note: I was lazy and haven't added tests yet, but I'll do so before merging if ya'll agree with this approach.
> Adds a "duplicate()" method on instances and fields

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/common/file_utils.py
- allennlp/data/vocabulary.py
- setup.py
- tests/commands/train_test.py
This should make our caching mechanism much more robust. It uses a lock file to ensure that if one process is caching a particular file, any other calls to `cached_path()` on the same file (from separate Python processes) will block until the writing process has finished.
I'm not sure if there's a good way to unit test this, or if it's even worth it because the logic is pretty simple. But you can give it a try by running a script like this from multiple terminals at the same time:
```python
import logging
from allennlp.common.file_utils import cached_path
logging.basicConfig(level=logging.INFO)
filename = "https://allennlp.s3.amazonaws.com/datasets/glove/glove.6B.100d.txt.gz"
print(cached_path(filename))
```
Also https://github.com/allenai/allennlp/pull/4298 may not be necessary if we …
> add lock file within caching mechanism

- setup.cfg
I don't think there's any reason to have this since we don't do `python setup.py test` to run pytest, which is deprecated anyway: https://github.com/pytest-dev/pytest-runner/#deprecation-notice
> remove setup.cfg

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- Makefile
Occasionally CUDA becomes unavailable on the self-hosted runner, for whatever reason. When this happens, the GPU workflow will always pass even though it doesn't actually run any GPU checks.
> ensure CUDA available in GPU checks workflow

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/common/tqdm.py
- allennlp/data/dataset_readers/dataset_reader.py
- allennlp/modules/token_embedders/embedding.py
- allennlp/training/learning_rate_schedulers/slanted_triangular.py
- allennlp/training/trainer.py
- allennlp/training/util.py
This fixes a bug that occurs when using a lazy dataset reader where you'd get a `PyTorch` warning on every single batch during training. It does so by making `AllennlpLazyDataset` consistent with `torch.data.IterableDataset` in that it no longer implements `__len__()` (previously `len()` would just return 1).
To reproduce this bug just run `allennlp train` on a experiment with a lazy dataset reader like this:
```
{
"dataset_reader": {
"type": "squad",
"lazy": true,
"token_indexers": {
"tokens": {
"type": "single_id",
"lowercase_tokens": true
},
"token_characters": {
"type": "characters",
"character_tokenizer": {
"byte_encoding": "utf-8",
"start_tokens": [259],
"end_tokens": [260]
},
"min_padding_length": 5
}
}
},
"train_data_path": …
```
> Fix bug with lazy data loading, un-implement __len__ on AllennlpLazyDataset

- CHANGELOG.md
- allennlp/models/simple_tagger.py
- allennlp/predictors/sentence_tagger.py
- tests/interpret/input_reduction_test.py
- tests/predictors/predictor_test.py
- tests/predictors/sentence_tagger_test.py
This seems like a nit-picky thing, but we had situations where the model was using underscores, and the corresponding predictor was using the exact same name except with dashes.
> Consistently use underscores in Predictor names

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/training/util.py
- tests/training/util_test.py
This fixes a couple of bugs related to the `datasets_for_vocab_creation` config parameter.
The main bug is that `datasets_for_vocab_creation: []` ends up being treated like `datasets_for_vocab_creation: null` due to this statement in `commands.train.TrainModel.from_partial_objects`:
```python
instance_generator = (
instance
for key, dataset in datasets.items()
if not datasets_for_vocab_creation or key in datasets_for_vocab_creation
for instance in dataset
)
```
which should be
```python
instance_generator = (
instance
for key, dataset in datasets.items()
if datasets_for_vocab_creation is None or key in datasets_for_vocab_creation
for instance in dataset
)
```
The 2nd bug occurs when `training.util.vocab_from_params(...)` is called. Even if `datasets_for_vocab_creation` is set to `[]`, all …
> Fix handling of "datasets_for_vocab_creation" param

- README.md
Partial fix for #4339.  Not saying it closes that issue, because there are two more templates to make first.
> Add link to new template repo for config file development

- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
- allennlp/version.py
- setup.py
If we don't do this at initialization, then in the training logs it will list the transformer's parameters as trainable, and it will also cause model tests to fail on the `check_model_computes_gradient_correctly` method if your test model has `train_parameters` set to `False`.
> ensure transformer params are frozen at initialization when train_parameters is false

- dev-requirements.txt
This should fix the errors we're seeing in the "Build docs" CI step.
> pin some doc building requirements

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/common/testing/model_test_case.py
- allennlp/training/trainer.py
This was necessary to have tests for the no-config-file template repo.  I also noticed a few other small typos in the documentation, which are fixed in here.
> Add a method to ModelTestCase for use without config files

- tests/data/dataloader_test.py
Closes #4393 
The behavior was actually correct, so this just adds a test to make sure we don't regress in the future.
> Add test to ensure data loader yields all instances when batches_per_epoch is set

- CHANGELOG.md
- allennlp/nn/initializers.py
- tests/nn/pretrained_model_initializer_test.py
This PR fixes #4427. As described, slicing a 0-dim tensor raises `IndexError`, so used `copy_` method instead.
I added scalar parameters to the models in `pretrained_model_initializer_test.py` and added a test case, which had failed before this fix.
> Fix pretrained model initialization

- CHANGELOG.md
- allennlp/training/learning_rate_schedulers/slanted_triangular.py
There is a bug related to gradual unfreezing with the Slanted Triangular Learning Rate schedule. During the first epoch, only the top layer is trained (as expected) but, during the 2nd epoch, the top **3** layers are trained when it should just be the top 2:
This also causes training to crash on the last "freezing" epoch:
> fix bug with SlantedTriangular LR scheduler

- CHANGELOG.md
- allennlp/common/logging.py
@dirkgr, I'm not sure if this was intentional, but https://github.com/allenai/allennlp/pull/4383 caused all trainer workers to write log output to the terminal, which makes it hard to read.
> ensure only rank 0 worker writes to terminal

- CHANGELOG.md
- allennlp/common/logging.py
- allennlp/data/dataset_readers/sharded_dataset_reader.py
- tests/data/dataset_readers/sharded_dataset_reader_test.py
The base reader of a `ShardedDatasetReader` should never implement manual distributed sharding itself, otherwise only a fraction of the instances would be read. This just adds a check for that.
> ensure base reader of ShardedDatasetReader doesn't implement sharding itself

- CHANGELOG.md
- allennlp/predictors/text_classifier.py
Fixes #4059
TextClassificationPredictor now passes tokenized inputs to the DatasetReader's text_to_instance function if it does not have a tokenizer.
> Fixing bug in TextClassificationPredictor

- CHANGELOG.md
- allennlp/data/dataloader.py
- tests/data/dataloader_test.py
This warning is no longer relevant since the tokenizers upgrade.
> remove deadlock warning in DataLoader

- CHANGELOG.md
- allennlp/training/optimizers.py
- allennlp/training/trainer.py
- tests/training/optimizer_test.py
Closes #4482
Per the discussion in #4482, we decided to have the optimizer handle freezing layers. This PR accomplishes that by having the optimizer module check for a `requires_grad: false` key-value pair in the parameter groups. So, for example, if you want to freeze the first few layers in a BERT model, you could do something like this:
```jsonnet
// ... config snippet ...
"trainer": {
"optimizer": {
"type": "huggingface_adamw",
"lr": 2e-4,
"eps": 1e-8,
"weight_decay": 0.01,
"parameter_groups": [
[
[
"_source_embedder\\.token_embedder_tokens\\.transformer_model\\.embeddings\\..*",
"_source_embedder\\.token_embedder_tokens\\.transformer_model\\.encoder\\.layer\\.0\\..*",
"_source_embedder\\.token_embedder_tokens\\.transformer_model\\.encoder\\.layer\\.1\\..*", …
```
> add a requires_grad option to param groups

- CHANGELOG.md
- allennlp/common/from_params.py
- tests/common/from_params_test.py
When `FromParams` needs to construct parameters for cases when the type is Optional[Union[...]], it fails silently if the parameter name is incorrect.
Steps to reproduce:
1. This fails silently and returns the type as `dict` (it should be `NestedClass`):
```from typing import Optional, Union
from allennlp.common import Params, FromParams
class NestedClass(FromParams):
def __init__(self, 
varname: Optional[str] = None
):
self.varname = varname
class WrapperClass(FromParams):
def __init__(self, nested_class: Optional[Union[str, NestedClass]] = None):
if isinstance(nested_class, str):
nested_class = NestedClass(varname=nested_class)
self.nested_class = nested_class
m = WrapperClass.from_params(params=Params({"nested_class": {"wrong_varname": "varstring"}}))
type(m.nested_class)
```
2. This …
> Bug fix for case when param type is Optional[Union...]

- scripts/py2md.py
Implementations of `__call__` are usually worth including in the API docs, such as with `BatchCallback` or `EpochCallback`.
> ensure __call__ methods are rendered in docs

- CHANGELOG.md
- allennlp/modules/seq2seq_encoders/__init__.py
Follow-up for #3941.
I was looking for self-attention modules to find that these were moved to allennlp-model.
I removed the links with no destination.
> Remove link to self-attention modules.

- CHANGELOG.md
- allennlp/commands/train.py
A follow-up on this [issue](https://github.com/allenai/allennlp/pull/4328/files#r436138651), in which if we use `AllennlpLazyDataset`, the dataloader in pytorch will attempt to call `len(self.evaluation_data_loader)`, which will crash the program.
@epwalsh patched the first condition but forgot to patch the second condition. This PR patches the second condition.
> Ensure len(self.evaluation_data_loader) is not called

- CHANGELOG.md
- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
- tests/data/tokenizers/pretrained_transformer_tokenizer_test.py
Fixes how truncation was handled with `PretrainedTransformerTokenizer`.
Currently, if `max_length` is set to `None`, the tokenizer will still do truncation if the transformer model has a default max length in its config.
Also, when `max_length` is set to a non-`None` value, several warnings appear for certain transformer models around the use of the `truncation` parameter.
The warnings come from this function: https://github.com/huggingface/transformers/blob/b390a5672aea995e65d031b3759274d92188e553/src/transformers/tokenization_utils_base.py#L1705, and for reference, this is the signature of the `encode_plus` method: https://github.com/huggingface/transformers/blob/b390a5672aea995e65d031b3759274d92188e553/src/transformers/tokenization_utils_base.py#L1946.
> Fix handling of max length with transformer tokenizers

- CHANGELOG.md
- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
- allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
- tests/modules/token_embedders/pretrained_transformer_embedder_test.py
Gradient checkpointing has been released with huggingface/transformers v3.0.0. Gradient checkpointing reduces memory by 5x which makes it possible to process longer sequences on smaller GPUs. This PR allows to fine-tune transformer token embedders on a more regular GPU with high(er) max_length values.
Sorry for not providing any tests, I have no clue how to create a simple test case and no resources at the moment to figure that out. But I tried it succesfully with Longformer (max_length: 4096) and SciBert (max_length: 512) on a single RTX 2080 Ti.
> add gradient checkpointing for transformer token embedders

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
Ensures the GitHub Actions workflow runs on commits to the vision branch but doesn't deploy the docs or docker image. Also fixes the CHANGELOG check on pull requests to the vision branch.
> ensure vision CI runs on each commit

- allennlp/data/dataset_readers/dataset_reader.py
- tests/data/dataset_readers/dataset_reader_test.py
I think `node_rank` is the wrong name to use in this context because this is supposed to represent the ID of the current **process** within the distributed group, not the ID of the node (which usually contains multiple processes). `global_rank` is more accurate.
> rename 'node_rank' to 'global_rank' in dataset reader 'DistributedInfo'

- CHANGELOG.md
- allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
- tests/modules/token_embedders/pretrained_transformer_mismatched_embedder_test.py
Fixes #4612 and adds a unit test to confirm that missing or exotic tokens to not lead to `nan` gradients in BERT-style embedder.
> Fix division by zero when there are zero-length spans in MismatchedEmbedder.

- allennlp/data/data_loaders/data_loader.py
There is no need to pass the result of `Batch.get_padding_lengths()` to `Batch.as_tensor_dict()` since, internally, `Batch.as_tensor_dict()` will call `Batch.get_padding_lengths()` anyway.
> remove duplicate padding calculations in collate fn

- CHANGELOG.md
- allennlp/common/file_utils.py
Closes https://github.com/allenai/allennlp/issues/4501.
> improve robustness of cached_path when extracting archives

- allennlp/data/data_loaders/multi_process_data_loader.py
- tests/data/data_loaders/multi_process_data_loader_test.py
Had the wrong order in the `if` statement.
> fix len calculation for new data loader

- CHANGELOG.md
- allennlp/common/testing/distributed_test.py
- allennlp/training/metrics/attachment_scores.py
- allennlp/training/metrics/average.py
- allennlp/training/metrics/evalb_bracketing_scorer.py
- allennlp/training/metrics/pearson_correlation.py
- tests/training/metrics/average_test.py
Closes https://github.com/allenai/allennlp/issues/4623.
There was a bug with the `average` and `evalb_bracketing_scorer` metrics during distributed training on GPU.
> fix Average metric

- allennlp/common/plugins.py
> Workaround for Python not finding imports in spawned processes

- allennlp/data/dataset_readers/babi.py
- allennlp/data/dataset_readers/conll2003.py
- allennlp/data/dataset_readers/nlvr2_reader.py
- allennlp/data/dataset_readers/sequence_tagging.py
- allennlp/data/dataset_readers/text_classification_json.py
- allennlp/interpret/attackers/hotflip.py
- allennlp/predictors/predictor.py
- tests/predictors/predictor_test.py
- tests/predictors/sentence_tagger_test.py
- tests/predictors/text_classifier_test.py
This makes it so the dataset readers we provide can be used efficiently with the multi-process data loader.
> make existing readers work with multi-process loading

- CHANGELOG.md
- allennlp/training/metrics/average.py
- allennlp/training/metrics/perplexity.py
I think we need to decide what type metrics return. Here are some changes to make sure it's always `float` (as opposed to `FloatTensor` or `int`).
I don't care much what we decide, but it causes problems in some places when the types change. It _especially_ causes problems when we have `if something(): return 0; else return FloatTensor(...).`, where the types differ depending on when you call it.
> Return consistent types from metrics

- CHANGELOG.md
- allennlp/modules/conditional_random_field.py
- tests/modules/conditional_random_field_test.py
When running the CRF, I currently get this warning (reproduced it in py.test, too):
```
========================================== warnings summary ===========================================
tests/modules/conditional_random_field_test.py::TestConditionalRandomField::test_viterbi_tags
/home/nfliu/git/allennlp/tests/modules/conditional_random_field_test.py:1: UserWarning: This overload of nonzero is deprecated:
nonzero()
Consider using one of the following signatures instead:
nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
import itertools
-- Docs: https://docs.pytest.org/en/stable/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: Quitting debugger !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================ 2 …
```
> Fix tensor.nonzero() function overload warning

- CHANGELOG.md
- RELEASE_PROCESS.md
- scripts/release_notes.py
This PR does two things:
1. Adds a script `scripts/release_notes.py` which automatically prepares markdown release notes from the `CHANGELOG` and commit history.
2. Updates `RELEASE_PROCESS.md` to include using the new script, and also clarifies some other things.
> smooth out release process

- CHANGELOG.md
- allennlp/common/file_utils.py
- tests/common/file_utils_test.py
Currently, when `cached_path()` is called with `extract_archive=True` on a local archive file, the archive is extracted in the same directory. For example,
```python
>>> cached_path("~/vocab.tar.gz", extract_archive=True)
#> ~/vocab-tar-gz-extracted
```
But I don't think this is a good way to do it because we shouldn't be messing with peoples' local file system outside of the designated cache directory.
This PR changes the behavior so that local archives are extracted to unique sub-directories of the cache root. The name of the sub-directory is derived in a similar way that we derive the cached path for remote resources: with a hash of the path and a hash of the ETag. Except, instead of an ETag in this case, we use the last modified time of the local file.
This approach has the added …
> improve how cached_path extracts archives

- allennlp/commands/train.py
@jiasenlu brought up that the timing of this logging statement is confusing. It should really happen right before we spawn distributed workers, after vocab creation, so that it doesn't seem like vocab creation is happening after spawning distributed workers.
> fix confusing distributed logging info

- CHANGELOG.md
- allennlp/data/token_indexers/pretrained_transformer_mismatched_indexer.py
- allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
Looks like I missed a couple places where `tokenizer_kwargs`/`transformer_kwargs` should have been passed through as well as part of #4651 (issue #4650).
So, I added `tokenizer_kwargs` in `PretrainedTransformerMismatchedIndexer` and `tokenizer_kwargs`/`transformer_kwargs` in `PretrainedTransformerMismatchedEmbedder`.
> Add missing tokenizer/transformer kwargs

- CHANGELOG.md
- scripts/py2md.py
- scripts/tests/py2md/basic_example.py
- scripts/tests/py2md/basic_example_expected_output.md
Updates the doc generation script so that class decorators are displayed like this:
One obvious benefit to this is that you can see what a class is registered under.
> display class decorators in API docs

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/common/util.py
common.util.is_master returned wrong result when there was only a single node. It was only used when saving vocabulary, so I think no harm done.
> Fix a bug in saving vocab during distributed training

- CHANGELOG.md
- allennlp/training/trainer.py
Currently, when training with gradient accumulation (i.e. with `num_gradient_accumulation_steps > 1`), the reported `batch_loss` metric is always just the loss from last batch in the batch group divided by the number of batches in the group. By itself, this is arbitrary and kind of meaningless. Instead, `batch_loss` should report the cumulative loss for the entire group.
By the way, this came up in https://stackoverflow.com/questions/64181843/calculate-loss-in-train-epoch-function.
> fix reported batch_loss with gradient accumulation

- CHANGELOG.md
- allennlp/commands/cached_path.py
- allennlp/common/file_utils.py
- allennlp/common/util.py
- allennlp/training/tensorboard_writer.py
- allennlp/training/trainer.py
- tests/commands/train_test.py
- tests/common/file_utils_test.py
- tests/common/util_test.py
- tests/training/trainer_test.py
While training some jobs on beaker today I realized the GPU memory metrics were completely inaccurate, which motivated me to make some improvements to our memory reporting util functions.
- Renames `allennlp.common.util.peak_memory_mb` to `peak_cpu_memory` and returns results in bytes as integers.
- Renames `allennlp.common.util.gpu_memory_mb` to `peak_gpu_memory` and returns results in bytes as integers.
- The `peak_gpu_memory` function now utilizes PyTorch functions to find the memory usage instead of shelling out to the `nvidia-smi` command. This is more efficient and also more accurate because it only takes into account the tensor allocations of the current PyTorch process.
> improve memory helper functions

- CHANGELOG.md
- allennlp/nn/initializers.py
Make sure weights are first loaded to the cpu when using PretrainedModelInitializer, preventing wasted GPU memory.
> Load weights to cpu with PretrainedModelInitializer

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/common/util.py
Closes https://github.com/allenai/allennlp/issues/4666
> automatically find local open port in distributed training

- CHANGELOG.md
- allennlp/training/metrics/rouge.py
Fixes #4715 .
Rouge metrics were being computed incorrectly while distributed training because of `self._total_sequence_count`  not being aggregated across GPUs. This PR fixes it.
> Fixes rouge metric calculation corrected for distributed training

- CHANGELOG.md
- allennlp/common/testing/test_case.py
Updated AllenNlpTestCase test case to remove reference to `unittest.TestCase` as per issue #4716
> Updated AllenNlpTestCase docstring

- CHANGELOG.md
- allennlp/common/params.py
- allennlp/models/model.py
- allennlp/nn/initializers.py
- tests/common/params_test.py
When loading a model, pretrained embeddings are not loaded as it is not needed.
This change make the same thing happen with pretrained weights from PretrainedModelInitializer.
Goes with https://github.com/allenai/allennlp-models/pull/141
> Don't use PretrainedModelInitializer when loading a model

- CHANGELOG.md
- allennlp/training/metrics/categorical_accuracy.py
I got same error( `RuntimeError: Tensors must be CUDA and dense` )  in #4623 when I used distributed training with **allennlp 1.1.0** and **pytorch 1.6**.
I read your PR in #4570 , seem you only fix it in `Average` Class. When I use `CategoricalAccuracy `, the same error occur. 
So I try to fix it by move these tensors to GPU (same in `Average`), it works well.
Maybe you could help me check my solution, then I could update all related Metrics Classes ?
> Fix device mismatch bug for categorical accuracy metric in distributed training

- CHANGELOG.md
- allennlp/training/trainer.py
Fixes #4750 . Makes `end_callbacks` and `trainer_callbacks` instantiable from config files.
> Add end+trainer callbacks to Trainer.from_partial_objects

- CHANGELOG.md
- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
Addressing #4757 bug - check description there.
I can duplicate intra tokenizer test with use_fast False flag, but not sure if you want to keep such tests (there can be multiple of such tests with different flags).
> Make returning token type id default in transformers intra word tokenization.

- CHANGELOG.md
- allennlp/common/testing/model_test_case.py
This is an alternative to ad hoc patches like https://github.com/allenai/allennlp-models/pull/162. It should allow us to make some model tests less flaky by setting the seed.
> add seed option to ModelTestCase.set_up_model

- CHANGELOG.md
- allennlp/nn/util.py
This should make the tests in https://github.com/allenai/allennlp-models/pull/163 pass.
> RoBERTa embeddings are no longer a type of BERT embeddings

- CHANGELOG.md
- allennlp/modules/seq2vec_encoders/cnn_encoder.py
When we create completely new tensors outside of a dataset reader, we almost always have to be careful where we put them.
> Set the device for an auto-created mask

- CHANGELOG.md
- allennlp/training/metrics/rouge.py
typo in registered string. if ones use registered metric by string `rogue`, they need to fix.
Just fixing typo, I didn't update CHANGELOG.
> Fix: typo in metric, rogue -> rouge

- CHANGELOG.md
- Makefile
- README.md
- allennlp/commands/subcommand.py
- allennlp/common/plugins.py
Adds support for declaring a global plugins file at `~/.allennlp/plugins` and improves the documentation for plugins. This also closes https://github.com/allenai/allennlp/issues/4775 by added a place to display third-party plugins.
> support global plugins file, improve plugins docs

- CHANGELOG.md
- allennlp/training/trainer.py
* Prevent an error when GradientDescentTrainer is constructed with
validation_data_loader=None and learning_rate_scheduler!=None
This pull request fixes issue: https://github.com/allenai/allennlp/issues/4810
> Fix issue in GradientDescentTrainer, when validation data is absent

- CHANGELOG.md
- allennlp/common/logging.py
We should not mutate (insert/remove elements) the list you're currently iterating on. In fact, this causes handlers to not be completely deleted on my side.
For more discussion, see https://stackoverflow.com/questions/7484454/removing-handlers-from-pythons-logging-loggers
> fix: removes all handlers from the root logger

- CHANGELOG.md
- allennlp/data/dataset_readers/sharded_dataset_reader.py
- tests/data/dataset_readers/sharded_dataset_reader_test.py
Implemented automatic parameters inheritance from `base_reader` in `ShardedDatasetReader`. This allows the user to specify parameters like `lazy` or `max_instances` either for the `base_reader` or the `ShardedDatasetReader` itself. 
Fixes the issue reported in https://github.com/allenai/allennlp/issues/4825
> Bugfix for attribute inheritance in ShardedDatasetReader

- CHANGELOG.md
- allennlp/nn/activations.py
Following up from Issue #4823. This PR adds the Gaussian Error Linear Unit activation to the Activations class in AllenNLP.
> Add GELU activation

- CHANGELOG.md
- allennlp/common/from_params.py
- tests/common/from_params_test.py
This was an interesting one. I found this after digging into the test that seemed to fail out of nowhere in this (unrelated) PR: https://github.com/allenai/allennlp-models/pull/175/checks?check_run_id=1499712028. This bug only manifested itself because of a different bug fix regarding the `ShardedDatasetReader` (https://github.com/allenai/allennlp/pull/4830).
Basically, the `ShardedDatasetReader` needs to inspect its `**kwargs` for the "lazy" parameter. The behavior depends on whether or not "lazy" is present. But the current `FromParams` logic removes the "lazy" param from `kwargs` if it's the same as the default value in the superclass.
So this fixes the behavior of `FromParams` so that parameters in the `Params` object will ALWAYS be passed to the constructor.
> fix FromParams bug

- CHANGELOG.md
- allennlp/__init__.py
I kept getting "ImportError: dlopen: cannot load any more object with static TLS" and segmentation faults.
At first, it seemed the cause is the import of `sklearn` in the AUC metric. After adding `sklearn` import before everything else, I didn't get the static TLS error anymore, but continued getting seg faults which came from imports from `transformers`.
Adding a `transformers` import before all other imports helped with both errors.
> Improve the band-aid solution for seg faults and the static TLS error

- allennlp/models/vision_text_model.py
- allennlp/modules/transformer/bimodal_attention.py
- allennlp/modules/transformer/self_attention.py
- allennlp/modules/transformer/util.py
- test_fixtures/vilbert_ve/experiment_from_huggingface.jsonnet
- tests/modules/transformer/bimodal_attention_test.py
- tests/modules/transformer/bimodal_encoder_test.py
@dirkgr This includes the `_apply_mask` function that you added in `torchvision`, with minor changes. I shifted the reshaping part to the module (though it will still work if the reshaping happens outside) to make it consistent with `SelfAttention`.
> Toolkit: Adding documentation and small changes for `BiModalAttention`

- CHANGELOG.md
- allennlp/training/learning_rate_schedulers/__init__.py
- allennlp/training/learning_rate_schedulers/combined.py
- allennlp/training/scheduler.py
- tests/training/learning_rate_schedulers/combined_test.py
Closes #4856. This will allow me to try some other things with VilBERT VQA.
> add CombinedLearningRateScheduler

- CHANGELOG.md
- allennlp/data/fields/label_field.py
Minor typo in `LabelField.__str__` function.
> Fix typo in __str__

- allennlp/modules/elmo.py
There is a small typo in allennlp/modules/elmo.py.
Should read `multiplication` rather than `multplication`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, multplication -> multiplication

- allennlp/data/data_loaders/__init__.py
- allennlp/data/data_loaders/data_loader.py
- allennlp/data/data_loaders/multiprocess_data_loader.py
- allennlp/data/data_loaders/multitask_data_loader.py
- allennlp/data/dataset_readers/conll2003.py
- allennlp/data/dataset_readers/dataset_reader.py
- allennlp/data/dataset_readers/sequence_tagging.py
- allennlp/data/dataset_readers/sharded_dataset_reader.py
- allennlp/data/dataset_readers/text_classification_json.py
- allennlp/data/dataset_readers/vision_reader.py
- tests/data/data_loaders/multi_process_data_loader_test.py
- tests/data/dataset_readers/dataset_reader_test.py
See #4904.
```
find ./ -type f -exec sed -i '' 's/multi_process/multiprocess/g' {} \;
```
Requires a small change in `allennlp-models` for CI to pass.
> rename 'multi_process_*' -> 'multiprocess' for consistency

- allennlp/data/data_loaders/multi_process_data_loader.py
See #4904.
- Changes `data_path` type to `Union[str, os.PathLike]` in `MultiProcessDataLoader`.
> MultiProcessDataLoader takes PathLike data_path

- .github/workflows/ci.yml
- CHANGELOG.md
- Adds an official Docker image for CUDA 10.1.
> add CUDA 10.1 Docker image

- mkdocs-skeleton.yml
Syntax highlighting had quietly disappeared. This fixes that.
> fix mkdocs config

- allennlp/training/metric_tracker.py
Makes the metric tracker's `state_dict` handling consistent.
Neither `patience` nor `tracked_metrics` should be in the `state_dict`, because those come from the constructor. Also, `best_epoch_metrics` should be saved and restored.
@mahnerak
> Consistent metric tracker

- CHANGELOG.md
- allennlp/modules/backbones/pretrained_transformer_backbone.py
- Just adding a missing `transformer_kwargs` arg to `PretrainedTransformerBackbone` constructor, that was recently added to `PretrainedTransformerEmbedder`.
> Adding missing transformer_kwargs arg that was recently added to PretrainedTransformerEmbedder

- CHANGELOG.md
- allennlp/modules/backbones/pretrained_transformer_backbone.py
- Adding missing `tokenizer_kwargs` argument to `PretrainedTransformerBackbone`'s constructor. This was also recently added to `PretrainedTransformerEmbedder`.
> Adding missing tokenizer_kwargs arg to PretrainedTransformerBackbone

- CHANGELOG.md
- allennlp/common/util.py
- tests/common/util_test.py
- `common.util.sanitize()` didn't handle `set` objects before. Now it will.
> Sanitize set

- CHANGELOG.md
- allennlp/data/data_loaders/multiprocess_data_loader.py
Fixes a bug in `MultiProcessDataLoader` that causes a crash when using lazy loader with workers when `start_method = "spawn"` and `batches_per_epoch` is set.
The bug happens because generator objects cannot be pickled. And with those settings in the `MultiProcessDataLoader`, a generator would be created and assigned to `self._batch_generator` before spawning workers, and since spawning uses pickle, this would fail.
> fix bug with MultiProcessDataLoader

- CHANGELOG.md
- allennlp/data/dataset_readers/conll2003.py
- tests/data/dataset_readers/conll2003_test.py
Fixes #1941 and retry of #4924.
This PR introduces `convert_to_coding_scheme` to `Conll2003DatasetReader` based on the [suggestion](https://github.com/allenai/allennlp/pull/4924#discussion_r566309610) by @epwalsh.
> Introduce `convert_to_coding_scheme` and make `coding_scheme` deprecated in CoNLL2003DatasetReader

- CHANGELOG.md
- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
- allennlp/training/metric_tracker.py
- tests/modules/token_embedders/pretrained_transformer_embedder_test.py
Fixes part of #4690 
- I opened issue #4690 a while ago for AllenNLP to provide `additional_special_tokens` parameter for transformers models. @dirkgr already provided a fix for the parameter to be added and worked very well, but we were missing some way for the model to adapt it's word embeddings layer to the additional tokens provided. I'm not sure if this is the best way to do it, but this PR seems to solve this.
> Resize transformers word embeddings layer for additional_special_tokens

- CHANGELOG.md
- allennlp/common/file_utils.py
- tests/common/file_utils_test.py
Fixes #4978.
- When the HTTP response we get from remote resources has an error code, we raise an `HTTPError` now by simply calling `.raise_for_status()` on the response object.
> raise on HTTP errors in cached_path

- CHANGELOG.md
- allennlp/training/metrics/mean_absolute_error.py
- tests/training/metrics/mean_absolute_error_test.py
Fixes #4961
- Ensure that `MeanAbsoluteError.get_metric(...)` returns a float, not a tensor.
- Update tests accordingly.
> Mean absolute error returns float

- CHANGELOG.md
- allennlp/data/dataset_readers/dataset_reader.py
Addresses a [comment in the migration guide](https://github.com/allenai/allennlp/discussions/4933#discussioncomment-371349).
- Added an example for fields of type `ListField[TextField]` to `apply_token_indexers` API docs.
The documentation for `apply_token_indexers` now reads like this:
Let me know if there's anything you would like me to change! @epwalsh
> Add ListField example to apply token indexers

- CHANGELOG.md
- allennlp/common/file_utils.py
Fixes https://github.com/allenai/allennlp/issues/5014.
I am not sure why this is necessary, but @aleSuglia ran into a problem with this, and this is a simple and fast way to make sure it doesn't happen again.
> Makes sure serialized tensors live on CPUs

- CHANGELOG.md
- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
Fixes # . (no open issue for this)
Uses the [`ModelOutput`](https://huggingface.co/transformers/main_classes/output.html) attributes of the `transformers` library in place of indexing. E.g., instead of
```python
hidden_states = transformer_output[-1][1:]
embeddings = transformer_output[0]
```
does
```python
hidden_states = transformer_output.hidden_states[1:]
embeddings = transformer_output.last_hidden_state
```
IMO this is more readable and (probably?) less likely to break with new versions of `transformers`.
I didn't open an issue or give the maintainers any heads up (sorry!) so please feel free to close the PR if this change is not welcome.
> Use HF Transformers output types

- .github/workflows/ci.yml
- CHANGELOG.md
- setup.py
Playing dependabot for the day.
Updates the requirements on [torch](https://github.com/pytorch/pytorch) to permit the latest version.
Release Notes: https://github.com/pytorch/pytorch/releases/tag/v1.8.0
> Update torch requirement from <1.8.0,>=1.6.0 to >=1.6.0,<1.9.0

- CHANGELOG.md
- allennlp/common/from_params.py
- allennlp/common/lazy.py
- tests/common/from_params_test.py
From https://github.com/allenai/allennlp/issues/5030#issuecomment-795765426. This should ensure the `VisionReader` is pickleable, which is needed in order to use the "spawn" start method with multi-process data loading.
> fix pickle bug for Lazy FromParams

- CHANGELOG.md
- allennlp/common/util.py
- allennlp/data/tokenizers/sentence_splitter.py
- allennlp/data/tokenizers/spacy_tokenizer.py
- allennlp/predictors/sentence_tagger.py
- tests/data/dataset_readers/dataset_utils/span_utils_test.py
- tests/data/dataset_readers/text_classification_json_test.py
- tests/data/token_indexers/spacy_indexer_test.py
Fixes #5036  .
- We always keep our spacy model's PoS tagger on, since the additional computation seems small and fix the behavioral issue of upgrading to SpaCy 3.0
-
> Always keep Spacy PoS tagger on

- .github/ISSUE_TEMPLATE/bug_report.md
Fixes our "Bug report" issue template by replacing references to the "master" branch with "main".
> Replace master references with main in issue template

- CHANGELOG.md
- allennlp/sanity_checks/normalization_bias_verification.py
- allennlp/training/trainer.py
- tests/training/trainer_test.py
From the discussion [here](https://github.com/allenai/allennlp/discussions/5053#discussioncomment-544325).
- Adds (back) a `run_sanity_checks` parameter.
- `SanityChecksCallback` no longer a `DEFAULT_CALLBACK`.
> Bring back `run_sanity_checks` parameter

- CHANGELOG.md
- allennlp/sanity_checks/verification_base.py
- allennlp/training/callbacks/sanity_checks.py
- tests/training/trainer_test.py
- The sanity checks callback will raise a `SanityCheckError` instead of an `AssertionError` when a check fails.
- The error message explicitly says how to turn off sanity checks.
I think it's good to have a custom error class for this type of thing so that users can easily detect and/or handle these errors in particular.
> add SanityCheckError class

- CHANGELOG.md
- allennlp/common/cached_transformers.py
- tests/common/cached_transformers_test.py
Related to #4599 .
- If a transformer is not in cache but has override weights, the transformer's pretrained weights are no longer downloaded, that is, only its `config.json` file is downloaded.
- Does not completely fix this issue, as model architecture download still occurs.
> Avoid from_pretrained download of model weights

- CHANGELOG.md
- allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
- tests/modules/token_embedders/pretrained_transformer_mismatched_embedder_test.py
Fixes #4363 .
Currently 'PretrainedTransformerMismatchedEmbedder' in allennlp only allows to return average of embeddings of all
sub-tokens of a word whereas Original BERT Model suggests to take first/last sub-token embedding.
Added the flexibility to choose first subtoken embedding based on a parameter `sub_token_mode`
- If 'sub_token_mode' is set to 'first', return first sub-token representation as word-level representation
- If 'sub_token_mode' is set to 'avg', return average of all the sub-tokens representation as word-level representation
- If 'sub_token_mode' is not specified it defaults to 'avg'
- If invalid 'sub_token_mode' is provided, throw 'ConfigurationError'
Acknowledgement of support by  @pab-vmware, @annajung, @agururajvais, …
> Added new parameter 'sub_token_mode' to 'pretrained_transformer_mismatched_embedder' class to support first sub-token embedding (#4363)

- CHANGELOG.md
- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
Avoids this warning message: https://github.com/allenai/allennlp/discussions/5119#discussioncomment-605823
> specify 'truncation' to avoid transformers warning

- CHANGELOG.md
- setup.py
We don't use jsonpickle anymore.
> remove jsonpickle from dependencies

- CHANGELOG.md
- allennlp/common/registrable.py
- tests/common/registrable_test.py
From a discussion @AkshitaB and I had.
- Improves the error message when the name passed to `Registrable.by_name()` doesn't match the name of an available subclass.
- The error message will also include a suggestion if there is a close match between the given name and the name of an available subclass.
> improve error message from Registrable class

- CHANGELOG.md
- allennlp/common/testing/__init__.py
- tests/training/metrics/categorical_accuracy_test.py
From a discussion in https://github.com/allenai/allennlp-models/pull/250.
> Take the number of runs in the test for distributed metrics

- CHANGELOG.md
- allennlp/common/testing/__init__.py
- allennlp/fairness/__init__.py
- allennlp/fairness/fairness_metrics.py
- allennlp/nn/activations.py
- tests/fairness/fairness_metrics_test.py
- tests/modules/feedforward_test.py
- Created the fairness module and added four fairness metrics: `Independence`, `Separation`, `Sufficiency`, and `Demographic Parity Without Ground Truth`.
> Fairness Metrics

- CHANGELOG.md
- allennlp/common/file_utils.py
- tests/common/file_utils_test.py
Fixes issue described [here](https://github.com/allenai/allennlp/pull/5109#issuecomment-824335671), and also ensures the downloads end up in the right cache directory, with meta ".json" files that adhere to our spec.
> fix cached_path for hub downloads

- CHANGELOG.md
- allennlp/training/checkpointer.py
- allennlp/training/trainer.py
This is supposed to fix #5076, and supersede #5077.
Fixes #5067.
I don't understand how we ever got away with bailing so early when we're out of patience. We didn't update metrics, write outputs for the last epoch, nothing, just bailed as soon as we saw we didn't improve.
> Don't orphan checkpoints when we run out of patience

- allennlp/modules/backbones/backbone.py
The ordering of parent classes in `Backbone` is backwards from `Model`'s, which leads to inconsistent MRO issues if one wants to implement their `Backbone` by multi-inheriting from an existing `Model`.
> Fixes Backbone / Model MRO inconsistency

- allennlp/nn/util.py
- tests/nn/util_test.py
- Make `dist_reduce` work for tensors.
- Pass the kwargs from `dist_reduce_sum` to `dist_reduce`
> Make dist_reduce work for tensors

- CHANGELOG.md
- allennlp/common/cached_transformers.py
- allennlp/modules/seq2vec_encoders/bert_pooler.py
- allennlp/modules/token_embedders/pretrained_transformer_embedder.py
- allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
- allennlp/modules/transformer/transformer_module.py
- allennlp/modules/transformer/transformer_stack.py
- tests/common/cached_transformers_test.py
Fixes #4599.
- Adds a `load_weights: bool` (default = `True`) parameter to `cached_transformers.get()` and all higher-level modules that call this function, such as `PretrainedTransformerEmbedder` and `PretrainedTransformerMismatchedEmbedder`. Setting this parameter to `False` will avoid downloading and loading pretrained transformer weights, so only the architecture is instantiated. So you can set the parameter to `False` via the `overrides` parameter when loading an AllenNLP model/predictor from an archive to avoid an unnecessary download.
For example, suppose your training config looks something like this:
```jsonnet
{
"model": {
"type": "basic_classifier",
"text_field_embedder": {
"tokens": {
"type": "pretrained_transformer",
"model_name": …
```
> Add way of skipping pretrained weights download

- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
We are importing `dataclasses` within a method in the `PretrainedTransformerTokenizer` class, instead of at the top level of the module. There's no good reason to do that, because `dataclasses` is imported elsewhere anyway, and there is probably a performance penalty with having to call this import statement every time the method is called. I usually don't worry about that when the method is only meant to be called once, but this particular method is likely to be called many times by the user (for example, on each tokenized sentence read from a dataset reader).
> fix dataclasses import

- README.md
Additions proposed in this pull request:
- Update README.md with fairness module description
> Update README.md with fairness module description

- CHANGELOG.md
- allennlp/common/file_utils.py
- setup.py
- tests/common/file_utils_test.py
Fixes #5150 
- Allow google cloud storage locations for cached_path
> Allow google cloud storage locations for cached_path

- CHANGELOG.md
- allennlp/modules/span_extractors/bidirectional_endpoint_span_extractor.py
- allennlp/modules/span_extractors/endpoint_span_extractor.py
- allennlp/modules/span_extractors/self_attentive_span_extractor.py
- allennlp/modules/span_extractors/span_extractor.py
- allennlp/modules/span_extractors/span_extractor_with_span_width_embedding.py
- tests/modules/span_extractors/self_attentive_span_extractor_test.py
Fixes #5145. Thanks! @dirkgr 
- added a `SpanExtractorWithSpanWidthEmbedding` class with `__init__`, `forward` and `get_input_dim` methods, putting specific span embedding computations into the abstract mehtod `_embed_spans`.
- ~~added the `__init__` method to `SpanExtractor` for initiating `span_width_embedding` and other attributes.~~
- ~~added the `forward` method to `SpanExtractor` to unify `forward` arguments of all extractors.~~
- ~~added comments for `width = span_end - span_start`.~~
- ~~added an `_embed_spans` method, which need to be implemented to compute span embeddings in different ways,  to `SpanExtractor`.~~
- modified `EndpointSpanExtractor`, `SelfAttentiveSpanExtractor` and `BidirectionalEndpointSpanExtractor` accordingly (change …
> Refactor span extractors and unify forward.

- Makefile
> Update Makefile to avoid nltk docs error

- CHANGELOG.md
- allennlp/training/trainer.py
> fix cuda_device param docs in trainer

- Makefile
> fix nltk downloads in CI install (3rd try's a charm)

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/training/trainer.py
- tests/commands/train_test.py
~~The `local_rank` was never actually passed to the trainer.~~
> Explicitly pass serialization directory and local rank to trainer in train command

- CHANGELOG.md
- allennlp/nn/beam_search.py
- tests/nn/beam_search_test.py
Implements feature requests 2 and 3 from #5205 and closes #5113.
- Other libraries, such as `transformers` or `fairseq` pick the top outputs from beam search by taking the sequence with the highest **average** log probability per token. See [here](https://huggingface.co/transformers/_modules/transformers/generation_beam_search.html) for the `transformers` implementation. The AllenNLP implementation takes the sequence with the best **total** log probability of the sequence. This change adds an abstraction called `FinalSequenceScorer` to decide how the final sequences will be scored. The default is `SequenceLogProbabilityScorer`, which assigns a score equal to sum of the log probabilities per token (i.e., the current implementation). This PR also …
> Implementing abstraction to score final sequences in `BeamSearch`

- CHANGELOG.md
- allennlp/data/samplers/bucket_batch_sampler.py
- tests/data/samplers/bucket_batch_sampler_test.py
- Added `shuffle` argument to `BucketBatchSampler` which allows for disabling shuffling.
> added shuffle disable option in BucketBatchSampler

- CHANGELOG.md
- allennlp/commands/train.py
- allennlp/common/__init__.py
- allennlp/common/meta.py
- allennlp/models/archival.py
- tests/commands/train_test.py
- tests/models/archival_test.py
- Saves meta data in the serialization directory and archive file when training. The meta data is in JSON format, and for now just includes the version used for training, but in the future could include other things such as system info or git info (https://github.com/allenai/allennlp/issues/4862).
- When an archive is loaded, a `UserWarning` will be issued if the current version of AllenNLP is older than the version that the model was trained on, or if the major versions differ (e.g. `1.2.0` vs `2.2.0`) since there is no guarantee of compatibility between major releases.
You can …
> save meta data with model archives

- CHANGELOG.md
- allennlp/training/callbacks/log_writer.py
- allennlp/training/callbacks/wandb.py
This was totally broken for distributed training 🤦‍♂️
> Fix W&B callback for distributed training

- .github/workflows/ci.yml
- Makefile
Uses the [`concurrency`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) feature to cancel redundant workflows associated with the same `ref`.
> cancel redundant GH Actions workflows

- CHANGELOG.md
- allennlp/fairness/fairness_metrics.py
Closes #5244
- fixes broken link in the doc string
> [Docs] Fixes broken link in Fairness_Metrics

- CHANGELOG.md
- allennlp/common/plugins.py
- allennlp/common/util.py
- allennlp/tools/archive_surgery.py
I was wondering why "bias_mitigator_applicator" wasn't showing up as a registered model name. This fixes that.
> Ensure all relevant allennlp submodules are imported with `import_plugins()`

- CHANGELOG.md
- allennlp/training/callbacks/__init__.py
- allennlp/training/callbacks/backward.py
- allennlp/training/callbacks/callback.py
- allennlp/training/gradient_descent_trainer.py
- tests/commands/train_test.py
- tests/training/trainer_test.py
Additions proposed in this pull request:
- Added `on_backward` training callback which allows for control over backpropagation and gradient manipulation.
> added `on_backward` trainer callback

- .github/workflows/ci.yml
- Makefile
This PR makes some improvements to how we cache and initialize the Python environment within GitHub Actions jobs. In particular, we now
- Create, use, and cache a virtualenv instead of the Python installation created by the `setup-python` action to avoid messing with system-wide files. Messing with system-wide files is okay for GitHub-hosted runners, but not for self-hosted runners.
- Consolidates where the PyTorch/Torchvision versions are defined. They still have to be hard-coded in the GH Actions config for now, but just in a single spot (an environment variable at the top of the file).
- Completely reset all caches weekly to keep them fresh.
- Use a secondary cache restore key based on the torch installation to speed up builds when a non-torch requirement changes.
Another notable …
> update Python environment setup in GitHub Actions

- CHANGELOG.md
- allennlp/predictors/predictor.py
Adds `**kwargs` to `Predictor.from_path()`. This was requested here: https://stackoverflow.com/q/68011338/4151392.
> add kwargs to Predictor.from_path()

- CHANGELOG.md
- allennlp/common/testing/model_test_case.py
- Making model_test_case.ensure_model_can_train_save_and_load consistently random
> Making model test case consistently random

- .github/workflows/ci.yml
This PR makes it so the "Check that CHANGELOG has been updated" CI step will only run when source files (files matching `allennlp/*.py`) have been modified. This should result in a cleaner looking CI history for pull requests.
> only run CHANGELOG check when source files are modified

- .github/workflows/ci.yml
- scripts/check_torch_version.py
This adds a step in CI that will ensure the current installed version of PyTorch is the most recent allowed version PyTorch according to our dependency specification in `setup.py`.
This is needed because we have to hard-code the torch installation steps in some places, so dependabot updates don't necessarily change the version of PyTorch used in CI.
> ensure torch always up-to-date in CI

- CHANGELOG.md
- allennlp/training/gradient_descent_trainer.py
Some models expect that you only call `get_metrics()` on them if they have seen at least one batch. When recovering, this is not the case. This fixes that scenario.
> Fixes recovering when the model expects metrics to be ready

- CHANGELOG.md
- allennlp/modules/seq2seq_encoders/pytorch_transformer_wrapper.py
> Docs update for `PytorchTransformerWrapper`

- CHANGELOG.md
- allennlp/nn/util.py
> Faster label smoothing

- CHANGELOG.md
- allennlp/data/fields/transformer_text_field.py
- allennlp/modules/transformer/transformer_embeddings.py
- tests/modules/transformer/toolkit_test.py
- tests/modules/transformer/transformer_embeddings_test.py
This PR contains some fixes for things I found wrong with the Transformer Toolkit when working on the multiple choice model. Unfortunately none of these differences were consequential, but we should still have this correct.
> Transformer Toolkit fixes

- CHANGELOG.md
- allennlp/modules/conditional_random_field.py
Fixes #5313 .
- Added casting tensor to the proper device
> Fix training Conditional Random Fields on GPU (#5313)

- CHANGELOG.md
- allennlp/nn/beam_search.py
Fixes #5311
- Make `constraints` object to `BeamSearch` `Lazy`.
- Pass `vocab` to each constraint in `BeamSearch` constructor (if provided).
> Provide vocab as param to constraints

- CHANGELOG.md
- allennlp/training/callbacks/wandb.py
Ensures the Weights & Biases callback will resume logging to the same run on `allennlp train --resume ...`. See https://docs.wandb.ai/guides/track/advanced/resuming for reference. Here's an example run that was stopped and then restarted: https://wandb.ai/allenai-team1/allennlp-testing/runs/2gf9ug4m/overview.
> make W&B callback resumable

- CHANGELOG.md
- allennlp/nn/initializers.py
I found some links in the initializer documentation were broken.
This PR updates them to fix.
[Writing docstrings](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.~
> Update links in initializers documentation

- CHANGELOG.md
- allennlp/data/fields/transformer_text_field.py
- tests/data/fields/transformer_text_field_test.py
Currently you can't do
```python
TransformerTextField(**tokenizer("Hello, World!", return_tensors="pt"))
```
because the tensors returned from the tokenizer have a batch dimension. This fixes that.
> allow TransformerTextField to take input directly from HF tokenizer

- CHANGELOG.md
- allennlp/common/checks.py
- tests/training/util_test.py
Fixes #5318 .
- Overrides `BaseException.__reduce__()` to include message value in the args passed down to cls(which in turn calls `__new__` and then `__init__`)
> Fix `ConfigurationError` deserialization

- CHANGELOG.md
- allennlp/common/tqdm.py
- allennlp/data/data_loaders/multiprocess_data_loader.py
Need to do this to avoid contention when the workers use Tqdm.
> set tqdm lock when new data loading workers are spawned

- CHANGELOG.md
- allennlp/models/multitask.py
> TextFieldTensor in multitask models

- CHANGELOG.md
- allennlp/nn/beam_search.py
- tests/nn/beam_search_test.py
See https://github.com/allenai/allennlp/pull/5216#discussion_r674154041 for context. @JohnGiorgi @danieldeutsch
> fix constraint bug in beam search, clean up tests

- allennlp/__main__.py
- allennlp/commands/tango.py
- allennlp/tango/evaluation.py
- allennlp/tango/step.py
- Only issue an "AllenNLP Tango is experimental..." warning when the `tango` command is run instead of issuing this warning when ANY command is run.
- Fixes the evaluation step to put the model on the right device.
- Adds a log message that says when a step run is starting (without it the logs are really hard to segment by step).
> small fixes for tango

- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.test
- Makefile
- README.md
Base images are built here: https://github.com/allenai/docker-images.
I posted a blurb about this in the `#engineering` channel on Slack:
> In an effort to speed up Docker builds across our projects and strongly version base images to avoid the possibility of downstream images breaking due to unanticipated changes in those base images, I’ve made this repo (https://github.com/allenai/docker-images) for building useful base images. So far I’ve just added base images for pytorch which we’ll end up using downstream in the AllenNLP ecosystem, but it’s easy to add new ones (instructions in the readme).
> Use our own base images to build allennlp Docker images

- CHANGELOG.md
- allennlp/training/callbacks/log_writer.py
- allennlp/training/callbacks/tensorboard.py
> Log batch metrics

- .github/workflows/ci.yml
- tests/modules/transformer/t5_test.py
Quick fix to prevent OOM failure in CI. I have a better solution I will implement tomorrow, so may revert this later. Also increases the job timeout.
> skip loading t5-base in CI

- CHANGELOG.md
- allennlp/training/learning_rate_schedulers/__init__.py
- allennlp/training/learning_rate_schedulers/combined.py
- allennlp/training/learning_rate_schedulers/cosine.py
- allennlp/training/learning_rate_schedulers/learning_rate_scheduler.py
- allennlp/training/learning_rate_schedulers/linear_with_warmup.py
- allennlp/training/learning_rate_schedulers/noam.py
- allennlp/training/learning_rate_schedulers/polynomial_decay.py
- allennlp/training/learning_rate_schedulers/pytorch_lr_schedulers.py
Partially addresses #4835.
- Improved documentation and a basic config snippet example for the learning rate schedulers
- Moved the Pytorch wrapped learning rates into their own file `pytorch_lr_schedulers.py` so that they have their own docs page
- Added links to the original PyTorch LRSchedulers so that people can read their docs as well. 
- Added formula for Noam to its docs page.
- The only LR scheduler without an example is `slanted_triangular.py` as I have not used it before and do not know of a valid config for it.
You can find this under the "Actions" tab of the pull …
> Improved Documentation For Learning Rate Schedulers

- CHANGELOG.md
- allennlp/data/vocabulary.py
- tests/data/vocabulary_test.py
Closes #5355 
- Adds new constructor for creating Vocabulary from both pretrained transformer models and instances from datasets. 
> Create Vocabulary from both pretrained transformers and instances

- CHANGELOG.md
- allennlp/__main__.py
- allennlp/commands/train.py
- allennlp/common/logging.py
- allennlp/common/util.py
- allennlp/data/data_loaders/multiprocess_data_loader.py
Fixes #5369. @dhruvdcoder could you please take a look and verify that this fixes your issues?
- `allennlp` will now catch `SIGTERM` signals and handle them the same way of `SIGINT` (keyboard interrupt).
- The `MultiProcessDataLoader` will properly shutdown its workers when a `SIGTERM` is received.
- This also adds an additional worker safety mechanism that allows `MultiProcessDataLoader` workers to constantly check if the main process is still alive and consuming. If they determine that the main process has exited, they can shut themselves down. This is useful if the main process exits abnormally. But unfortunately it only works when `start_method` is "spawn".
[Writing …
> improve signal handling and worker cleanup

- allennlp/common/file_utils.py
- Adds unit scaling to Tqdm bar when it is used to track file downloading progress
Seeing million-like numbers in the tqdm bar when downloading large files is quite non-informative. I think that scaled units will be way more useful, as we see them daily while downloading files in the browser of checking connectivity speed on speedtest. Fortunately, tqdm has scaling features that convert numbers to their scaled variants like 12304556B -> 12,3MB. 
That is used in other libraries, which deal with pretrained models, for example [huggingface/transformers](https://github.com/huggingface/transformers/blob/35236b870ee4102fb82f7a1d4713dc83af78a00a/src/transformers/file_utils.py#L1520).
You can find this under the "Actions" …
> Add scaling to tqdm bar when downloading files

- setup.py
Fixes #5398.
- Changes `setup.py` to require Python >= 3.7.
> require Python>=3.7

- .github/workflows/ci.yml
- CHANGELOG.md
- allennlp/common/params.py
- tests/common/params_test.py
This proposed change impacts the behavior of `--overrides` in a potentially breaking way ⚠️
Previously the final configuration params read from a file were simply taken as the union over the original params in the file and the params specified in `--overrides`. With this, you can now use `--overrides` to completely replace any part of the original config.
For example, passing `--overrides '{"model":{"type":"foo"}}'` will completely replace the "model" part of the original config. However, when you just want to change a single field in the JSON structure without removing / replacing adjacent fields, you can still use the "dot" syntax. For example, `--overrides '{"model.num_layers":3}'` will only change the `num_layers` parameter to the "model" part of the config, leaving everything else …
> Make `--overrides` more flexible

- CHANGELOG.md
- allennlp/training/metrics/fbeta_multi_label_measure.py
Fixes https://github.com/allenai/allennlp/issues/5472
> Fix metric docstring

- CHANGELOG.md
- allennlp/common/file_utils.py
- allennlp/common/sqlite_sparse_sequence.py
- allennlp/training/gradient_descent_trainer.py
> Hardlink or copy

- CHANGELOG.md
- allennlp/training/gradient_descent_trainer.py
Fixes #5511  .
- Load model on CPU after training is done to save GPU memory.
> Fix model loading on GPU post training

- CHANGELOG.md
- allennlp/common/checks.py
It seems the `_check_driver` function was removed or renamed at some point. Let's not rely on PyTorch internal functions in the future.
This came up in https://github.com/allenai/beaker-service/issues/1837.
> Remove spurious error message "'torch.cuda' has no attribute '_check_driver'"

- CHANGELOG.md
- allennlp/training/callbacks/should_validate.py
- tests/training/trainer_test.py
Addresses a bug in #5534.
There were two subtle bugs in `ShouldValidateCallback` merged in #5534. One caused validation to always happen after the first epoch regardless of `validation_start`. The other caused validation to happen every `validation_interval + 1` epochs instead of every `validation_interval` epochs. Fixed both with the following changes:
- Add `on_start` method to `ShouldValidateCallback` that correctly sets `_should_validate_this_epoch` when training begins.
- Because `on_epoch` is called at the _end_ of every epoch, it needs to consider `epoch + 1` (instead of `epoch`) when setting `_should_validate_this_epoch`.
- Update `TrainerTest.test_should_validate_callback` so that it fails without these fixes.
section of the `CONTRIBUTING` …
> Fix ShouldValidateCallback

- CHANGELOG.md
N/A
- I accidentally placed the changes from #5534 in the wrong place in the changelog. This PR just moves them to the correct place.
> Move changes from #5534 to correct place.

- CHANGELOG.md
- allennlp/training/callbacks/should_validate.py
- tests/training/trainer_test.py
Addresses another bug in #5534. Sorry my original PR had so many bugs in it!
The `ShouldValidateCallback` merged in #5534 was missing the method `on_end`. This caused validation to never occur at the end of training, even if the final epoch satisfied `validation_start` and `validation_interval`. I added an additional check to the test for this scenario.
> Fix should validate callback train end

- tests/modules/sampled_softmax_loss_test.py
**Patch description**
Hi,
The test `test_sampled_equals_unsampled_when_biased_against_non_sampled_positions` in `sampled_softmax_loss_test.py` has an assertion bound (`assert (abs(pct_error) < 0.001)`) that is too loose. This means potential bug in the code could still pass the original test.
To quantify this I conducted some experiments where I generated multiple mutations of the source code under test and ran each mutant and the original code 100 times to build a distribution of their outputs. Each mutant is generated using simple mutation operators (e.g. > can become < ) on source code covered by the test. I used KS-test to find mutants that produced a different distribution from the original and use those mutants as a proxy for bugs that could be introduced. In the graph below I show …
> tighten test_sampled_equals_unsampled_when_biased_against_non_sampled_positions bound

- allennlp/modules/stacked_alternating_lstm.py
Title in original paper is with 1 L: https://www.aclweb.org/anthology/P17-1044.pdf
Fixes # .
- Changes `Labelling` to `Labeling` to reflect the papers title
- [ x] I've read and followed all steps in the [Making a pull request](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#making-a-pull-request)
- [x ] I've updated or added any relevant docstrings following the syntax described in the
> Small typo

- CHANGELOG.md
- allennlp/common/testing/test_case.py
- tests/commands/cached_path_test.py
The test suites of allennlp (and several sister/daughter libraries) implicitly depend on being run directly in the source directory, and cannot succeed being run against being actually installed somewhere on the system (e.g. the conda environment).
Since I like to run the full test suite wherever possible to validate that the library as packaged works correctly, I therefore need to patch this in most of the allennlp libraries. As conda-forge has now become one of the "officially" recommended ways of installation, I wanted to kindly ask if the project would consider picking up these patches (I'm using this PR as a stand-in for discussion, there'd be other very similar ones), which should hopefully not be intrusive and would help me a lot.
> Make tests runnable out-of-tree for help with conda-packaging

- CHANGELOG.md
- allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
Fixes this question: https://stackoverflow.com/questions/71167641/in-allennlp-how-can-we-set-sub-module-argument-in-pretrainedtransformermismat
- Added "sub_module" argument in PretrainedTransformerMismatchedEmbedder initializer.
> Add "sub_module" argument in PretrainedTransformerMismatchedEmbedder

- CHANGELOG.md
- allennlp/commands/evaluate.py
- test_fixtures/basic_classifier/common.jsonnet
- tests/commands/evaluate_test.py
- tests/models/multitask_test.py
> Makes the `evaluate` command work for the multitask case (Second Edition)

- CHANGELOG.md
- allennlp/common/file_utils.py
- dev-requirements.txt
- requirements.txt
Fixes #5585
Changes proposed:
- Adds a tighter pin on `cached-path` to catch breaking changes in the future.
- Makes sure our `cached_path()` wrapper still returns a `str`.
- Also pins `docspec` which is needed to build the docs.
See also https://github.com/allenai/allennlp/pull/5586.
> pin cached-path tighter, make sure our cached-path wrapper still returns `str`

- CHANGELOG.md
- allennlp/data/tokenizers/pretrained_transformer_tokenizer.py
- tests/data/tokenizers/pretrained_transformer_tokenizer_test.py
This commit aims to support #5597
- Add `custom_dummy_tokens` argument to `PretrainedTransformerTokenizer`. Without that argument, initializing `PretrainedTransformerTokenizer` of some non-English models fail.
> Add `custom_dummy_tokens` to `PretrainedTransformerTokenizer`

- tests/common/push_to_hub_test.py
This test is broken with the new version of huggingface-hub. The failures are all related to the test, not to the functionality. I don't think we can fix it ourselves, and I also don't think that this feature gets a lot of use, so I just want to disable the test, and remove the feature altogether the next time this breaks.
> Disable hub upload test

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- allennlp/common/file_utils.py
- dev-requirements.txt
- requirements.txt
- tests/common/file_utils_test.py
- Mostly changes to the CI. Using `pip-tools` to  resolve versions of primary and non-primary dependencies, so that we don't download multiple versions of multiple packages. 
- Also using `venv` instead of `conda`, which was [several times slower](https://stackoverflow.com/questions/67978161/why-is-conda-so-much-slower-than-pip-when-installing-libraries).
- Combined effect of the two (but especially `pip-tools`) has reduced the virtual environment caching time from hours (we stopped trying after 1 hour) to ~5 min.
- Pinning versions for more packages now.
- Commenting a couple of test cases for the time being. They will be fixed on `cached-path`, and then uncommented.
> Update cached_path version

- requirements.txt
- Relaxed `protobuf` requirement from `protobuf==3.20.0` to `protobuf>=3.20.0,<4.0.0`, to allow for security patch `3.20.1` patch on `protobuf`
> Relax requirements on protobuf to allow for minor changes and patches.

- .github/workflows/ci.yml
- allennlp/modules/conditional_random_field/__init__.py
> Allowed transitions

- README.md
I´m super sad that allennllp is veen deprecated. I was looking for alternatives to port my projects and I think that the best candidate is the Flair library. It have many of qualities of Allennlp such as the academic focus and the framework composability. I think it would be nice to add as an alternative.
> Add flair as an alternative
